### ISSUE TITLE
Misc Maintenance issues

### ISSUE THREAD

**Issue by drowe67** [drowe67/freedv-gui#10]
This software needs some maintenance and refactoring, any help with the following would be greatly appreciated.  In no particular order:

1. Remove unnecessary PortAudio Wrapper layer
1. ~~break fdmdv2_main.cpp into smaller files~~
1. ~~Rename src files from fdmdv2_* -> freedv_* (or maybe remove prefix)~~
1. Align license text in source files with LGPL

**Comment by hobbes1069** [comment]
Fedora 28 will be EOL in about a month or so now that F30 is released...

**Comment by drowe67** [comment]
> Fedora 28 will be EOL in about a month or so now that F30 is released...

OK. Is there anything we need to do in FreeDV to address this?

**Comment by hobbes1069** [comment]
Does the problem only happen on Fedora 28? We may just be able to ignore it. I'll play around with it this weekend.

**Comment by drowe67** [comment]
Thanks Richard - there was also a post on the codec 2 mailing list from Al Bear 21 April re a tweak rqd he needed for Fedora 29.

**Comment by DG9BFC** [comment]
at least point # 5 is solved :-)
runs now from top to bottom (like in other sdr soft)
if we now lower the resolution to have a higher speed available (without increasing cpu load!) then we maybe could make the waterfall text from sdr console readable (good for announcing a mode change)
greetz sigi dg9bfc
ps ... another thing for your todo list ... add PTT INPUT ;-) ... wink wink

**Comment by drowe67** [comment]
This ones been open for a few years and I don't feel it has much value any more.  Just a few minor wants rather than needs for the code.
