### ISSUE TITLE
FreeDV About using Hamlib on Windows 

### ISSUE THREAD

**Issue by hiro2818** [drowe67/freedv-gui#101]
FreeDV About using Hamlib on Windows 

PTT control of transceiver using Hamlib
Set to control and control with Test PTT
Check what you can do and press the start button
Start receiving FreeDV.
Then press PTT to start sending
The transmitter is not a digitally modulated signal
The analog signal from the microphone is used as it is for the transmitter input.
It is input and the radio wave of analog SSB is emitted.

The version I am currently using is the Windows version.
The sound device uses two sets of USB audio devices.
This issue may be occurring in my own environment
FreeDV1.5.1 Ver1.4.1 had the same symptom.

**Comment by drowe67** [comment]
@hiro2818 it would be better to post this kind of issue to the Digital Voice Google Group as it's more likely a set up issue than a problem with the software.  We have many reports of people using FreeDV to successfully transmit digital modulated signals.

Is the Analog button pressed?
