### ISSUE TITLE
error Assertion `nout <= freedv_get_n_max_speech_samples(f)' failed.

### ISSUE THREAD

**Issue by netmate1234** [drowe67/freedv-gui#106]
freedv: /home/martin/temp/freedv-gui/codec2/src/freedv_api.c:823: freedv_bits_to_speech: Assertion `nout <= freedv_get_n_max_speech_samples(f)' failed.
Aborted (core dumped)

(Running 2020. It comes often, Ubuntu  20.10. FreeDV 1.5.2 dev.)

**Comment by drowe67** [comment]
Pls see https://github.com/drowe67/freedv-gui/issues/107 suggestions (1) and (2)

**Comment by drowe67** [comment]
Closed as no response from OP

**Comment by netmate1234** [comment]
I removed 3 assserts in codec2. now its stable.

**Comment by drowe67** [comment]
Removing asserts is a bad idea - they are there to trap unexpected and illegal behavior.

**Comment by drowe67** [comment]
@tmiw :point_up: this might be related to what Kanda is reporting :thinking:

**Comment by drowe67** [comment]
@timw I popped this into the top of `freedv_rx` and the assert fired:
```
    fprintf(stderr, "max_speech_samples: %d max_modem_samples: %d\n", 
        freedv_get_n_max_speech_samples(freedv), freedv_get_n_max_modem_samples(freedv));
    {
        int nout = 2*freedv_get_n_max_modem_samples(freedv);
        assert(nout <= freedv_get_n_max_speech_samples(freedv));
    }
```
I think I know what's going on here:
1. When we are out out sync (and squelch is off), we run through that pass through code, the input modem samples are oversampled up to the 16 kHz speech sample rate so we can hear the off air rx audio.
1. When the demod is out of sync it will just ask for the nominal number of input samples, which satisfies the assert.
2. However if we fall out of sync, it's possible `nin` might be set to `max_modem_samples` on the last modem frame processed before we fall out of sync.  Doesn't look like there is enough storage for that case, so the assert fires.
3. I haven't been able to reproduce the actual issue, as it requires a few conditions to line up, but can see how it might happen from analysis.  Just in 2020 I suspect.

**Comment by drowe67** [comment]
OK by forcing nin to be the max in `freedv_rx.c`:
```
        nin = freedv_nin(freedv);
        nin = freedv_get_n_max_modem_samples(freedv);
        /* optionally read some stats */
```
I can also trigger another assert (I have seen this once before):
```
./src/freedv_tx 2020 ~/LPCNet/wav/all.wav - | ./src/cohpsk_ch - - -20 | ./src/freedv_rx 2020 - /dev/null -v
<snip>
freedv_rx: /home/david/codec2/src/fdmdv.c:1770: fdmdv_8_to_16: Assertion `(n % FDMDV_OS) == 0' failed.
```
I hit that once [before](https://github.com/drowe67/freedv-gui/pull/109#issuecomment-808800860).

**Comment by drowe67** [comment]
https://github.com/drowe67/codec2/pull/176

**Comment by tmiw** [comment]
@drowe67, I assume the PR fixes that additional assert as well?

**Comment by drowe67** [comment]
I think this one was fixed with https://github.com/drowe67/codec2/pull/176
