### ISSUE TITLE
[Feature Request] repeater function

### ISSUE THREAD

**Issue by netmate1234** [drowe67/freedv-gui#113]
If we had a port or 2 that could serve as raw bitstream transfer between 2 freedv apps. Just to recondition the signal without going threw the codec.

Cool app ;)

**Comment by drowe67** [comment]
There is the https://github.com/drowe67/freebeacon and also third party "parrot repeaters".  A repeater is best implemented as an application that sits on top of libcodec2, rather than as a feature of freedvi-gui. You are correct that you don't need to decode he speech.
