### ISSUE TITLE
command line freedv-gui to support testing

### ISSUE THREAD

**Issue by drowe67** [drowe67/freedv-gui#118]
A way to run freedv-gui from the command line, put it into a mode (e.g 700D), set up input and output sound cards, and feed a signal through it.  This way basic freedv-gui operation can be tested using a GitHub action.  

1. Not sure what happens to the actual screen on a headless GitHub action machine.
1. Rx only is OK for a first pass.  
1. ALSA loopback sound cards could be used to simulate real sound card hardware (see `codec2/unittest/tnc*` tests for examples).
1. Sox could be used for command line sample I/O from sound cards to files.

**Comment by tmiw** [comment]
Perhaps we can implement #104 as a command line option to specify a config file to partly implement this? I believe FreeDV uses the configuration registry (Windows Registry on Windows and wherever it's stored on other platforms), so it should be a simple code change to make it use config files instead.

**Comment by drowe67** [comment]
Sure that would work, the config is stored in `~/.FreeDV` on Linux already (and perhaps MacOS).  Not sure how to handle Windows, using the registry is kind of a convention.  However most of our testing is on Unix type systems.

**Comment by tmiw** [comment]
BTW, ~/.FreeDV is only used on Linux; ~/Library/Preferences/FreeDV Preferences is apparently used on macOS (and the Windows Registry used on Windows). I listed those defaults in the user manual as part of #119.
