### ISSUE TITLE
Assertion failed on Fedora 29

### ISSUE THREAD

**Issue by hobbes1069** [drowe67/freedv-gui#12]
Ok, I always do all my devel work on a separate login so this morning I cloned freedv-gui/brad-2020 from my regular account and did a build using the internal build method and got:
```
freedv: /home/richard/git/freedv-gui/src/fdmdv2_main.cpp:4082: void txRxProcessing(): Assertion `ret != -1' failed.
```
as soon as I clicked "Start"

**Comment by ac0zj** [comment]
That's a result of the tx output fifo being too small.  I can, through Tools->Options, set the Fifo Size to 400, and then I can transmit and not get the same error.

I tested this earlier:  I got rid of the assert, and I *think* I was able to leave the fifo size at 350.  I tried bumping it down,  and eventually started getting choppy sounding audio when I demodulated.

I'm guessing only getting one when you press transmit is ok, but obviously getting a bunch is not good. 

A couple ways to solve this; I'm open to suggestions.  We could just get rid of the assert, and I'm guessing, leave at 350 and we'd be ok, but I'd test for sure.  I could test even bumping it down (was it at 250 prior to 2020?).  We could have something adaptive - but that would add a layer of complexity.

**Comment by drowe67** [comment]
I faced the same issue with 700D, especially when people started running it on a variety of machines...

I'm sure we can get it stable without too much effort, or the need for pop ups and adaption.  We should avoid asserts if it doesn't really cause anything fatal.  We want things to "just work" so best to get to the bottom of the bug and nail it.  My approach for 700D was add some debug counters and get a bunch of people to test.

**Comment by drowe67** [comment]
@hobbes1069 Just tried Fedora 28.  I rm-ed ~//FreeDV first, selected the default (top) audio devices, and selected 2020 mode and hit Start.  Decoded ```all_2020.wav`` test file just fine. Upgrading to Fedora 29 now.

When running, it is printing out these messages all the time, no matter what tab is selected:
```
(freedv:31234): Gtk-WARNING **: 18:22:46.347: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node trough, owner GtkProgressBar)

(freedv:31234): Gtk-WARNING **: 18:22:46.447: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node trough, owner GtkProgressBar)
```

**Comment by drowe67** [comment]
@hobbes1069 Fedora 30 working well on receive too, however that GTK error is printed out all the time as above.

**Comment by hobbes1069** [comment]
Most of the time those types of errors can be ignored. I see them frequently on GTK based apps. Not to say I see this specific error, it just seems to be common to get them. Or we can try to hunt them down.

I haven't had a lot of time to test the new build but a lot of the entry boxes don't seem to be the right size, specifically the ones for FIFO buffers.

**Comment by drowe67** [comment]
OK I traced it to widget resizing.  When my FreeDV window is small, it shrinks the level gauge to zero height, and the warnings pop up.  A fix would be disable updating the gauge if it's height is zero, or adjust the layout so the gauge has a minimum height. I don't know enough about WxWidgets to make this happen. 

I guess these warnings are disabled in Ubuntu.

@hobbes1069 can you pls tell me if you are still getting the original problem raised in this issue (bombing out with an assert)?

**Comment by hobbes1069** [comment]
Yes, upping the FIFO buffer to 400 solved the assert.

**Comment by drowe67** [comment]
All fixed thanks guys.  We'll have to leave the warnings for another day.
