### ISSUE TITLE
Uninstall should remove configuration

### ISSUE THREAD

**Issue by drowe67** [drowe67/freedv-gui#14]
Registry entries on Windows, ~/.FreeDV on Linux

**Comment by hobbes1069** [comment]
When I have some time (haha) I can take a look and see if there's some option I can pass to the NSIS installer to remove registry entries but I don't think there's any practical way to remove configuration files on *nix...

**Comment by tmiw** [comment]
Would the following in CMakeLists.txt be sufficient, you guys think?

```
set(CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS "reg delete HKEY_CURRENT_USER\SOFTWARE\CODEC2-Project\FreeDV /f")
```

Sources: [CMake documentation](https://cmake.org/cmake/help/latest/cpack_gen/nsis.html) and [here](https://www.windows-commandline.com/delete-registry-key-command-line/).
