### ISSUE TITLE
No source releases or tags

### ISSUE THREAD

**Issue by wkazubski** [drowe67/freedv-gui#150]
Windows binary is actually on 1.5.3, but there is no source releases (or even tags) since 1.4 almost 2 years ago

**Comment by tmiw** [comment]
@wkazubski, we just released 1.6.0 (https://github.com/drowe67/freedv-gui/releases/tag/v1.6.0), which includes tarballs as well as Windows and macOS binaries. Let us know if there's anything missing in there.

**Comment by tmiw** [comment]
@drowe67, can this be closed?
