### ISSUE TITLE
Feature Request: Ouput Volume control

### ISSUE THREAD

**Issue by drowe67** [drowe67/freedv-gui#17]
Tom,  N4FWD, has requested an output volume control for driving his radio from FreeDV:

> there is no "volume" control for the transmit output of
> FreeDV. That shortcoming would be mitigated if FreeDV used PulseAudio.
> Honestly, I should not be forced to modify the radio's internal
> settings just to accommodate FreeDV. The audio drive should be set in
> software and not in the rig.

**Comment by DG9BFC** [comment]
audio drive is low when using virtual cable and sdr software ... could be 6 to 10 db more in some modes
i have to crank up drive and mic gain to full while in voice i need much lower drive and mic gain
so if you add a volume control  for tx level (i can use level slider in virtual cable also) ... then also set the levels higher what comes out of the software ... 3 to 6 db ... maybe 10 dependingt on mode (1600 is quite low compared to 700 or 800xa)
greetz sigi dg9bfc

**Comment by drowemyriota** [comment]
I do not want to add another level control to FreeDV, as I feel this will just add to the general confusion around setup. For Tx on my station I already have two controls (laptop and a Tx level on the radio/external rig blaster card).

On Tx my aim to have a constant peak drive level from all modes.  I recently adjusted FreeDV 700C/D/E and 2020 to have the same level (half full scale).  The others will need to be brought into line in the future. This is enough to drive my radios to full power.

If we get many requests for a different peak drive level we could consider changing it.

**Comment by DG9BFC** [comment]
with an sdr and virtual cable the drive is a bit on the low side ... i had to set the drive setting way higher in sdr console as i have to do with other digi modes (sstv or whatever) to reach half power out ... so the levels could be much higher in my view (in minimum 3 db better 6 to 10 db depending on mode!!)
for sure that lower levels are enough to drive external radios ... but that is cause all normal radios have a very sensitive mic input (only a few mV needed) while the level of a soundcard line out is way higher
but ... in an sdr setup with virtual cable its different ... all is on a digital level ... and i set all levels in the virtual cable chain to 100 (can not set it higher) ... so the only way to get to a resonable level is cranking up the drive in sdr console (to much higher setting as i use in all other modes ... be it normal voice or any other digi mode soft) ... danger of overdrive when change mode back to normal voice!!!
i can do a list how much higher the levels should be (depending on mode) ... if you want that list i do some measurements ... ?!?!? ... just drop me a line
 ... using higher levels on output and then using a resistor divider for external radio means also lower noise that may couple in your audio chain ... be it hum noise or whatever ... wink wink
sdr and analog rig users ... both can live with a higher level i think
what about a simple checkbox in the audio settings "boost audio level" ... and increase all levels say 6 to 10db or so ... (default after install the checkbox is off) ??? ... in hdsdr the programmer (after i asked for it) made an audio boost plus 10 to 20 db but hidden in registry settings (so only to be found for users with some background and knowledge) ..t . do you see any chance to get the levels a bit higher?? or do i have to write a "new issue" for that?? (new issue would be increase levels ... this one was output volume control so it is a bit hijacking the thread ... sorry!!!)

**Comment by drowe67** [comment]
The Tx audio is  sequence of 16 bit samples.  They are already at around half full scale, just less than 6dB beneath the clipping level.  I am not inclined to set them any higher as this will lead to clipping with some waveforms.  This is a reasonable level for any further audio processing.

It is unreasonable to expect FreeDV to handle every users audio processing chain.  How audio levels are handled after they leave FreeDV is the responsibility of the end user.
