### ISSUE TITLE
Hamlib 4.3 change always selects VFO A at TS-890 open

### ISSUE THREAD

**Issue by Tyrbiter** [drowe67/freedv-gui#170]
Since hamlib-4.3 appeared I see behaviour that is not ideal with freedv.

The problem is that due to changes apparently needed for WSJT-X (https://github.com/Hamlib/Hamlib/issues/745) my TS-890 gets switched to VFO A when the start button is clicked, while I often use freedv with VFO B selected. I think that it shouldn't matter which VFO is in use. Mike W9MDB suggested arranging it so that a start click only opens the radio on the first use, then any change of VFO will be accepted. I suspect this would cause problems with changing settings in freedv, I'm not sure.

Just noticed that if I manually change VFO and then use freedv's PTT button I get a mode error (because originally the frequency in use required USB) and the frequency/mode is not rechecked.

Perhaps I'm being difficult, but I don't see why a 3rd party library should hijack my way of doing things. All programs ought to be well-behaved enough to leave a radio how they found it.

Is a change to work around this difficult to implement in freedv?

**Comment by drowe67** [comment]
@Tyrbiter as you mentioned in the title this is a HamLib issue, not  a FreeDV issue.  It's also very specific to your personal use case.  Given both HamLib and FreeDV are open source you are free to address this yourself with source code changes to your personal repo.

I'm closing this as  a FreeDV issue, but you are welcome to discuss further in Discussions](https://github.com/drowe67/freedv-gui/discussions).
