### ISSUE TITLE
1.6.1 Build fail in Mageia cauldron - missing reliable_text.h

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#174]
Attempting to update our Mageia package I have hit this:-
In file included from /home/baz/rpmbuild/BUILD/freedv-gui-1.6.1/src/main.h:95,
                 from /home/baz/rpmbuild/BUILD/freedv-gui-1.6.1/src/dlg_audiooptions.cpp:22:
/home/baz/rpmbuild/BUILD/freedv-gui-1.6.1/src/freedv_interface.h:34:10: fatal error: reliable_text.h: No such file or directory
   34 | #include "reliable_text.h"

reliable_text.h does not seem to be provided by anything that I can find.

Building against codec2-1.0.0 and wxgtk3.0 (or 3.1).

**Comment by drowe67** [comment]
Hi @barjac - I think `relaible_text.h` is available in `codec2/master`.  The feature (and freedv 1.6.1) was only recently developed, so we don't have a corresponding codec2 tag.

**Comment by tmiw** [comment]
@drowe67, is codec2 ready to tag as 1.0.1?

**Comment by drowe67** [comment]
Here you go: https://github.com/drowe67/codec2/releases/tag/v1.0.1

**Comment by tmiw** [comment]
@barjc, let us know if that release works and we can close out this issue.

**Comment by barjac** [comment]
Hi,
Yes, thanks, that has fixed the problem, however there is still a minor issue with the package build related to lpcnet_get_hash() which is called in the 'About' dialogue. This is not defined anywhere that I can find, so for now I have removed it from /src/ongui.cpp. Line 154.
`-                FREEDV_VERSION, FREEDV_VERSION, GIT_HASH, freedv_get_hash(), lpcnet_get_hash());
+                FREEDV_VERSION, FREEDV_VERSION, GIT_HASH, freedv_get_hash());`

**Comment by srsampson** [comment]
Located:

https://github.com/drowe67/LPCNet/blob/master/src/lpcnet_freedv.h#L23

LPCNet is imported into the build in the build_linux.sh script I believe, so would be in the library produced and linked.

**Comment by barjac** [comment]
OMG! I never saw that script before. I can't imagine how that process can be packaged. My first thought is that we would need a vanilla codec2 package available in the repos, but I will consider our options.
Thanks for alerting me to this!

**Comment by Tyrbiter** [comment]
freedv, codec2 and lpcnetfreedv are all packaged separately in Fedora, you could look at how it's done by downloading the src rpms from https://koji.fedoraproject.org/koji/packages

**Comment by barjac** [comment]
> freedv, codec2 and lpcnetfreedv are all packaged separately in Fedora, you could look at how it's done by downloading the src rpms from https://koji.fedoraproject.org/koji/packages
Yes thanks,  that is my next port of call before trying to re-invent the wheel.

**Comment by tmiw** [comment]
@barjac, any updates on this?

**Comment by barjac** [comment]
Hi, Yes I have managed to get a working(?) package built now by adding a switch in the codec2 package spec to allow a temporary vanilla build. All very messy and easy to break if another packager pushes a build without knowing the right hoops to jump through and in which order. Or if I forget. :( 
Testing is a problem as I have yet to find a live transmission on any band. Also the configuration is beyond comprehension for a casual user, which possibly explains the lack of signals. I have had some success with the audio file samples, so it seems to be working on RX at least.

**Comment by drowe67** [comment]
Closing this as I don't think it requires any further freedv-gui or codec2 coding, it's more a packaging project for a specific distro.  Happy to re-open if further assistance is required.
