### ISSUE TITLE
Waterfall Speed adjustable (feature request)

### ISSUE THREAD

**Issue by cybork42** [drowe67/freedv-gui#176]
Dear experts.
I would like to suggest to make the **waterfall speed adjustable**.
- as part of the "Options - Display" tab (maybe any way an idea to rename that tab to "Waterfall" as there are waterfall settings only right now?)
- with three tiny radio buttons on the main screen (fast / mid/ slow) (the settings for each might have been part of above Options menu)

What for that suggestion?
When using freeDV for example during skeds, it's sometimes difficult not to overlay with some other ham as audio decoding takes some time, and the waterfall with its typical speed may not yet show what the S-Meter on the TRX already suggests (someone else transmitting already...). Faster waterfall might help in such situations. Also think about a possible upcoming contest capability... you need to see if you're already to late to press PTT...

73 de Andreas (DM4AB).

**Comment by tmiw** [comment]
BTW if you can repost this at https://github.com/drowe67/freedv-gui/discussions, that would be good. The issues area is for bugs with FreeDV and not feature requests.

**Comment by cybork42** [comment]
moved over to diuscussion category.
