### ISSUE TITLE
Feature request - Please provide simplified audio setup for recieve only systems.

### ISSUE THREAD

**Issue by g0hww** [drowe67/freedv-gui#185]
It is not possible to quickly configure a receive only system to allow me to rapidly listen to freedv transmissions without being forced to go through the process of configuring transmit audio paths.

I would like to be able to disable the transmit capability, so that I can simply configure the receive audio paths.

My HF kit is capable of transmitting, and is configured to allow all routing of Tx and Rx audio for digimode progs such as JS8Call, QSSTV, ARDOP or FLDigi through Pulse Audio.  I don't tend to keep a headset connected to that Linux box, so generally don't have a mic available. More often than not, I just want to listen to some FreeDV audio, with analog voice coming from the laptop's speakers.

Going a bit off topic now ...

Ideally, all input and output streams could be pointed to the "pulse" device, with actual configuration left to tinkering with PAVU Control.  I have some hopes that a resolution of #16 would improve the situation. However, the 2 second test is not sufficient to switch back and forth between PAVU Control and the FreeDV GUI in order to configure pulse audio externally. It would be preferable to have an infinite test duration.  Also,  the UI does not let me configure Pulse as the device for all 4 audio inputs and outputs.  I feel that it should allow this.  Obviously it would be down to the user to ensure that things are sanely configured.

**Comment by drowe67** [comment]
> It is not possible to quickly configure a receive only system to allow me to rapidly listen to freedv transmissions without being forced to go through the process of configuring transmit audio paths.

This is covered at the start of the FreeDV manual.

Re off topic and other detailed discussion - pls open a topic in [Discussions](https://github.com/drowe67/freedv-gui/discussions).  We'd like to use Issues only for demonstrable bugs.

**Comment by g0hww** [comment]
Oh, wow. OK. I have dabbled with FreeDV on and off for a number of years and never even considered looking for a manual before. Thanks.

**Comment by tmiw** [comment]
BTW, there's also some info [here](https://groups.google.com/g/digitalvoice/c/robpK8BOjfI/m/Pa-K4IEaBAAJ) on building a version of PortAudio that has PulseAudio enabled and subsequently including it in FreeDV. That will at least allow Pulse devices to show up instead of needing to choose the generic "pulse" device. Once that PR finally gets into PortAudio and new distro packages made, FreeDV should be able to handle PulseAudio with little to no modification.

**Comment by drowe67** [comment]
@tmiw re [knowing there is a FreeDV manual](https://github.com/drowe67/freedv-gui/issues/185#issuecomment-966257904) - perhaps we could make the existence of the manual more obvious?  For example;
1. Install the PDF version as part of the installer.  Only problem is this won't track updates like a link to a live version.
2. A pop up dialog with a hyperlink the first time FreeDV is run (or when defaults are reset).  But not every time it starts, that would get annoying.
3. Link to it in off the Help menu.

**Comment by tmiw** [comment]
I'm thinking 1 and 3 since it's probably not preferred for the PDF version that's installed not to be sync with the latest. I'll see what's needed on the code side.
