### ISSUE TITLE
"/usr/bin/bash" or "/bin/bash" for ./build_linux.sh 

### ISSUE THREAD

**Issue by cybork42** [drowe67/freedv-gui#199]
I think my Linux setup is aged, but not special or weird. 
My **bash** command interpreter resides in **/bin/bash**. 
Is this special, or is the install script special?
```
lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```
Install script "build_linux.sh" starts with:
```
#!/usr/bin/bash
# build_ubuntu.sh
```

**Comment by tmiw** [comment]
For me, both /bin/bash and /usr/bin/bash exist on Ubuntu 21.10 and seem to be the exact same file:

```
mooneer@ubuntu:~/freedv-gui$ sha512sum /bin/bash /usr/bin/bash
0e1018c5e7696ce92708ac8cb68da146e0533e7f5d39818333e1450167746d2361dbc767fcb26b358ce1140402ceda1405f76d1a42645e2a08f243d4aea2ae84  /bin/bash
0e1018c5e7696ce92708ac8cb68da146e0533e7f5d39818333e1450167746d2361dbc767fcb26b358ce1140402ceda1405f76d1a42645e2a08f243d4aea2ae84  /usr/bin/bash
mooneer@ubuntu:~/freedv-gui$ 
```

Though it probably wouldn't hurt to make it something like `#!/usr/bin/env bash` (as per [this StackOverflow question](https://stackoverflow.com/questions/10376206/what-is-the-preferred-bash-shebang)).
