### ISSUE TITLE
when starting and resizing, waterfall appears garbled

### ISSUE THREAD

**Issue by cybork42** [drowe67/freedv-gui#201]
When starting up FreeDV (latest sources on main branch), the waterfall section of the GUI somehow misaligns taking over (probably not initialized?) memory content from somewhere. 
The screen after fresh startup looks like this:
   https://c.web.de/@337855112338741224/awaJ_NnJR0mvTVSpS3wHbA/ROOT/ROOT

When modifying source code of "plot_waterfall.cpp" line 104 from
`gc->DrawRectangle(PLOT_BORDER + XLEFT_OFFSET, PLOT_BORDER + YBOTTOM_OFFSET, m_imgWidth, m_imgHeight);
`
to
`gc->DrawRectangle(PLOT_BORDER - XLEFT_OFFSET/2, PLOT_BORDER - YBOTTOM_OFFSET/2, m_imgWidth, m_imgHeight);
`
the startup screen looks ok. However, when resizing, again garbled content pushes into the waterfall section. 
I guess there might be some general mis-calculation of the waterfall section size?

OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

**Comment by tmiw** [comment]
Do you have display scaling enabled? I'm wondering if the issue is related to that?

**Comment by cybork42** [comment]
Not that I am aware of. My Ubuntu runs native on hardware, nothing special. I believe that the effect is platform and possibly also architecure specific though. I guess it depends on memory init with default values or some other stuff. Amazingly, the content taken as "garbage" into the black rect is what was there on the screen eralier before the FreeDV window popped up. Not sure how this happens. Probably there is a Linux frame buffer which provides the data, or the wx toolchain doesn't overwrite the frame buffer if not explicityl addressed to do so.

However, it's strange that it goes away when resizing the black rect...

**Comment by drowe67** [comment]
I've seen junk on the black rectangle of the waterfall for years, but haven't been able to determine the root cause.  My best guess is it's a quirk of wxWidgets.

A PR that fixes the problem would be most welcome :slightly_smiling_face:

**Comment by tmiw** [comment]
> I've seen junk on the black rectangle of the waterfall for years (on Linux), but haven't been able to determine the root cause. My best guess is it's a quirk of wxWidgets.
> 
> A PR that fixes the problem would be most welcome 🙂

On that note, I'm pretty sure we're not using best practices for high-DPI displays per [wxWidgets' documentation](https://docs.wxwidgets.org/trunk/overview_high_dpi.html), so if nothing else a cleanup would be beneficial.

**Comment by cybork42** [comment]
merged commit cd1555d

**Comment by cybork42** [comment]
merged commit cd1555d
