### ISSUE TITLE
USB modulation input path into Kenwood TS890

### ISSUE THREAD

**Issue by cybork42** [drowe67/freedv-gui#206]
I'm writing this on behalf of a fellow ham. We've been trying to fix the same problem now for two evenings, but we've failed and we're running out of ideas and suspect this might even be a problem in the FreeDV handling of that Kenwood TS890 (??). All hints welcome!

Setup: TS890 works fine in general with a lot of modes, and also with FT8, FLDIGI and other digital ham applications: all programs succeed in producing TS890 internal Audio to modulate the TX path. Receiving with FreeDV works fine.

**Problem:** FreeDV fails to activate (?) or switch to (?) the USB output of the TS890 internal sound card fpor TX modulation. After pressing "PTT" in FreeDV, all seems normal, but no drive to TXR gets supplied. Instead, the TS genuine mic connected to the front panel is still active, tapping on that mic drives the TXR and modulates the TXR. The internal sound card output is not used for modulation. 

Funny, strange, no idea what's going wrong. Change application, all works fine, revert back to FreeDV -> no TX out.
Anyone with any idea?

**Comment by Tyrbiter** [comment]
I have a TS-890, freedv works for me with the exception of a problem of remembering devices on the playback tab of pavucontrol. I don't have a front panel microphone, I use a USB mic.

Suggest you have a look at the mod.sel settings (long press of DATA mode button) and see how it's set up. freedv does not change modes (although it checks them to warn about USB/LSB above/below 10MHz). I have both front audio input settings set to Off, and both rear audio inputs set to USB Audio.

**Comment by tmiw** [comment]
This might be silly, but have you confirmed the following:

1. Data Mode is set to On.
2. Data On->Send/PTT is set to "USB Audio" per the below from [the TS-890S manual](http://manual.kenwood.com/files/B5A-2215-10.pdf):

![TS-890S Audio Source](https://user-images.githubusercontent.com/449242/149420541-329ff7be-7917-45aa-9547-5e51b8fd5380.png)

(As a note, WSJT-X doesn't have anything specific in its configuration to allow it to force the radio to use a different audio source. If it is indeed doing something to make the radio switch modes, it's something transparent to the user.)

**Comment by Tyrbiter** [comment]
Just note that SSB mode is what freedv should use, then the digital/analog mode switch works with IF filtering behaving as expected.

**Comment by cybork42** [comment]
@Trybiter: my fellow ham tried out your suggestions (thanks a lot for the screen-shot), and @tmiw - of course we studied all the material (full manual and the special addendum for digital operation :-)). However, no luck gained yet.
With Trybiter's settings, FT4 still works fine, but FreeDV doesn't modulate the TRX still.
Bottom-line: no gains yet.

@Trybiter: could you please provide FreeDV version, OS and Firmware version of your TS890? Mabe we have some funny version problem here. In parallel, we'll try to switch computer and OS to see if that changes anything.

Thanks a lot for trying to help on. The weird thing is that the TRX works in general and with other programs. Very strange indeed!

**Comment by Tyrbiter** [comment]
My TS-890 has firmware 1.04 and I use Fedora Linux currently Fedora 35.

freedv here is currently a development pulseaudio version, 1.7.0 although it gets rebuilt from the git version quite often and there is no released version as yet. Fedora 35 actually uses pipewire, pipewire-pulse and wireplumber which are also in heavy development and replace pulseaudio with a system-wide low-latency audio and video framework, if you're not using Linux then it probably is irrelevant.

If you are using Windows then you may find that you need to give freedv access to the audio devices you are using, I'm not sure exactly how but I do know that WSJT-X also needs these permissions. I think it is done on a program by program basis.

HTH

**Comment by cybork42** [comment]
one more Pingback: which TRX do you configure with the PTT dialog?

**Comment by Tyrbiter** [comment]
I have Hamlib PTT selected, the rig model is Kenwood TS-890S and my serial device is /dev/ttyUSB1

The hamlib installed is 4.4 and the Fedora package is the -1 revision, so it's as released by the hamlib guys.

**Comment by tmiw** [comment]
@cybork42, any updates? Were you able to get FreeDV working properly with the TS-890S?

**Comment by cybork42** [comment]
@tmiw: sorry, I forgot to close this one: the fellow ham unfortunately gave up, we faield to fix this one for him.

**Comment by cybork42** [comment]
not solved.

**Comment by tmiw** [comment]
That is unfortunate. I would think that if this ham got the 890 working with WSJT-X etc. FreeDV would have as well. Feel free to reopen if they want to try again.
