### ISSUE TITLE
FreeDV 2400B

### ISSUE THREAD

**Issue by jh0pcf** [drowe67/freedv-gui#21]
Nice to meet you, I am a Japanese amateur radio
I am JH0PCF Hiro.
Currently testing FreeDV 1.4.0.
Among them, only the 2400B mode does not generate a signal
Do you need any special equipment

**Comment by drowe67** [comment]
Hello Hiro,

No special equipment required.  However it is not a mode in common use and I haven't tested it for a long time, so perhaps it has a bug.

**Comment by drowe67** [comment]
Tested in 756534ed - 2400B seems to be generating a Tx signal now.
