### ISSUE TITLE
Windows Defender SmartScreen blocks recent FreeDV installers from running

### ISSUE THREAD

**Issue by tmiw** [drowe67/freedv-gui#213]
Reported on the digitalvoice list today (and duplicated by myself on Windows 11). From initial research, it seems that digitally signing the installers should at least make it happen less often.

Unfortunately, I'm not sure how difficult that'd be to automate using the existing CMake infrastructure. I'm seeing references online to `signtool.exe`, which is decidedly a Windows API tool. This could mean that if we do get a certificate and start doing this, we'll have to manually sign the installers before posting them up for download--definitely not ideal.

Anyway, I'll keep researching but suggestions are definitely appreciated.

EDIT: Note for myself to review and test later: https://stackoverflow.com/questions/18287960/signing-windows-application-on-linux-based-distros

**Comment by tmiw** [comment]
Some additional notes regarding this issue:

1. It seems that simply signing with a normal code signing certificate [doesn't immediately eliminate the issue](https://security.stackexchange.com/questions/139347/smart-screen-filter-still-complains-despite-i-signed-the-executable-why). Instead, FreeDV would need to have a sufficient number of downloads *after* starting to sign the binaries before Microsoft starts implicitly trusting them. 
    * Until that point, people will likely question whether FreeDV.exe and/or the installer is trustworthy, which may slow down adoption.
2. However, an EV code signing certificate bypasses a lot of (1) if not all of it. This is all well and good but there are a few problems with this approach:
    * An EV certificate is a multi-hundred USD/year investment based on the price lists of the [various Microsoft recommended certificate authorities](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate#step-2-buy-a-new-code-signing-certificate). This is significantly more than even a normal code signing certificate, which in itself isn't 100% trivial.
    * Just to *get* an EV certificate requires being a legally licensed business/nonprofit entity (pg. 23, [Guidelines for the Issuance and Management of Extended Validation Certificates](https://cabforum.org/wp-content/uploads/CA-Browser-Forum-EV-Guidelines-1.7.8.pdf)). FreeDV/Codec2 is not currently such in the US, Australia or any other country\*.
    * One nice thing about EV certificates, though, is that [you can have the private key be stored on 2FA tokens](https://www.ssl.com/faqs/faq-getting-started-with-your-ev-code-signing-certificate/). That should help at least a bit with security.

We have a few options at this point:

1. Update the user guide with bypass instructions for Windows, similar to what we did for macOS (https://github.com/drowe67/freedv-gui/commit/d664efa97abd419825a7b5942e9a7066de0d88cb). This could be done alone or in combination with one of the other options.
2. Purchase a non-EV code signing certificate and start signing Windows builds using it, with the understanding that the problem may not resolve itself immediately. Also, update the build scripts accordingly so the signing process can be somewhat automated. (IIRC, I saw one CA offering them at $69/year, so I may be able to cover the cost if we want to go this route.)
3. Bite the bullet, incorporate as a non-profit and get the EV certificate.

@drowe67, thoughts? Unlike with macOS, there are a lot more Windows users, so I'm not sure simply doing (1) is sufficient.

\* It might be a good idea to incorporate a 501(c)3 nonprofit at some point, anyway, mainly to help with getting additional funding for the project (e.g. from [ARDC](https://www.ampr.org/)). In California, at least, this [requires at least three board members and some additional overhead just to stay legal](https://calnonprofits.org/resources/starting-a-california-nonprofit).

**Comment by drowe67** [comment]
Hi @tmiw - thank you for looking into this.  This is the sort of issue that I struggle with (I like the experimental side of this project better) - so I am very happy for you to take the lead on this and follow your recommendation :slightly_smiling_face: 

I we need some money to make this happen I can help.

**Comment by tmiw** [comment]
> Hi @tmiw - thank you for looking into this. This is the sort of issue that I struggle with (I like the experimental side of this project better) - so I am very happy for you to take the lead on this and follow your recommendation 🙂
> 
> I we need some money to make this happen I can help.

I posted a message on the mailing lists as sort of a "brainstorming" thing because I'm not 100% sure how to proceed. At least for this particular issue, we could just do (1) and/or (2), but I feel like some other issue will come up that will eventually make us revisit how development should be steered/organized. I wouldn't say this is high priority, so we can probably wait to see if there's feedback before proceeding with whatever solution to resolve this PR.

**Comment by tmiw** [comment]
Some more technical info to try now that this may be moving forward: https://stackoverflow.com/questions/72504366/how-to-sign-windows-binaries-and-nsis-installers-when-building-with-cmake-cpac

On another note, obviously we don't want the certs/private keys floating around on public repos. However, I'm not sure if we need to worry about others potentially forking out the money to get their own certs and sign the installer, etc. themselves. Is that even a concern in the first place? (Presumably, people will see "FreeDV Project" or "Software Freedom Conservancy" in the certificate somewhere and presume that's the "official" build, right?) Thoughts would be appreciated.

**Comment by drowe67** [comment]
:thinking: You know I don't think we'd care if someone else went to the trouble of releasing a signed freedv-gui fork.  We can't control that anyway, and I'm not sure if we would want to - it's open source after all.

I think the core requirement here is simply making sure Defender doesn't choke when end users install freedv-gui.

**Comment by tmiw** [comment]
> I think the core requirement here is simply making sure Defender doesn't choke when end users install freedv-gui.

Agreed.

Currently I'm looking into possible certificate authorities. Some have the ability to store the key in a cloud-based HSM (e.g. [Azure Key Vault](https://learn.microsoft.com/en-us/azure/key-vault/general/basic-concepts), the equivalent AWS service or a few others) but I'm not sure how I feel about the project using any sort of cloud provider for this. 

Other than the cloud, the most common way seems to be via using some sort of hardware security token. There is a Linux equivalent to Windows' `signtool.exe` so I think I could kludge something together using CMake based on the info I've already found. Some/most of the HW token certificate authorities seem to need their software tool to actually be able to enter the 2FA required to sign the binaries. While they seem to have versions for Linux and macOS, they're definitely not open source (does/should that matter?)

HW token based certificate providers found so far (excluding discounts if we pay for 3 year validity instead of 1 year):

* [Sectigo](https://www.instantssl.com/code-signing-certificates): US$166/yr (non-EV), US$299/yr (EV)
* [Certum](https://certum.store/data-safety/code-signing-certificates.html): US$89/189 (non-EV, depends on whether we go for the "Open Source" one or not), US$399 (EV). Plus additional money for the HW token. *Note: The "Open Source" certificate doesn't let us put anything other than "Open Source Developer" as the Common Name.*
* [SSL.com](https://www.ssl.com/certificates/ev-code-signing/buy/): US$349/yr + US$249/each for HW tokens (EV)

As for EV vs. non-EV, I'd lean towards EV simply because it'd cause the installers/binaries to be insta-trusted. Non-EV would need a bit of a period (depending on the number of downloads) before Windows would start to trust it, and it sounds like that would get reset as soon as the certificate was renewed.
