### ISSUE TITLE
please verify: missing code line for MicInVol proper function

### ISSUE THREAD

**Issue by cybork42** [drowe67/freedv-gui#223]
It seems that on Windows and Linux the **MicInVolume Slider** doesn't have effect on the mic-in data to be processed. I believe I verified its function fine with a pre-release version, but with Release Version 1.7.0 it doesn't work any more. You can see the equalizer curve move up and down fine, but the adjustments has no effect on the processed mic signal whatsoever.

Tracking this down it seems that there is one statement missing in main.cpp:

```
            g_mutexProtectingCallbackData.Lock();
            if (cbData->micInEQEnable) {
                sox_biquad_filter(cbData->sbqMicInBass, infreedv, infreedv, nout);
                sox_biquad_filter(cbData->sbqMicInTreble, infreedv, infreedv, nout);
                sox_biquad_filter(cbData->sbqMicInMid, infreedv, infreedv, nout);
                sox_biquad_filter(cbData->sbqMicInVol, infreedv, infreedv, nout);   // missing !!
            }
            g_mutexProtectingCallbackData.Unlock();

```
Adding the line above, the function seems fine. Maybe this essential line got lost while preparing the release version?
73 de Andreas.

**Comment by tmiw** [comment]
Yeah, I noticed this when working on PR #219 and integrated the needed change in the 1.8.0 builds I've been emailing out. Let me know if those work okay for you. 👍

**Comment by tmiw** [comment]
The code that resolves this has been merged to master. @cybork42, can you confirm that this is no longer an issue?

**Comment by cybork42** [comment]
@tmiw: just finished building a Linux version from master branch: behaviour is fine now!
