### ISSUE TITLE
ammend "docker build instructions"

### ISSUE THREAD

**Issue by cybork42** [drowe67/freedv-gui#229]
Hello all. 
Just trying out to build FreeDV on Windows in WSL subsystems. Looks good so far.
However, looking at the docker build instructions, there is:

```
Building the docker images
Building is only required once, or if you modify the docker scripts

docker-compose -f docker-compose-win.yml build

```
It's probably a good ammendment to make clear that these steps are required beforehand?
```
$ git clone https://github.com/drowe67/freedv-gui.git
$ cd freedv-gui/docker
```
Once the docker images have been built, the instructions say:
```
Running the docker image to build Windows installers
  ./freedv_build_windows.sh 64
  ./freedv_build_windows.sh 32

```
What I found worthwile to note is "run this inside the "**freedv-gui/docker**"" directory, else you easily get mixed up with the other build_scripts one dir level above.

Best regards, Andreas.

**Comment by tmiw** [comment]
@cybork42, take a look at #231 and let me know if that looks okay?
