### ISSUE TITLE
update for hamlib

### ISSUE THREAD

**Issue by lu9dce** [drowe67/freedv-gui#245]
in some linux distributions as well as in the bsd
freedv has stopped working due to lack of update
from hamlib .. the new version 4.4
already used by other radio software
they leave us out of freedv
please consider updating this

https://www.freshports.org/comms/freedv/

tks

**Comment by lu9dce** [comment]
oh I am sorry
the new version runs perfectly
on freebsd 13.1

tks - sorry

73 - lu9dce

**Comment by tmiw** [comment]
No worries!

FYI for the future, you can build your own version of Hamlib and tell FreeDV to use it while building. `build_osx.sh` has an example of doing this if you're interested.
