### ISSUE TITLE
Identity of connected radio missing

### ISSUE THREAD

**Issue by Tyrbiter** [drowe67/freedv-gui#253]
Could freedv-gui please add the identity or model of the connected radio in the main window please.

Hamlib seems to change the list and this is not picked up by freedv so I end up wondering why the radio gets multiple selections, changing VFOs and similar because of the mismatch of the PTT setup with the real radio.

As an example if Kenwood TS-890S is selected then I would hope to see just TS-890S in the corner of the window.

**Comment by tmiw** [comment]
Give PR #256 a shot? It might be a while before we're 100% sure it solves your problem but we can at least see if there's any obvious major issues.

**Comment by Tyrbiter** [comment]
OK, I have rebuilt and installed this and will keep an eye on things. Hamlib has had a lot of changes and will continue to do so, that should give this a good test over the next few months.

Thanks for your assistance @tmiw
