### ISSUE TITLE
Release 1.8.0 depends on unreleased FREEDV_MODE_2020B from codec2

### ISSUE THREAD

**Issue by bwarden** [drowe67/freedv-gui#255]
The release 1.8.0 source code will not compile against the latest release of codec2 (1.0.3). That release does not yet include the implementation of FREEDV_MODE_2020B (https://github.com/drowe67/codec2/pull/274).

https://github.com/drowe67/freedv-gui/blob/a612cdc79a155e0bb4614f616f6b2fb54687b63e/src/freedv_interface.cpp#L45-L46
https://github.com/drowe67/freedv-gui/blob/a612cdc79a155e0bb4614f616f6b2fb54687b63e/src/main.cpp#L922

**Comment by tmiw** [comment]
As a workaround, use codec2 master. I'll see if we can get a new codec2 release out.

**Comment by tmiw** [comment]
See https://github.com/drowe67/codec2/releases/tag/v1.0.4 for version 1.0.4.

**Comment by tmiw** [comment]
Sorry, but it seems that v1.0.4 was premature. Continue to use codec2 master as a workaround. We're figuring out a way forward and will update with the solution.

**Comment by tmiw** [comment]
Try https://github.com/drowe67/freedv-gui/releases/tag/v1.8.1. Feel free to reopen if you continue to have build issues.
