### ISSUE TITLE
Upgrade Hamlib for Windows to 4.4

### ISSUE THREAD

**Issue by tmiw** [drowe67/freedv-gui#260]
Per [COPR](https://copr.fedorainfracloud.org/coprs/hobbes1069/mingw/packages/), the Docker container uses Hamlib version 3.3, which is significantly behind the macOS build (and what [Fedora 36](https://packages.fedoraproject.org/pkgs/hamlib/hamlib/) provides). As there have been changes in radio support since the packages have been generated, it would be good to update the COPR packages as well or possibly just build Hamlib from git like what the macOS build does.

(ping @hobbes1069)

**Comment by Tyrbiter** [comment]
It seems that we should have hamlib-4.5 out soon, might make sense to target it as it has a lot of bugfixes.

**Comment by tmiw** [comment]
> It seems that we should have hamlib-4.5 out soon, might make sense to target it as it has a lot of bugfixes.

After this commit is merged, we shouldn't have any problems supporting newer versions of hamlib as Windows builds will use git master's version of it.
