### ISSUE TITLE
Hamlib radio list update

### ISSUE THREAD

**Issue by py2edu** [drowe67/freedv-gui#263]
I tried to install FreeDV on a Yaesu FTDX 1200 and I was not successful. The hamlib version 4.4 (current) already has the radio listed. I request for improvements to update the list in the program. THX

**Comment by tmiw** [comment]
What version of FreeDV are you running and on what platform? If you're on Windows, https://github.com/drowe67/freedv-gui/pull/261 has some changes that will allow future releases to use newer versions of Hamlib.

In the meantime, have you tried selecting any other similar Yaesu radios in the list that does pop up? My understanding is that most use a similar protocol so basic functionality (frequency readout, PTT) should still work.

**Comment by Tyrbiter** [comment]
Hamlib 4.5 is due out right now, in fact it's a few days past due.

There have been a lot of code changes and bug fixes in the git versions, it is quite likely that the radio you are using will work better with the new code.

**Comment by tmiw** [comment]
Closing due to lack of feedback. Please feel free to reopen if desired.
