### ISSUE TITLE
Encryption Support?

### ISSUE THREAD

**Issue by ITCMD** [drowe67/freedv-gui#275]
Does FreeDV have or plan to add support for encryption over voice? Obviously, this would not be possible for amateur radio, but for private organizations and in situations in other countries, it would be very useful. There is currently no software I know of that allows encrypted HF communication.

Looks like this fork of codec2 might have some encryption in there, not sure. https://github.com/aarmono/codec2

**Comment by tmiw** [comment]
As freedv-gui is intended for amateur radio use, there aren't any plans on supporting encryption at this time. 

BTW, re: the linked Codec2 fork: it's actually a few years behind, so it wouldn't be ideal to use it with freedv-gui anyway (e.g. no 2020B/C support).
