### ISSUE TITLE
Transition away from GitHub

### ISSUE THREAD

**Issue by tmiw** [drowe67/freedv-gui#281]
Now that we're under the Software Freedom Conservancy (SFC), we'll need to figure out a plan for transitioning away from GitHub (context [here](https://sfconservancy.org/blog/2022/jun/30/give-up-github-launch/)). This issue is being created to track this task.

TODO:

* Research Git hosting providers (GitLab, SFC's own, etc.)
* Select Git hosting provider (w/vote by the Leadership Team)
* Clone current repo at new provider
* Re-enable/port CI tasks as appropriate
* Add link from GitHub to new location
* Make repository read-only mirror of new location
* Determine future date when to delete GitHub repository entirely

Related issues on other projects: codec2 (https://github.com/drowe67/codec2/issues/354), LPCNet (https://github.com/drowe67/LPCNet/issues/46), ezDV (https://github.com/tmiw/ezDV/issues/13)

**Comment by tmiw** [comment]
Tagging @drowe67 and @Tyrbiter for feedback/discussion.

**Comment by Tyrbiter** [comment]
My immediate thought is how to determine whether wherever the repository moves to will be safe in future, or is this a repeating task as circumstances change. I imagine that it's not sensible to limit ourselves to the 2 year horizon of the current application.

**Comment by tmiw** [comment]
> My immediate thought is how to determine whether wherever the repository moves to will be safe in future, or is this a repeating task as circumstances change. I imagine that it's not sensible to limit ourselves to the 2 year horizon of the current application.

We can't see into the future but I suspect we'd be safe for a while with any of the other well-known ones. We'll have to discuss more offline during the selection process.

**Comment by barjac** [comment]
I happened across this recently, but know nothing more:

https://codeberg.org/

**Comment by drowe67** [comment]
@tmiw is this issue dead and can this closed?

**Comment by tmiw** [comment]
> @tmiw is this issue dead and can this closed?

Theoretically we're still supposed to do this at some point. However, we haven't been pushed to (i.e. with imposed deadlines) and I'm not sure we will any time soon. I added a spot at the top of the meeting minutes document so we don't forget about it and will close for now.
