### ISSUE TITLE
Last version compilation failed

### ISSUE THREAD

**Issue by UgoPoddine** [drowe67/freedv-gui#309]
Hello Mooner,

How are you ? Thank-you for your work, really appreciated.
The today update with the last release of FreeDV on my Raspberry Pi3+ with up do date pi OS 32 bits failed.
See the last part of the log in the attachment.
Feel free to ask if you need further details.

Best regards
 @Ugo
![Screenshot_20221204-164325](https://user-images.githubusercontent.com/12426023/205501315-e1d898dc-a1b1-4e42-9f5b-ff7573a196d7.png)

**Comment by tmiw** [comment]
This is a known issue. See https://github.com/drowe67/LPCNet/issues/49 and https://github.com/drowe67/LPCNet/pull/50. 

As a workaround, you can update `LPCNET_BRANCH` in build_linux.sh to `ms-rpi-build` instead of `master`. Let me know if that doesn't work for you.

**Comment by UgoPoddine** [comment]
Hi Mooner,

The issue was almost known, but till last version (7 days ago) I have always compiled using the build_linux script on the PI without issues 
No problem at all, I will try the workaround tomorrow morning.

Thanks 
Best regards, 73 
Ugo

Il giorno 4 dic 2022, 19:37, alle ore 19:37, Mooneer Salem ***@***.***> ha scritto:

**Comment by UgoPoddine** [comment]
Hi Mooner,

the workaround you have proposed allows the compilation to proceed, but not to end correctly :
With this change to build_linux.sh :

[..]

# change this when working on combined codec2/freedv-gui changes
CODEC2_BRANCH=ms-rpi-build
LPCNET_BRANCH=ms-rpi-build

[..]

...this is the final effect :

[..]

Scanning dependencies of target test_vec
[ 79%] Building C object src/CMakeFiles/test_vec.dir/test_vec.c.o
/home/pi/FreeDV/freedv-gui/LPCNet/src/test_vec.c: In function ‘test_sgemv_accum16’:
/home/pi/FreeDV/freedv-gui/LPCNet/src/test_vec.c:75:5: warning: implicit declaration of function ‘sgemv_accum16_fast’; did you mean ‘sgemv_accum16’? [-Wimplicit-function-declaration]
   75 |     sgemv_accum16_fast(out_fast, weights, ROWS, COLS, 1, x);
      |     ^~~~~~~~~~~~~~~~~~
      |     sgemv_accum16
/home/pi/FreeDV/freedv-gui/LPCNet/src/test_vec.c: In function ‘test_sparse_sgemv_accum16’:
/home/pi/FreeDV/freedv-gui/LPCNet/src/test_vec.c:109:5: warning: implicit declaration of function ‘sparse_sgemv_accum16_fast’; did you mean ‘sparse_sgemv_accum16’? [-Wimplicit-function-declaration]
  109 |     sparse_sgemv_accum16_fast(out_fast, w, rows, indx, x);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
      |     sparse_sgemv_accum16
[ 80%] Linking C executable test_vec
/usr/bin/ld: CMakeFiles/test_vec.dir/test_vec.c.o: in function `test_sgemv_accum16':
/home/pi/FreeDV/freedv-gui/LPCNet/src/test_vec.c:75: undefined reference to `sgemv_accum16_fast'
/usr/bin/ld: CMakeFiles/test_vec.dir/test_vec.c.o: in function `test_sparse_sgemv_accum16':
/home/pi/FreeDV/freedv-gui/LPCNet/src/test_vec.c:109: undefined reference to `sparse_sgemv_accum16_fast'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/test_vec.dir/build.make:103: src/test_vec] Error 1
make[1]: *** [CMakeFiles/Makefile2:1286: src/CMakeFiles/test_vec.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
[..]

Please advise.
Thank-you
Ugo

**Comment by tmiw** [comment]
A few things:

1. `CODEC2_BRANCH` should still be `master`. Only `LPCNET_BRANCH` should change.
2. You may need to `rm -rf codec2 LPCNet build_linux` before re-attempting the build to clear out anything CMake still has cached.

If you still have issues after (1) and (2) above then I can see about getting 32 bit Raspberry Pi OS running on my 4B for further debugging.

**Comment by tmiw** [comment]
BTW I was able to get a build environment installed on an older Pi and resolve the issue you're having, so definitely try again. 👍

**Comment by UgoPoddine** [comment]
Hi Mooner,

using :

[...]

# change this when working on combined codec2/freedv-gui changes
CODEC2_BRANCH=master
LPCNET_BRANCH=ms-rpi-build

[..]

I was also able to compile the new version.
I will try it this evening.

Thank-you
Ugo
