### ISSUE TITLE
Other issue in building the last version

### ISSUE THREAD

**Issue by UgoPoddine** [drowe67/freedv-gui#310]
Hello Mooner, 

sorry about another bad news :-))
After having solved with your workaround on the RaspberryPI, I have tried to install as usual (with the build_linux.sh script) the new version on my other "real" PC (AMD64 with Debian 5.10.0-13-rt-amd64 #1 SMP PREEMPT_RT Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux).
The last version ran correctly.
Unfortunately the new installation failed before starting compiling.

Can you help (with your magic workaround basket) ?
thank-you as usual, 73

Ugo

/build_linux.sh
+ UT_ENABLE=0
+ FREEDV_VARIANT=portaudio
+ [[ portaudio != \p\o\r\t\a\u\d\i\o ]]
+ export FREEDVGUIDIR=/home/ugo/FreeDV/freedv-gui
+ FREEDVGUIDIR=/home/ugo/FreeDV/freedv-gui
+ export CODEC2DIR=/home/ugo/FreeDV/freedv-gui/codec2
+ CODEC2DIR=/home/ugo/FreeDV/freedv-gui/codec2
+ export LPCNETDIR=/home/ugo/FreeDV/freedv-gui/LPCNet
+ LPCNETDIR=/home/ugo/FreeDV/freedv-gui/LPCNet
+ CODEC2_BRANCH=master
+ LPCNET_BRANCH=master
+ cd /home/ugo/FreeDV/freedv-gui
+ '[' '!' -d LPCNet ']'
+ git clone https://github.com/drowe67/LPCNet.git
Cloning into 'LPCNet'...
remote: Enumerating objects: 2474, done.
remote: Counting objects: 100% (296/296), done.
remote: Compressing objects: 100% (140/140), done.
remote: Total 2474 (delta 157), reused 260 (delta 134), pack-reused 2178
Receiving objects: 100% (2474/2474), 57.58 MiB | 942.00 KiB/s, done.
Resolving deltas: 100% (1668/1668), done.
+ cd /home/ugo/FreeDV/freedv-gui/LPCNet
+ git switch master
Already on 'master'
Your branch is up to date with 'origin/master'.
+ git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
+ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
+ mkdir -p build_linux
+ cd build_linux
+ rm -Rf '*'
+ cmake ..
-- The C compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- LPCNet version: 0.4
-- freedv-gui current git hash: 59f75b6
-- Host system arch is: x86_64
-- Looking for available CPU optimizations on Linux/BSD system...
CMake Error at src/CMakeLists.txt:38 (set_source_files_properties):
  set_source_files_properties called with incorrect number of arguments.

CMake Error at src/CMakeLists.txt:38 (set_source_files_properties):
  set_source_files_properties called with incorrect number of arguments.

CMake Error at src/CMakeLists.txt:38 (set_source_files_properties):
  set_source_files_properties called with incorrect number of arguments.

CMake Error at src/CMakeLists.txt:38 (set_source_files_properties):
  set_source_files_properties called with incorrect number of arguments.

CMake Error at src/CMakeLists.txt:38 (set_source_files_properties):
  set_source_files_properties called with incorrect number of arguments.

CMake Error at src/CMakeLists.txt:38 (set_source_files_properties):
  set_source_files_properties called with incorrect number of arguments.

CMake Error at src/CMakeLists.txt:38 (set_source_files_properties):
  set_source_files_properties called with incorrect number of arguments.

CMake Error at src/CMakeLists.txt:38 (set_source_files_properties):
  set_source_files_properties called with incorrect number of arguments.

CMake Error at src/CMakeLists.txt:38 (set_source_files_properties):
  set_source_files_properties called with incorrect number of arguments.

CMake Error at src/CMakeLists.txt:38 (set_source_files_properties):
  set_source_files_properties called with incorrect number of arguments.

CMake Error at src/CMakeLists.txt:38 (set_source_files_properties):
  set_source_files_properties called with incorrect number of arguments.

CMake Error at src/CMakeLists.txt:38 (set_source_files_properties):
  set_source_files_properties called with incorrect number of arguments.

CMake Error at src/CMakeLists.txt:38 (set_source_files_properties):
  set_source_files_properties called with incorrect number of arguments.

CMake Error at src/CMakeLists.txt:38 (set_source_files_properties):
  set_source_files_properties called with incorrect number of arguments.

CMake Error at src/CMakeLists.txt:38 (set_source_files_properties):
  set_source_files_properties called with incorrect number of arguments.

-- Compilation date = XX20221207XX
-- Configuring incomplete, errors occurred!
See also "/home/ugo/FreeDV/freedv-gui/LPCNet/build_linux/CMakeFiles/CMakeOutput.log".

**Comment by tmiw** [comment]
What CPU are you using, exactly? I'm not sure there are that many these days that don't at least support AVX.

Anyway, I'd try that same branch (`ms-rpi-build` for LPCNet) as with the previous issue as that will probably fix that particular error, or at least work around it anyway.

**Comment by UgoPoddine** [comment]
Hello Mooner, 

it's not a baby, but neither a Commodore64

I will adopt the workaround, in the meantime.
Thank-you as usual
Ugo


Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           23
Model name:                      Celeron(R) Dual-Core CPU       T3000  @ 1.80GHz
Stepping:                        10
CPU MHz:                         1795.450
BogoMIPS:                        3590.87
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        1 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no mic
                                 rocode; SMT disabled
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Unknown: No mitigations
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user
                                  pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB fil
                                 ling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtr
                                 r pge mca cmov pat pse36 clflush dts acpi mmx f
                                 xsr sse sse2 ht tm pbe syscall nx lm constant_t
                                 sc arch_perfmon pebs bts rep_good nopl cpuid ap
                                 erfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx
                                 16 xtpr pdcm xsave lahf_lm pti dtherm

**Comment by tmiw** [comment]
How did this go? Still having issues compiling?

**Comment by UgoPoddine** [comment]
Hi Mooner,

I have compiled using the "rpi" workaround also on the amd64 pc, as you have proposed.
I don't know if you are planning to do something more....

Thanks 
Ugo

Il giorno 16 dic 2022, 09:30, alle ore 09:30, Mooneer Salem ***@***.***> ha scritto:

**Comment by tmiw** [comment]
Nope, the fix for this particular issue is in master now so we're good.
