### ISSUE TITLE
increase recording duration of "Start Record File - from Modulator..."

### ISSUE THREAD

**Issue by cybork42** [drowe67/freedv-gui#320]
In the beginning, when I started to play with FreeDV on a MS Windows computer, I used a virtual audio cable (VB-Audio Cable) to connect FreeDV with **Audacity** and to grab outputs from FreeDV and perform playbacks of own recordings, recordings made from remote stations (kiwi SDR or similar) or distorted versions of locally recorded files. 
Audacity is quite versatile also on distorting file recordings, starting with sadding noise only, or applying filters, equalizer functions, frequency (pitch) shifts and so on. a lot of things to learn from messing around with audio functions here...!

Using a virtual audio cable is a small mess until you get used to it, on Linux with different device driver models it's a different story, but it's not a simple matter, too.

As all this is messy and requires a learning curve, similar functions exist in FreeDV, but it's not easy getting used to them at the same time. The naming is not quite straight forward (I have no suggestion how to improve them though!).

![2022-12-18 10_59_29-](https://user-images.githubusercontent.com/66186274/208292288-e729cede-28de-4443-8cf9-e5ab3d0c9082.png)

But what I still find quite limiting is the recording length limit for "recording from modulator" which seems to be 10secs with no special need for such a short duration? Whenever you try to optimize settings or listen to artefacts, or evaluate differences, 10secs is very short, isn't it?

At the same time, forgetting to stop a recording may completely jam a storage device. A reminder after 5 minutes of recording "Hello, operator! You're recording still.. sure you want to continue?" might be a safeguard if recording time is set to unlimited, while probably over-complicating things. From my perspective an increased **120 seconds record limit** would do as well.

What do you think?

**Comment by tmiw** [comment]
The recording time is user adjustable:

![Screenshot 2022-12-18 at 11 32 14 PM](https://user-images.githubusercontent.com/449242/208371406-3521ff48-cba4-4289-9e55-fc8450f9f690.png)

(On Windows you may need to push the "Options" button once you're in the dialog to see the setting.)

That said, it does default to 10 seconds and I'm not sure why. It shouldn't hurt to make that 60 seconds like the Record From Radio dialog, so I went ahead and created PR #321 to do such.

**Comment by tmiw** [comment]
Closing for now as the PR has been merged.
