### ISSUE TITLE
QO-100 frequency in FreeDV GUI

### ISSUE THREAD

**Issue by sp2ong** [drowe67/freedv-gui#324]
When I try put frequency QO-100 manually in kHz 10489640.0 in filed "Report Frequency" ( in Options I have enabled "PSK Reproter ") 
the frequency is displayed in red colour.
It looks like I can put in "Report Frequency" a bigger frequency than 2147483.647 kHz.

In config .freedv is stored FrequencyHz in Hz so for frequency for QO-100 should be in Hz value 10489640000

The value of this is type INT which has a limit in C++ to -2147483648 to 2147483647 so QRG QO-100 is not in this range, for this reason, is not correctly stored in the config file and not correctly reread

For QO-100 frequency in Hz would be instead INT rather type:

long long : -9223372036854775808 to 9223372036854775807
or
unsigned long long : 0 to 18446744073709551615

it will allow stored in .freedv QRG QO-100 in Hz and allow use of any frequency in PSKRepoert up to 10 Ghz band

but I'm not a programmer, it is only my analysis problem use "Report Frequency" bigger than 2.1 Ghz

I use the version compiled under Linux:

https://github.com/drowe67/freedv-gui/releases/tag/v1.8.6-20221217

![freedv-ver](https://user-images.githubusercontent.com/822846/208832400-c4352859-4e9f-4f69-bf71-576277998cec.png)

![qo-100-qrg](https://user-images.githubusercontent.com/822846/208832462-e9acce33-b6c6-4861-ad54-4c48586cf0ed.png)

**Comment by sp2ong** [comment]
Thank you.

I have tried the new branch ms-freq-precision and I put QRG for QO-100 10489640.0 is displayed 
now correctly but when I exit from GUI and start again the frequency is displayed with a small difference 10489639.9 
I think it is not a critical problem :-)

In the file .freedv is  FrequencyHzStr=10489639900

![screenshot1](https://user-images.githubusercontent.com/822846/208874810-622de6ab-ed79-42c9-9347-c91430e4c13a.png)
![screenshot2](https://user-images.githubusercontent.com/822846/208874846-1a357e98-37e6-4c0c-b5f5-cbd7c8ae233b.png)

**Comment by tmiw** [comment]
Try pulling down the latest from that branch and trying again? I just checked in a minor change that seems to resolve that on my end, anyway.

**Comment by sp2ong** [comment]
Ok,

I updated sources and during compilation, I see one warning only:

freedv/freedv-gui/src/main.cpp: In member function ‘void MainFrame::OnTimer(wxTimerEvent&)’:
/freedv/freedv-gui/src/main.cpp:1299:45: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 1299 |                     if (m_timeSinceSyncLoss >= wxGetApp().m_statsResetTimeSec)
      |                         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


The new sources work OK now, I put manually 10489640.0 kHz frequency and after exiting and run again GUI frequency
is displayed without a problem

Thanks

![screenshot3](https://user-images.githubusercontent.com/822846/208891476-3754c832-9fef-43bc-b193-b2be6f9cbc44.png)

**Comment by sp2ong** [comment]
I try to check this version to send report to PSKReporter 
I create file with freedv 700D mode and text add callsign and play this file in FreeDV GUI use Tools -> Start Play file form radio. 
When I put manually frequency like 7177.0 kHz in "Report frequency" in console I see that was sent to PSKReporter report like:

Adding call sign SP2RXY @ SNR 24, freq 7177000 to PSK Reporter.

and on PSKReporter map display information correctly that I received traffic on FreeDV 
from SP2RXY on frequency 7.177 Mhz

I changed frequency to 10489640.0 kHz i play again y test file and in console I see

Adding callsign SP2RXY @ SNR 24, freq 10489640000 to PSK Reporter.

but on PSKReporter map I see

![screenshot](https://user-images.githubusercontent.com/822846/208948629-7f54bb5f-43b7-4602-ad1c-ab20067b65ea.png)

It is loo like is problem with report sending to PSKReport with QRG 10489.640 Mhz where display
frequency 0.000 Mhz (invalid)

When use frequency 2147483.0 kHz  the report PSKreporter is correct

![screenshot1](https://user-images.githubusercontent.com/822846/208950682-571648be-119d-4e3f-8fc6-427178e40bae.png)

**Comment by sp2ong** [comment]
I see on PSKReproter reprts on 10 Ghz for example Mode FT8 from QO-100

![screenshot2](https://user-images.githubusercontent.com/822846/208954095-f3cecbef-dc25-4f5b-a6ed-94939f01a9cf.png)
-100:

**Comment by tmiw** [comment]
I checked out how MSHV was doing it and it seems that they send a 5 byte location field instead of 4 (like what WSJT-X, FreeDV, etc. do) I updated the PR branch to also use 5 bytes and it seems to work okay here; please confirm.

**Comment by sp2ong** [comment]
Hi,

I will check the new version.

During compile the latest version branch ms-freq-precision show two warring:

/Projects/freedv/freedv-gui/src/main.cpp: In member function ‘void MainFrame::OnTimer(wxTimerEvent&)’:
/Projects/freedv/freedv-gui/src/main.cpp:1299:45: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 1299 |                     if (m_timeSinceSyncLoss >= wxGetApp().m_statsResetTimeSec)
      |                         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/Projects/freedv/freedv-gui/src/main.cpp:1411:63: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 5 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
 1411 |                         "Adding callsign %s @ SNR %d, freq %lld to PSK Reporter.\n",
      |                                                            ~~~^
      |                                                               |
      |                                                               long long int
      |                                                            %ld
......
 1414 |                         freq);
      |                         ~~~~                                   
      |                         |
      |                         int64_t {aka long int}

**Comment by tmiw** [comment]
> During compilation the latest version branch ms-freq-precision show two warrings:

Should be fixed as of the latest commit.

**Comment by sp2ong** [comment]
Hi,

I have updated,  and now compiled it clearly :-) without warning.

But in the latest version I have a problem with the console shows that 

Adding callsign SP2RXY @ SNR 24, freq 7177000 to PSK Reporter.
Adding callsign SP2RXY @ SNR 24, freq  10489640000 to PSK Reporter.

but I don't see a report on PSKReport map any report on band 40 m and 10 GHz

I check band 40m on 1.8.6-dev and the report is displayed on map but from the latest version branch ms-freq-precision
 no report is shown for example for 7177.0 kHz and for 10489640.0 kHz
In the previous version, it showed for 7177.0 kHz but wrongly showed for 10489640.0 kHz

**Comment by tmiw** [comment]
I just tried playing a test file back in the FreeDV application using the PR branch. It looks like it properly reported when Hamlib was enabled and the radio was on 20 meters and also when I manually entered a 10 GHz frequency. However, I did notice that the PSK Reporter website has been pretty glitchy tonight so it's possible that the server didn't pick up your report. I'd `git pull` the latest from that branch and try again over the course of the next day or two to make sure.

**Comment by sp2ong** [comment]
OK,

I will do the tests again in the evening and tomorrow to confirm that it works OK

73 
Waldek

**Comment by sp2ong** [comment]
I have tried many times.
When I use the GUI of the latest version 1.8.6-devel
and I manually set the frequencies from 3.6 to 28 Mhz each report is shown on PSKReporter

When I use the latest version of ms-freq-precision and manually set the frequencies between 3.6 and 28 Mhz no report is shown on PSKReporter even though in the console it shows that it sent this report

The version of ms-freq-precision that I use is:
 
![screenshot](https://user-images.githubusercontent.com/822846/209187111-b3a7b3c8-a19e-4d53-85df-0f104b36fa7e.png)

**Comment by sp2ong** [comment]
I monitor port UDP 4739 which is used to send report to PSKRreporter host under Linux

tcpdump -nXX -i eth0 dst port 4739

I set frequency  manually  21313.0 kHz 

and when use FreeDV GUI 1.8.6-devl I see traffic in following

![screenshot](https://user-images.githubusercontent.com/822846/209202530-7324ff9d-bb5f-438a-b8e4-ba1add4c9d4c.png)

but when I use FreeDV GUI branch ms-freq-precises and I set frequency  manually  21313.0 kHz 

UDP frame looks like below

![screenshot](https://user-images.githubusercontent.com/822846/209203535-8c241f38-b4d8-40c8-88ef-673253f12581.png)

but is not decoded by PSKReporter ??

**Comment by tmiw** [comment]
Looks like I forgot to add 1 to another location in the PSKReporter class to account for the extra byte sent for the frequency. I might not have encountered the issue before due to (a) my callsign being shorter and (b) the code including padding on 32 bit alignment. Pull down the latest and try again?

**Comment by sp2ong** [comment]
It seems that the latest patch has solved the problem with decoding reports on PSKReporter. I tried different HF/VHF/UHF/Microwave frequencies entering manually and every report was shown correctly on the map.

It would be nice for PR ms-freq-precisions to be in version 1.8.6-devel 
because maybe during the coming of Christmas week there will be some activity on QO-100 this could be checked on transmitting stations and not on test files :-)

Thanks and best regards

Waldek SP2ONG
