### ISSUE TITLE
Options - Debugging and VoiceKeyer tabs can be truncated as window is resized

### ISSUE THREAD

**Issue by Tyrbiter** [drowe67/freedv-gui#327]
This is a similar problem to https://github.com/drowe67/freedv-gui/issues/322 where the window is allowed to reduce width to the point where the right hand ends are truncated.

A little truncated:
![options-debugging](https://user-images.githubusercontent.com/36776842/208923121-e6633062-5958-47c1-9540-1eb67a6b9054.png)

This is the worst example:
![options-voicekeyer](https://user-images.githubusercontent.com/36776842/208923138-8a7be40c-51e5-4dc1-9db0-2054f612cc89.png)

**Comment by Tyrbiter** [comment]
Also note something odd about the Debugging txrxThreadPriority checkbox, it always appears enabled at restart and doesn't seem to prevent the debug output it controls.

**Comment by tmiw** [comment]
Created PR #328 for the truncation issue. Please confirm that it resolves the problem on your end.

> Also note something odd about the Debugging txrxThreadPriority checkbox, it always appears enabled at restart and doesn't seem to prevent the debug output it controls.

This doesn't actually control debugging output, just whether the TX/RX processing threads run at the highest priority. The state of this setting doesn't get saved anywhere, though, so I wonder if we actually need this to be configurable.

**Comment by Tyrbiter** [comment]
OK, after a pause for seasonal shopping I have now built and tried this out and it's behaving well for me, so the original issue is fixed.

Top work @tmiw, you clearly comprehend this wxWindows stuff well.

The thread priority control is not critical, especially as it wasn't clear what it did and seems happy to be left enabled.

**Comment by tmiw** [comment]
Thanks, the changes have now been merged. 👍
