### ISSUE TITLE
Click to tune resolution

### ISSUE THREAD

**Issue by drowe67** [drowe67/freedv-gui#33]
From Steve:

> One thing I noticed is the Mouse frequency centering is very course.
>  You can't finesse it to ± values around the center.
> Maybe needs a zoom feature added for OFDM.

I'd suggest just scaling, e.g. if the centre is 1500 Hz, clicking on -1400Hz will shift -10Hz rather than -100.

**Comment by tmiw** [comment]
Would a text box with the exact frequency work too? This would be similar to what WSJT-X does where clicking in the waterfall is effectively a "coarse" adjustment (while entering a frequency or pushing the up/down buttons next to it is the "fine" one).

**Comment by tmiw** [comment]
I haven't heard of any recent requests for this so I'm inclined to close this issue. @drowe67 et al, does that sound reasonable?

**Comment by drowe67** [comment]
Sure, if no one is complaining, no point keeping it open :+1:
