### ISSUE TITLE
Sample rate dropdowns in audio dialog are all one digit too narrow

### ISSUE THREAD

**Issue by Tyrbiter** [drowe67/freedv-gui#335]
Noticed this a while ago, forgot to report it.

![narrow_audio_dlg](https://user-images.githubusercontent.com/36776842/210177518-ebcc564d-9993-4cef-b337-b0fc0b428b52.png)

**Comment by tmiw** [comment]
#336 should resolve this. Let me know if I need to add additional space. 👍

**Comment by Tyrbiter** [comment]
Looks good to me now, think the max sample rate is 5 digits now.
