### ISSUE TITLE
SNR vertical gauge has no units shown

### ISSUE THREAD

**Issue by Tyrbiter** [drowe67/freedv-gui#337]
Since the squelch setting is labeled in dB, the SNR gauge should also have this label.

**Comment by Tyrbiter** [comment]
My fix for this, which seems to work OK is:

main.cpp:1243

change "%4.1f"  to "%4.1f dB"

and also

topFrame.cpp:153

change " 0.0" to " 0.0 dB"

and

topFrame.cpp:154

change wxSize(40, to wxSize(70,

Yes, I should have generated a patch file but I thought it was simpler to do this instead of get my diff syntax wrong :)

**Comment by tmiw** [comment]
Try https://github.com/drowe67/freedv-gui/pull/339 and let me know how that goes?

**Comment by Tyrbiter** [comment]
Looks good, sorry I got the line numbers wrong, based off file in the wrong branch.
