### ISSUE TITLE
Mode box in GUI changes columns each time Others is expanded/contracted

### ISSUE THREAD

**Issue by Tyrbiter** [drowe67/freedv-gui#346]
A minor niggle, but this also causes the Start and PTT buttons to jump about which would be nice to avoid.

After starting the program, the Mode box is in the left column to the right of the graph area.

Expand the Others modes and the Mode box jumps to the top of the right column, because it would otherwise extend below the Main window lower edge.

Now click the arrow button to contract the Modes list, still at the top right, but with only the 3 modes shown. On a 3rd click the Modes box moves back to the left column but is now expanded with the last 2 or 3 entries of the Others modes missing, the list is truncated by the main window edge. Also the Control box is too narrow now, Report Frequency is truncated at both left and right edges.

Naturally this depends on how the windows are sized when starting.
![freedv_Mode](https://user-images.githubusercontent.com/36776842/219964624-e2cc61a7-9c62-492e-9ff9-65af1dfc1b75.png)

**Comment by tmiw** [comment]
What if the Mode box is forced to be the largest possible size, even if the modes under "Others" are hidden? That seems like the best way to fix this IMO, but I'm open to other suggestions.

**Comment by Tyrbiter** [comment]
That seems a good idea to me, the thing I like least is the Control box moving around as it contains the buttons that get used most frequently. This would ensure that doesn't happen.

**Comment by tmiw** [comment]
I created PR #347 based on the feedback in this issue. Let me know how that works for you. 👍
