### ISSUE TITLE
FreeDV Transceiver Frequency Issue

### ISSUE THREAD

**Issue by Slinger128** [drowe67/freedv-gui#349]
[FreeDV Issue.docx](https://github.com/drowe67/freedv-gui/files/10932373/FreeDV.Issue.docx)

**Comment by tmiw** [comment]
Can you try having both VFOs set to the same frequency and see if you still have that issue? Might help narrow things down a bit.

**Comment by tmiw** [comment]
Also, here's the contents of the Word document here for ease of reading/searching later:

# FreeDV Transceiver Frequency issue.

Hi there, hope you can help with this issue.

## History

I am Brian Woods M0SSN. I was introduced to FreeDV by Mike G4ABP who is a long time old school mate and family friend. 
I have joined FreeDV nets using an Icom IC7100 and a laptop with a gaming headset and microphone. I was impressed with the results and have given demonstrations of FreeDV at the Local Radio Club. I use the IC7100 as the USB link to the laptop transfers audio as well as CAT and PPT signals, which is great for digital modes.

During one of the nets we decided to tryout 2020B, at the time I was using software version 1.5.2. After updating to version 1.8.7 I realised that the Laptop I was using was not up to the specification for running 1.8.7 in the 2020 and 2020B modes. I therefore changed to a higher specification laptop that I had. 

## The Issue.

On joining the net using 700E all was looking good until I monitored my signal my signal via the Western and Hack Green Web SDRs. I noticed that there were regular breaks in my transmission, although those on the net did not audibly hear any breaks. When mentioned they also observed the breaks on the Web SDRs. Looking at the frequency display of my Icom IC7100 I noticed it flickering from 5.3665MHz to 7.740MHz. I tuned one of my other transceivers to 7.074MHz and when I transmitted and observed that when the display flickered there was a transmission on 7.074 albeit no more than 0.25 of a second long. I also observed that the frequency display also occurred whilst in receive.

I had kept the version 1.5.2 and reverted to it the flickering of the frequency display and breaks in transmission disappeared. After some investigation I concluded that version 1.8.0 and earlier did not have this issue but 1.8.3.1 and higher did have this issue. Therefore at present I am using 1.8.0 and I am happy with the operation of FreeDV so far.

## Equipment.

The equipment I am using is as follows

* *Laptop*: LENVO Ideapad 310, which is an AMD A10 9600P RadeonR5, 10 compute cores 4C +6G 2.40GHz Ram 8GB, 64-bit X64 based processor.
* *Radio*: Icom IC7100
* *Radio firmware version*:	
    `CPU	M 1.11		DSP	I 1.03
			S 1.00			D 1.00
			C 1.10`
* *FreeDV Software tested*:
    * 1.5.2/1.8.0: Worked
    * 1.8.3.1/1.8.6/1.8.7: Has Issue

Kind regards Brian Woods M0SSN

**Comment by tmiw** [comment]
@Slinger128, additionally, can you make sure FreeDV is the only thing using the radio and try again? Considering that the other VFO was set to 7.074 MHz, I wonder if it was some sort of interaction with e.g. WSJT-X.

**Comment by Slinger128** [comment]
Dear Mooner Salem

Thank you for your prompt response to my enquiry. I followed up your
suggestions and made these observations.

Yes VFO A was set to 7.074MHz and VFO B set to 5.3665 using 1.8.7 after
setting VFO A to 5.3665 the frequency did not flicker.
Normally on 60m due to the channelisation I use the transceivers memory to
call up the correct frequency.
Using the memory and activating 1.8.7 in receive only I observed that the
indication on the transceiver was that the Memory, VFO A and VFO B changed
from MEM to VFO B and then after approximately 5.5 seconds flickered from
VFO B to VFO A  and back to VFO B. I repeated this using 1.8.0 and the
indication stayed static on the MEM .
I hope this helps, if you require any other tests please let me know.
Yours kindly
Brian M0SSN

**Comment by Slinger128** [comment]
I can also confirm no other software was running at the time of testing

**Comment by tmiw** [comment]
Unfortunately I don't have a IC-7100 here so I can't be sure if this change will work. Can you give it a try? The installer containing this change is over at https://www.dropbox.com/s/3lfaxfxye2vbsj5/FreeDV-1.8.7-windows-x86_64.exe?dl=0. (If successfully installed, the version should be "FreeDV 1.8.7 test".)

**Comment by Slinger128** [comment]
Thanks away from home for a couple of days will try and let you know the
results
Regards Brian M0SSN

**Comment by Slinger128** [comment]
Have tried the 1.8.7 test unfortunately the indications are the same. I
have made no changes to my setup and 1.8.0 still works with no flickerings.

**Comment by tmiw** [comment]
> Have tried the 1.8.7 test unfortunately the indications are the same. I have made no changes to my setup and 1.8.0 still works with no flickerings.

Thanks, I'll keep investigating and get back to you.

**Comment by tmiw** [comment]
I was able to have someone try on their IC-7100. Unfortunately they were unable to duplicate the issue you're having. Is it possible to do a factory reset of your radio to rule out any bad configuration or bugs on the radio side?
