### ISSUE TITLE
Crashing when USB devices removed

### ISSUE THREAD

**Issue by drowe67** [drowe67/freedv-gui#35]
Configure FreeDV with a radio and headset (two card configuration):
1. With all USB devices connected click on Start and FreeDV runs OK
1. Press Stop and remove one USB device
1. Click on Start and all sorts or error messages pop up and it crashes.

I've taken an initial look at the startRxStream.  This is complex code and could use some refactoring.  Backing out of any failed function calls is tricky, so many structures to delete/pull down.. To deal specifically with this bug, suggest a sanity check at the top to check the available PortAudio devices and confirm they are as expected, and bail early before everything is allocated. 

This is a fairly important issue, as we would like to avoid any circumstances where FreeDV can crash.  Messing with USB devices is common, so it would be good to trap this.

**Comment by drowe67** [comment]
@tmiw I can't seem to reproduce this issue on Ubuntu any more (756534e).  Can you please try to reproduce it?

I wonder if some of your recent fixes have fixed it?

**Comment by tmiw** [comment]
@drowe67, in VMware at least, following the test steps on Ubuntu 20.04 LTS results in "Sound Card 1 Open/Setup Error" and no other messages/crashes, so this issue is likely fixed. (It's definitely fixed in #82, or at least the error messages are improved anyway.)

Also, I don't remember seeing crashes on Mac surrounding sound devices going away in a while, FWIW.

**Comment by drowe67** [comment]
Thanks @tmiw - could you pls try it on your Windows VM? (I don't have a Windows machine or VM handy).  I might also ask the list just to double check.

**Comment by tmiw** [comment]
@drowe67, is the Docker script working for you? It looks like I'm getting "bad tar archive" errors now while building LPCnet:

```
ESC[36mfdv_win_fed31_c     |ESC[0m CMake Error: Problem with archive_read_next_header(): Damaged tar archive
ESC[36mfdv_win_fed31_c     |ESC[0m CMake Error: Problem extracting tar: /home/build/freedv-gui/LPCNet/build_win64/_deps/lpcnet-subbuild/lpcnet-populate-prefix/src/lpcnet_191005_v1.0.tgz
```

**Comment by drowe67** [comment]
Docker build worked fine for me.  Maybe try:
```
tar xvf lpcnet_191005_v1.0.tgz
```

**Comment by tmiw** [comment]
@drowe67, I edited my last post, actually. Even downloading the file by hand outside of Docker seemed to have issues. 

Weirdly, it seemed to decompress with no issue on macOS, so I'm not sure what's going on.

**Comment by tmiw** [comment]
@drowe67, okay, I came back to it after a few hours and the Docker build magically started working again. o_O 

Anyway, on Windows, I don't get any errors. It just seems to automatically choose the default sound device (Microsoft Sound Mapper?) instead. (I selected the USB sound card as the "radio" device and the built-in sound card as the "speaker/headset" one and unplugged the USB one after pushing Stop.) The audio-ux branch should hopefully make the behavior more consistent across platforms, I think.

**Comment by tmiw** [comment]
That all said, it looks like I do get a "sound card open/setup error" after closing and restarting FreeDV, so the behavior is at least consistent after then. Fortunately, no crashes either way.

**Comment by drowe67** [comment]
Thanks @tmiw that's great.  Lets see if anyone responds on the digital voice list in the next day or so, otherwise I will close this issue.  

Yes I'm looking fwd to merging and releasing https://github.com/drowe67/freedv-gui/pull/82 :slightly_smiling_face:

**Comment by tmiw** [comment]
@drowe67, BTW, I put the Windows build I used up [here](https://www.dropbox.com/s/rmffxvdtredepod/FreeDV-1.5.1-devel-20210108-9026d86-win64.exe?dl=0). I'll email it out to Sigfried since the squelch fix seems to have gotten merged to master prior to me generating it tonight.

**Comment by drowe67** [comment]
No reports of this issue from the digital voice mailing list, and the developers can't reproduce, so closing this one.
