### ISSUE TITLE
"Hash collision" after compiling manually

### ISSUE THREAD

**Issue by phl0** [drowe67/freedv-gui#351]
My local build of freedv-gui refuses to start and exits with error message:

```
$ build_linux/src/freedv 
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
Making sure your machine can handle 2020 mode:
Generating test audio...
Decoding modulated audio...
One second of 2020 decoded in 95 ms
2020 allowed: 1
Hash collision!!! Fatal error!!
```

Anyone seen this before or does know the root cause here?

**Comment by tmiw** [comment]
This seems to be something Hamlib is throwing:

```
./hamlib-code/src/register.c:        printf("Hash collision!!! Fatal error!!\n");
```

What version of Hamlib are you running on your machine?

**Comment by phl0** [comment]
Thats a good hint (I could/should have found myself). Thank you.
Currently running version 4.1 from git. Will check the details here.

**Comment by tmiw** [comment]
Another thing you can try is to edit the `rig_set_debug()` call inside `src/hamlib.cpp` (line 54) to enable additional Hamlib debug output (maybe `RIG_DEBUG_TRACE` for maximum output). The Hamlib folks would probably need that anyway for their own debugging.

BTW did you build FreeDV with the `build_linux.sh` script? That should just use whatever package your distro provides for Hamlib.

**Comment by phl0** [comment]
Fixed by re-building hamlib. Thank you for the hint @tmiw.
