### ISSUE TITLE
FreeDV Reporter - should not show receiving or transmitting freedv when analog is selected

### ISSUE THREAD

**Issue by Tyrbiter** [drowe67/freedv-gui#403]
I use freedv-gui when operating in analogue modes, it's a useful interface with my USB microphone, I don't use the front panel mic connectors on my radios.

It seems to me that the FreeDV Reporter logic should recognise this and take my callsign out of the list if I am not in digital mode.

**Comment by tmiw** [comment]
See PR #404. 👍

**Comment by Tyrbiter** [comment]
Looking good to me @tmiw, I hope it works as well for everyone else too.
