### ISSUE TITLE
FreeDV-Reporter limits frequency display to 3 decimals

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#406]
This becomes a problem on 60m in the UK where we use 5366.5kHz and 5403.5kHz.
In FreeDv reporter these round up to 5.367 MHz and 5.404MHz.
Could FreeDV Reporter be modified to accept 4 decimal places without rounding?

Also FreeDV displays the reported frequency in kHz but Reporter converts this to MHz.
Would it not be better to be consistent between the two?

May I congratulate Mooneer and everyone involved with FreeDV for the recent updates and innovations :)

**Comment by tmiw** [comment]
FreeDV Reporter has already been updated to go out to another decimal place, though you may need to clear your cache or use Shift-F5 (or equivalent) for the change to take effect.

Re: consistency -- maybe. I'm not sure if people prefer MHz or KHz, though.

**Comment by tmiw** [comment]
https://github.com/drowe67/freedv-gui/pull/405 has been updated to show frequencies in MHz similar to FreeDV Reporter.

**Comment by barjac** [comment]
IMHO:
freq < 1kHz should be shown in Hz
freq < 1MHz should be shown in kHz
freq < 1GHz should be shown in MHz
freq < 1THz should be shown in GHz

However I appreciate that it would involve more coding complexity and your above fix is probably adequate :)
