### ISSUE TITLE
1.8.10 release breaks FDV reporting.

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#407]
I built freedv-1.8.10-devel yesterday (31/05/2023) from git master at 0c096ed and all was fine.

Today I saw that 1.8.10 final was released and was all set to push this new release to Mageia (just in time for Mageia 9) after using and testing git master myself for a few weeks but my plan has been thwarted.

I see that rig frequency control has been added which is a massive untested change to introduce in the 24 hours before a final release!

I have just spent several hours trying to figure what is going on.

======================
After reverting to 0c096ed:
 I can switch from memory mode to VFO frequency at will and FreeDv shows the reported frequency correctly. FDV Reporter likewise follows this after a few seconds.

However if I run klog which also tracks the rig frequency all is fine unless I switch to VFO from M mode, then the rig starts to rapidly jump from VFOA to Memory channel and back endlessly. This could be a klog issue as it is supposed to be read only so ignoring this for now.

=========================================
I have now reinstalled 1.8.10 release to test again:
klog is not running.
With M mode selected and the frequency at 14.240, FDV is showing 14.240 and FDV reporter is showing the same. Switching M channel to 14.236 shows correct freq in FDV but now after a minute or so FDVR is still showing 14.240 which replicates what I was seeing earlier today.
Changing rig M freq to 7.177 likewise shows correctly in FDV but FDVR is still at 14.240 with last update showing as 9 mins ago.

Changing to VFO mode on rig now:
VFO was at 18.150 (see /OT at end while I remember). FDV shows 18.150. FDVR is still showing 14.240.

Selecting and clicking a new freq in the new selector in FDV changes the rig correctly to that frequency and hey presto FDVR changes too.

Going back to the rig M mode changes FDV to the correct freq, but FDVR is again stuck on the old VFO freq.

So for now this is looking like a reporting bug introduced by the new frequency setting feature, ignoring the fight between freedv, klog and hamlib for the time being.

/OT
While looking at this I noticed a typo in the freq listings in FDVR for 17m. It says 18.188 which I guess should have been 18.118. 

System is Mageia 9 (dev) (Linux) x86_64
Hamlib 4.5.5 using rigctld with rig type 2003 Kenwood TS450S
lib64sioclient is from git at b10474e

Barry

**Comment by tmiw** [comment]
I just pushed an update to FreeDV Reporter to fix the typo, thanks for letting me know!

As for the memory channel issue, there is logic in the application to prevent the text box in the drop down from getting overwritten during manual edits (vs. when selecting a predefined frequency). I wonder if that is interfering somehow. Do you see the same behavior if you make sure to click on another UI element (e.g. squelch or one of the other tabs) before changing the memory channel/frequency on the radio side?

Additionally, some console output right when reporting goes out of sync would be good too just in case there's some sort of error on there. 👍

**Comment by barjac** [comment]
>As for the memory channel issue, there is logic in the application to prevent the text box in the drop down from getting overwritten during manual edits (vs. when selecting a predefined frequency). I wonder if that is interfering somehow.

No, let's take memory channels away from this for now, they are a red herring.

The frequency displayed in FDV  is always correct no matter how the radio frequency is manually adjusted so nothing is interfering with that. It's the syncing of that frequency with FDVReporter that is failing, UNLESS the change is initiated by a selection from the new spin wheel.

>Do you see the same behavior if you make sure to click on another UI element (e.g. squelch or one of the other tabs) before changing the memory channel/frequency on the radio side?

It makes no difference, the radio frequency is always correctly displayed in the FDV dialogue.

> Additionally, some console output right when reporting goes out of sync would be good too just in case there's some sort of error on there. 

It appears it is always out of sync for any freq changes after start.

Here is the terminal output from running freedv --verbose > fdv_output.log 2>&1
[fdv_output.log](https://github.com/drowe67/freedv-gui/files/11629308/fdv_output.log)
I hit the start button wherupon the rig frequency was changed by freedv to whatever was being displayed there already, which explains why the initial frequency does get shown in FDVR. I then changed the rig band and  stopped FDV to keep the log short.
Nothing changed in FDVR after my call appeared showing the initial frequency that FDV already had stored somewhere on startup.

We need to be able to disable FDV from controlling the rig frequency.  i.e. An optional read only mode.
I for one prefer to just use rig memories for this although I'm sure others will want to use it.

Barry

**Comment by barjac** [comment]
/OT
I just noticed the same 17m error in the frequency spin wheel in freedv.

**Comment by Tyrbiter** [comment]
Not wanting to confuse the issue, but I looked at the log and you're using netrigctl which may mean something else on your system could be sending commands to it in the background. Which radio are you using? It might be that its hamlib implementation is buggy.

I requested the change where the original radio frequency/mode settings are reinstated after the modem is stopped, you're right @barjac that perhaps the changes made were a bit too ambitious. I did wonder what you were doing on 12m when the others were on 60m :)

**Comment by tmiw** [comment]
This is definitely not radio specific. I opened PR #408 that seems to resolve this for me, but it would be good to get some additional testing.

**Comment by barjac** [comment]
Where can I pull a git clone with this PR included? I can't use the PR patch as it includes a binary.
Tried tmwi/freedv-gui but it's not up to date. I'm obviously missing something as not a git guru ;)

**Comment by Tyrbiter** [comment]
You want drowe67/freedv-gui and do a git clone, then git checkout the ms-reporter-hamlib-fix branch.

I may have the exact branch name wrong, but from this page you should be able to find it near the top of the PR #408 link above.

**Comment by Tyrbiter** [comment]
I'm happy with the fixes in PR #408, FreeDV Reporter appears to correctly show operating frequency every time it is changed in both VFO and Memory mode under my setup.
