### ISSUE TITLE
Add "request QSY" feature to FreeDV Reporter

### ISSUE THREAD

**Issue by tmiw** [drowe67/freedv-gui#416]
From Rick WA6III on the digitalvoice list:

> I have a suggestion for an enhancement.   Currently we have no way to contact someone on the active list to change frequencies, unless they happen to be looking at the "Chat" tab.
>
> Since most of the computers that are running FreeDV are also connected to the internet, how about a short messaging system that will allow one user to send a "connect" request to another even though that person is on an different band.?
>
> For example, I am currently on 40M all ready to go and would like another station in the Pacific NW who is currently receiving on 14236.  Right now, 14236 is not very usable in the PNW because people are talking on SSB.
>
> I am in Washington State and I see another station in Oregon that I know is within propagation distance,   I would send him an email , but like many people, he has no posted email address in the callsign databases.
>
> If the software had some sort of P2P (obviously internet based)  messaging capability, it would be easy to get someone to switch bands frequencies etc.
>
> I do not know what this could look like and it doesn't even have to be "free text".  It could be any sort of notification alerting the other operator that someone wants him to switch freq or band etc...

(Opening an issue so we don't lose track of the discussion.)

**Comment by Tyrbiter** [comment]
A related idea, could the chat page show who is logged in, it's difficult to follow the join and leave messages.

**Comment by tmiw** [comment]
> A related idea, could the chat page show who is logged in, it's difficult to follow the join and leave messages.

Seems like that should be straightforward on the backend at least. Any ideas on how/where it should display?

**Comment by Tyrbiter** [comment]
The QSO Finder page shows a horizontal list down towards the bottom of the page, so something like that although it doesn't have to be at the bottom, it just needs to remain visible when scrolling the chat.

**Comment by Tyrbiter** [comment]
OK, I see you have to be logged in to see it.

**Comment by tmiw** [comment]
> OK, I see you have to be logged in to see it.

Indeed. I just restarted it to fix some bugs I saw with the user list earlier today. There's also some preliminary server side support for QSY in the daemon itself now, just waiting on app support (hopefully)

**Comment by Tyrbiter** [comment]
Thought I'd play with the new ms-request-qsy branch, but it falls over with this.

I may have hacked it together badly, started with all the recent merges into master except the hamlib vfo_list one from PR #429.

In file included from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.11/src/pipeline/../freedv_reporter.h:30,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.11/src/pipeline/../main.h:87,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.11/src/pipeline/TxRxThread.cpp:91:
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.11/src/pipeline/../reporting/FreeDVReporter.h:83:5: error: 'sio' does not name a type
   83 |     sio::client sioClient_;
      |     ^~~
gmake[2]: *** [src/pipeline/CMakeFiles/fdv_audio_pipeline.dir/build.make:317: src/pipeline/CMakeFiles/fdv_audio_pipeline.dir/TxRxThread.cpp.o] Error 1

Thought you would like to know.

**Comment by Tyrbiter** [comment]
> It seemed to compile fine for me last night. I'd make sure you can compile by checking out that branch directly and using the build_linux.sh script.
> 
> Note that the new window is in Tools->FreeDV Reporter and definitely has problems. Hopefully I can get it a bit more stable tonight (as well as actually implement QSY requests).

Yeah, I was only checking that I had reverted everything back to a sensible start point for playing with this branch. I will wait until you have fixed it up before I try again.

**Comment by tmiw** [comment]
I have some pretty basic QSY request functionality in PR #434. There are still some things that need to be implemented but this should work well enough to play with if you can get a friend or two to build that branch :)
