### ISSUE TITLE
FreeDV 1.8.10.1 unresponsive when using uBitx v6 (it emulates the FT-817)

### ISSUE THREAD

**Issue by Kimberly-McBlaze** [drowe67/freedv-gui#428]
Not sure what's going on, but FreeDV 1.8.10.1 becomes unresponsive when I try to use my uBitx v6 QRP rig, which emulates the Yaesu FT-817 for cat controls. I set the rig model to FT-857 instead and FreeDV becomes responsive again, but now it wouldn't update the report frequency automatically and when I try to update that manually, it won't take my input and remains stuck on the last frequency I used from a previous version of FreeDV. I'm running Windows 11, by the way.

**Comment by tmiw** [comment]
If you go to Tools->Options->Rig Control and check "Use USB/LSB instead of DIGU/DIGL", does that help?

**Comment by Kimberly-McBlaze** [comment]
I actually had that option checked, but when I go back to uncheck it, it seems to work fine, though still a brief period of unresponsiveness when starting up. The "report frequency" now automatically updates when I adjust my VFO, but only if I click off of the program or if I push a random button on the program to back out of the part of that area that you type numbers in, which seems to want to automatically go into typing mode when I hit the "start" and "stop" button.

**Comment by tmiw** [comment]
> still a brief period of unresponsiveness of approximately 10 seconds when clicking the "start" button

It will take a bit to get hamlib and the sound devices open depending on the specs of your system but the latest version in `master` shouldn't fully freeze up the application entirely (i.e. no "this application is not responding" type messages from Windows).

> The "report frequency" now automatically updates when I adjust my VFO, but only if I click off of the program

If the Report Frequency field has focus, updates from the radio are supposed to be suppressed. However, you don't need to click off from FreeDV entirely, just onto another UI element in that window (for example, one of the tabs on the bottom).

That said, this could probably be handled better. I'm not in a position to test right now but I do have a test build that should automatically cause the Report Frequency field to lose focus as soon as you push the Start button. If you can give it a shot and let me know how it goes, that'd be good: [FreeDV-1.8.10.1-windows-x86_64.exe.zip](https://github.com/drowe67/freedv-gui/files/11713751/FreeDV-1.8.10.1-windows-x86_64.exe.zip)

> it should clear itself from typing mode after pressing "enter" on the keyboard

This should already be getting done, if not for 1.8.10.1, for the version I linked above. Let me know if that's still not the case.

**Comment by tmiw** [comment]
Thanks! I'll go ahead and merge that change, then.
