### ISSUE TITLE
Mode should be changed before frequency

### ISSUE THREAD

**Issue by tmiw** [drowe67/freedv-gui#441]
Per the digitalvoice list, apparently the FT-991A will offset the frequency a bit when using FreeDV as the mode gets changed after the frequency. Swapping the order of operations will supposedly fix this.

**Comment by Tyrbiter** [comment]
A thought, if someone has their radio set up to show mid-filter frequency this can happen but if it's set for carrier frequency then it will not. Generally it's best to use the latter because it avoids going out of band at band edges.

**Comment by tmiw** [comment]
Opened PR to resolve this.

> A thought, if someone has their radio set up to show mid-filter frequency this can happen but if it's set for carrier frequency then it will not. Generally it's best to use the latter because it avoids going out of band at band edges.

As long as the PR doesn't impact use when using the carrier frequency it should be no problem. 👍
