### ISSUE TITLE
Mode box on freedv main window size tweak

### ISSUE THREAD

**Issue by Tyrbiter** [drowe67/freedv-gui#445]
The Mode box defined in the topFrame.cpp file has a minimum vertical size of 240 (line 401 in my current tree), that causes the box to change size when the Others: mode list is expanded and hence the Controls box and buttons move too. This doesn't happen if the minimum size is 250, at least with the Fedora wxWidgets libraries.

**Comment by tmiw** [comment]
I opened a PR for this. Interestingly, I couldn't duplicate it in Ubuntu 22.04 but could on my Fedora 38 VM.
