### ISSUE TITLE
FreeDV Reporter (built-in) now not showing any right hand side info (last heard, last mode, SNR etc.)

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#451]
Since 1.8.12 or maybe just the Thursday, 22 June 2023 version, all the reported data on the RHS of the display is showing as 'unknown'.
It is showing correctly in the web version.

All the other enhancements seem good :)

**Comment by tmiw** [comment]
RHS as in the RX data? I briefly triggered TX and that at least updated for me:

<img width="1266" alt="Screenshot 2023-06-22 at 10 27 42 AM" src="https://github.com/drowe67/freedv-gui/assets/449242/a3784894-beae-4448-a2a2-9e97b48b21d2">

I'll leave it running in the background while I'm working and see if I'm able to receive anything.

**Comment by Tyrbiter** [comment]
I've been watching this and have just seen SV1UH on Tx appear in the Firefox tab pointing at qso.freedv.org, there was no indication of anything in the freedv program FreeDV Reporter window.

Not sure why this should be, but at least it means that there are a couple of reports of things missing.

**Comment by tmiw** [comment]
Try this change:

```
diff --git a/src/reporting/FreeDVReporter.cpp b/src/reporting/FreeDVReporter.cpp
index e0a86a6..4f85bbe 100644
--- a/src/reporting/FreeDVReporter.cpp
+++ b/src/reporting/FreeDVReporter.cpp
@@ -348,7 +348,7 @@ void FreeDVReporter::connect_()
                 receiverCallsign->get_flag() == sio::message::flag_string &&
                 receiverGridSquare->get_flag() == sio::message::flag_string &&
                 mode->get_flag() == sio::message::flag_string &&
-                snr->get_flag() == sio::message::flag_double)
+                snr->get_flag() == sio::message::flag_integer)
             {
                 onReceiveUpdateFn_(
                     msgParams["sid"]->get_string(),
@@ -356,7 +356,7 @@ void FreeDVReporter::connect_()
                     msgParams["receiver_callsign"]->get_string(),
                     msgParams["receiver_grid_square"]->get_string(),
                     msgParams["callsign"]->get_string(),
-                    msgParams["snr"]->get_double(),
+                    msgParams["snr"]->get_int(),
                     msgParams["mode"]->get_string()
                 );
             }
```

**Comment by Tyrbiter** [comment]
No difference from that change.

**Comment by barjac** [comment]
Confirmed - no change.

**Comment by Tyrbiter** [comment]
Right, just got this.

![Screenshot from 2023-06-22 20-59-47](https://github.com/drowe67/freedv-gui/assets/36776842/e7de4cd5-58b8-4b78-a622-7defe691ff9d)

So it seems it works except for the last updated column for some cases at least.

**Comment by barjac** [comment]
I am now seeing the LU stations in qso OK but without last TX or Last update

**Comment by tmiw** [comment]
Could it be some sort of version issue with some of the stations? I just played back a file in FreeDV and it looks like I was able to report myself with no problems with that proposed change:

<img width="1243" alt="Screenshot 2023-06-22 at 2 29 05 PM" src="https://github.com/drowe67/freedv-gui/assets/449242/f88e8759-cb3c-4aa8-90ba-4d2f1e4f327a">

**Comment by Tyrbiter** [comment]
I don't know for sure, but the 2 LU stations appeared and are each using different versions as seen in my previous comment.

Just seen you appear @tmiw but nothing in the final column again while you seem to have it just fine. Something in MacOS? I know we've seen wxWidget differences before.

**Comment by tmiw** [comment]
> I immediately see Receiving change to Transmitting with PTT, but no change to the Last Tx column at all.

It's definitely a Linux thing for the dates. I'm not sure why, though, since regexes should in theory be the same across platforms.

Anyway, https://github.com/drowe67/freedv-gui/pull/434/commits/cd640de4a3d284a18488cb6637d7c7d9588c4c85 resolves the issue:

<img width="1342" alt="Screenshot 2023-06-22 at 6 17 26 PM" src="https://github.com/drowe67/freedv-gui/assets/449242/6f17dd8b-2bdc-479b-88bd-4922ac4a60d6">

**Comment by Tyrbiter** [comment]
Seems to be OK so far, I will see how it goes over the activity weekend.

**Comment by barjac** [comment]
Yes it's looking OK now :) Thanks for letting me know it's an activity weekend!
Maybe I missed the mail.
Where does reporter pull the version from? Running a build from git master I'm displayed as running1.8.11, it would be handy to be able to patch it to display as 1.8.12-devel.

**Comment by Tyrbiter** [comment]
Top level CMakeLists.txt file, you can change the PROJECT_VERSION and add "devel" into the FREEDV_VERSION_TAG

**Comment by barjac** [comment]
> Top level CMakeLists.txt file, you can change the PROJECT_VERSION and add "devel" into the FREEDV_VERSION_TAG

Thanks - all seems well today in the net

**Comment by tmiw** [comment]
> Thanks for letting me know it's an activity weekend!

That was this past weekend. This weekend is ARRL Field Day :)

**Comment by barjac** [comment]
Damn! Missed it again. :(

I just noticed an issue. When the internal freedv reporter first appeared it only ran when the modem was running.
Now it can be started from tools -> FreeDV Reporter at any time and it shows me (G4MKT) 'Receiving' when I am not :( 
![Screenshot_20230623_170619](https://github.com/drowe67/freedv-gui/assets/1324702/3422fd05-bfd7-46bd-baff-506b015a9cad)

**Comment by Tyrbiter** [comment]
> Damn! Missed it again. :(

Me too, brain overloaded right now...

> 
> I just noticed an issue. When the internal freedv reporter first appeared it only ran when the modem was running. Now it can be started from tools -> FreeDV Reporter at any time and it shows me (G4MKT) 'Receiving' when I am not :(
> 
> Edit - Or maybe it's just frozen in time? Yes that is it - maybe it should only start when the modem is running?
> 
> [Screenshot_20230623_170619](https://github.com/drowe67/freedv-gui/assets/1324702/3422fd05-bfd7-46bd-baff-506b015a9cad)

It seems to do the same here, but it doesn't update the times, so just needs some code to clear the window and not allow it to be opened when the modem is stopped. Could we also have a button or menu item to open the web version from the freedv program?

**Comment by tmiw** [comment]
How it's supposed to work is that the web version opens when FreeDV isn't running, but the built-in one does when it is. I'm not sure why that's not happening now, will investigate when I get time.

**Comment by Tyrbiter** [comment]
> How it's supposed to work is that the web version opens when FreeDV isn't running, but the built-in one does when it is. I'm not sure why that's not happening now, will investigate when I get time.

That makes sense, not sure if I had tested that before today.

No need to rush to fix it, workarounds exist.

**Comment by tmiw** [comment]
> > How it's supposed to work is that the web version opens when FreeDV isn't running, but the built-in one does when it is. I'm not sure why that's not happening now, will investigate when I get time.
> 
> That makes sense, not sure if I had tested that before today.
> 
> No need to rush to fix it, workarounds exist.

Confirm that https://github.com/drowe67/freedv-gui/pull/434/commits/78d2554f065c2c2d49d7214d02a71bdcbb1f0133 fixes it? Seems to for me on Ubuntu, anyway.

**Comment by Tyrbiter** [comment]
Yes, a nice simple one line fix, works for me.

I wonder how easy it would be to open an existing tab in a browser if one exists?

**Comment by barjac** [comment]
It fails for me using master @ 31455be
Start program (not modem) and Tools->FreeDV Reporter opens Web version.
Start modem and Tools->FreeDV Reporter still opens Web version.
Stop and re-start modem and Tools->FreeDV Reporter still opens Web version.
Shut down freedv.
Start program and start modem.  Tools->FreeDV Reporter still opens Web version.
Stop and start modem and Tools->FreeDV Reporter still opens Web version.

I can find no way to open the internal Reporter :(

**Comment by Tyrbiter** [comment]
@barjac You probably should pull the ms-rel-v1812 branch and apply this one line fix in ongui.cpp

**Comment by tmiw** [comment]
> I wonder how easy it would be to open an existing tab in a browser if one exists?

I checked and unfortunately, there doesn't seem to be anything in wxWidgets to enable this.

**Comment by tmiw** [comment]
I changed the logic to allow the FreeDV Reporter window to remain open even when it's not running. 

Anyway, I'm going to close out this issue as the main problem (not showing any info in the window) is now solved.
