### ISSUE TITLE
Add ability to filter on band/frequency in FreeDV Reporter

### ISSUE THREAD

**Issue by tmiw** [drowe67/freedv-gui#470]
Per feedback from the digitalvoice list, there should be some sort of way to filter listings in FreeDV Reporter (ideally both in-app and on the website) by band/frequency to make it easier to find contacts. 

Email for context:

> As the number of total FreeDV users increases and more are using the reporter, it might be advantageous to have a band "filter" (toggle-switch) incorporated into the Reporter.
>
> As more users on the west coast for example start using 40 or 75,  the list of callsigns might become a little long if all the other bands are always  included in the list. 
>
> For those using small screen screens such as that on a laptop there's barely enough room for the main window!.
>
> A band filter "button" could allow choosing to display only users on the band of use making it a little easier to see all the users on that band instead of being interspersed with all the other users on different bands.

Questions:

1. Should users be able to show more than one band/frequency at a time, or would the choice be between showing everything and showing only the people on the selected part of the spectrum?
2. How should this present itself to the user (drop-down, checkboxes, etc.)? Can this be different depending on whether it's in-app or the website?

**Comment by Tyrbiter** [comment]
Would it be enough to have a 'group by frequency' check box? Maybe enabling it could sort starting with the local user's frequency, at least for the in-app case.

On the web the old QSO Finder used to group by frequency if the user selected one, that was quite a nice way of seeing who was where.

**Comment by tmiw** [comment]
How about the new drop-down I added to https://qso.freedv.org/? If that works reasonably I'll see if I can bring it over to the in-app version as well.
