### ISSUE TITLE
1khz tone drowning out carriers

### ISSUE THREAD

**Issue by ninjafairy** [drowe67/freedv-gui#473]
FreeDV:  v1.8.12  7/5/23
Radio:  Xiegu G90
Interface: Signalink USB
OS: Windows 10 22H2

Receiving stations report a strong carrier but no decode. Updated from v1.8.5 but issue remained, uninstalled before installing 1.8.12

Other digimodes work normally 

Baseline Audio

![Screenshot_20230711-164339](https://github.com/drowe67/freedv-gui/assets/792629/64378f27-be18-44ae-857e-22d93dfdce33)

Output from FreeDV pointed at computer speaker normal Tx

![Screenshot_20230711-164350](https://github.com/drowe67/freedv-gui/assets/792629/4e705b2d-a231-49bc-9653-9610fde6caa6)

Output from FreeDV pointed at computer speaker with max Tx attenuation

![Screenshot_20230711-164357](https://github.com/drowe67/freedv-gui/assets/792629/3963117e-9ce7-4b27-9b86-7492440bf4a0)

**Comment by tmiw** [comment]
Can you go to Tools->PTT Config and confirm that "Left Channel VOX Tone" is unchecked? i.e.

<img width="634" alt="Screenshot 2023-07-11 at 6 36 17 PM" src="https://github.com/drowe67/freedv-gui/assets/449242/266a8ac4-f8d6-44a3-9122-47327c551872">

**Comment by ninjafairy** [comment]
It was checked

Unchecking removed the tone

Thank you so much
