### ISSUE TITLE
PTT control settings and CAT frequency control issues in FreeDV version 1.8.12

### ISSUE THREAD

**Issue by computer-wizard** [drowe67/freedv-gui#477]
Transceiver Yaesu FT-847, OS: Ubuntu 22.04,  FreeDV version 1.8.12

I have to use a separate USB to serial converter to control PTT as every connector (pkt, rtty & mic) has its own PTT in the FT-847. PTT over CAT can only control the front mic as this is a limitation of the firmware in the FT-847.
RTTY connector is used with FreeDV.

Problem with FreeDV version 1.8.12

I can't use FreeDV to control the frequency over CAT (hamlib) after FreeDV startup. I use the following workaround in version 1.8.12,

1)  Switch to "Use Hamlib PTT"  (Rest of hamlib settings are already setup in FreeDV)
2)  Test the PTT with 1)
3)  Switch over to "User Serial Port PTT"  

Now I can use FreeDV to set the frequency over CAT, although the hamlib settings are greyed out.
I have to repeat the same workaround the next time I start FreeDV.

What I suggest is to make the PTT method separate from the rest of the (hamlib) CAT settings with a separate enable box,
(Something along the line what WSJT-X is doing.) so that the rest of CAT control is still enabled.

Thanks

**Comment by tmiw** [comment]
Would the existing "PTT via" control work for your purpose?

<img width="517" alt="Screenshot 2023-07-16 at 2 32 51 PM" src="https://github.com/drowe67/freedv-gui/assets/449242/8cbccce6-0d96-41de-8984-c363988c80a1">

You'll probably have to make up a new cable, though, to route RTS or DTR to the correct RTTY jack on the back.

**Comment by tmiw** [comment]
I haven't heard anything back on this but I think it's reasonable to have another "PTT Device" drop-down (probably only in the advanced PTT settings, not in Easy Setup) that appears if you choose RTS or DTR for "PTT uses". It'd probably not be too bad to hook into Hamlib, either. Will see if I can get some time.

**Comment by computer-wizard** [comment]
Thanks
