### ISSUE TITLE
Restore screen layout between re-starts of FreeDV

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#495]
I have been asked to add this 'Enhancement Request' by Matt who reads the RSGB news in the UK using FreeDV every Sunday.
He has a rather complex system and uses this screen layout for FreeDV during the broadcasts:

![image](https://github.com/drowe67/freedv-gui/assets/1324702/a920df48-73d8-4e75-a257-b409e19c3758)

As you can imagine it takes a bit of setting up each time, so it would be good if it would restore to this layout on each start.

73
Matt & Barry

**Comment by tmiw** [comment]
This might be non-trivial to do as currently written. For example: https://forums.wxwidgets.org/viewtopic.php?t=48127

Will keep open for now in case me or someone else gets time to investigate in the future :)

**Comment by Tyrbiter** [comment]
> This might be non-trivial to do as currently written. For example: https://forums.wxwidgets.org/viewtopic.php?t=48127

They threw it over the wall and then ran away. That's really not ideal.

**Comment by tmiw** [comment]
> > This might be non-trivial to do as currently written. For example: https://forums.wxwidgets.org/viewtopic.php?t=48127
> 
> They threw it over the wall and then ran away. That's really not ideal.

Agreed. I do have a PR that seems to work (#497) but it's definitely not ideal as I'm literally bringing in an internal wxWidgets class verbatim (except with a different name to avoid linker issues). Apparently other projects that need similar functionality are doing the same thing so that is something we could do, but would rather we didn't if possible.

**Comment by tmiw** [comment]
FWIW, the difference for wxTabFrame between wxWidgets 3.0 and 3.2 seems to be one #ifdef block that doesn't seem to matter for our purposes. I suspect this class actually doesn't change much but we'd still need to prove it out across multiple test builds before we consider merging (and even then, it might be worth filing an issue/PR to get wxTabFrame added to the public API or at least some sort of officially sanctioned method of saving/restoring tab state).

**Comment by barjac** [comment]
Matt is now using this 'experimental' feature in his RSGB news broadcasts and has asked me to thank you for taking the the time and trouble to include it.
It is working perfectly and he finds it much easier to set up his system now. :)
