### ISSUE TITLE
"Monitor mode" for TX

### ISSUE THREAD

**Issue by tmiw** [drowe67/freedv-gui#498]
Basically, this would be an option that could be enabled to allow one to listen to themselves as they're transmitting. This would allow live feedback for filter changes (among other things).

Proposed workflow:

* User right-clicks on the PTT button and chooses "Monitor" to enable or disable this option.
* User left-clicks to transmit/stop transmitting as normal. If "Monitor" is checked", they'll hear themselves :)

**Comment by tmiw** [comment]
@barjac, @Tyrbiter: I opened this issue for the "hearing yourself while transmitting" request. I think it should be something more general than just something connected to the VK function, thus the issue tying it to TX in general.

**Comment by Tyrbiter** [comment]
> @barjac, @Tyrbiter: I opened this issue for the "hearing yourself while transmitting" request. I think it should be something more general than just something connected to the VK function, thus the issue tying it to TX in general.

A good idea, some minor changes to the tool-tip to explain the function and the new control should be nice and simple.

**Comment by barjac** [comment]
> Basically, this would be an option that could be enabled to allow one to listen to themselves as they're transmitting. This would allow live feedback for filter changes (among other things).
> 
> Proposed workflow:
> 
>     * User right-clicks on the PTT button and chooses "Monitor" to enable or disable this option.
> 
>     * User left-clicks to transmit/stop transmitting as normal. If "Monitor" is checked", they'll hear themselves :)

I don't see a need for this in normal TX, only for VK. In fact I really would not want this for normal TX at all.
If this is introduced for both then I suggest separate 'enable' options which have persistence across program sessions/reboots.

**Comment by tmiw** [comment]
How should the VK monitor setting be changed? Via the right-click VK menu (similar to what's proposed for PTT) or some other means?

**Comment by Tyrbiter** [comment]
I would think a separate 'sticky' setting for VK and PTT would meet Barry's needs, and certainly mine.

**Comment by tmiw** [comment]
https://github.com/drowe67/freedv-gui/pull/500 :)
