### ISSUE TITLE
Last version compilation of FreeDV on RaspberryPI

### ISSUE THREAD

**Issue by UgoPoddine** [drowe67/freedv-gui#50]
Hello David,

I have just downloaded last release of FreeDV on my RaspberryPI. As you know, till now and since last July, it was possible to compile and use FreeDV on RaspberryPI3 without the FreeDV GUI (freedv_tx and freedv_rx run very well in home-made wrapper).
I was curious to see the effect on the PI of you last adjustments on GUI (with a little attention on RaspberryPI4), but unfortunately today the new version compilation stops in an neverending idle status at this point :

[....] 

-- LPCNet version: 0.1
-- Looking for available CPU optimizations on Linux/BSD system...
-- neon processor flags found or enabled.

... stops working here and only CTRL+C solve the issue

Can you help ?
Thnak-you
Ugo

**Comment by drowe67** [comment]
Hi Ugo,

Hmmm, I can't think of anything that has changed in freedv-gui that would affect compilation in the Pi.  However it's not a platform we are testing and developing on, so I can't say for sure (I don't have a Pi 4).

From your trace above it looks like the LPCNet compilation, which hasn't changed for a long time. Perhaps running cmake in verbose mode might help you find here it stops?

Cheers,
David

**Comment by UgoPoddine** [comment]
Hello David,

I will do in -v
If I remember correctly some last year discussions, LPCnet compilation has to be jumped for small platforms or something like this.
After July, freedv gui compilation crashes after the platform verification (I wonder that a mail from me is there, and also an issue from someone else). 
As in any case, without this test, before July, freedv gui could be built on raspberry (not so useful for PI3, but PI4 is more powerful), I wonder that something is recently changed in the make procedure (I have seen a pull request on this, if I'm not wrong...).
In any  case I will give you the verbose log asap

Thank-you as usual, really good job (also if find guys to use it is still difficult)

Ugo


Il giorno 11 Mar 2020, 21:15, alle ore 21:15, drowe67 <notifications@github.com> ha scritto:

**Comment by UgoPoddine** [comment]
Hello David,

I was able to compile the new version correctly on Raspberrypi PI4 and the GUI is running again on PI. Not tested the performances.
On my PI3, I have tried again having the X environment switched off, and I was able to finish the compilation, this time.

You can close the issue
Thank-you 
Ugo



Il giorno 11 Mar 2020, 21:15, alle ore 21:15, drowe67 <notifications@github.com> ha scritto:

**Comment by drowe67** [comment]
Well done Ugo.  Hope you are doing well there with the virus situation in Italy.
