### ISSUE TITLE
Date format in FreeDV Reporter (internal)

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#508]
I have just received a comment from a new user about the reporter and I must agree with him.
The date format is rather confusing and difficult to read quickly.
At present it is displayed as:
Sat Aug 19 02:56:25 2023
The '2023' at the end can be confused with the time and is the year really needed?
Normal convention for year in a date would be to include it in the date not the time, so:
Sat Aug 19 2023 02:56:25
...would be more appropriate.

If the year was removed then:
Sat Aug 19 - 02:56:25
... would split the time from the date cleanly and be much more readable and compact than it is now.

WDYT?

**Comment by tmiw** [comment]
FreeDV uses wxWidgets' `wxDefaultDateTimeFormat` for formatting which seems to be `%c` according to src/common/datetime.cpp in the wxWidgets source:

```c++
// ----------------------------------------------------------------------------
// global data
// ----------------------------------------------------------------------------

const char wxDefaultDateTimeFormat[] = "%c";
```

And since wxWidgets seems to just use `strftime` internally, it looks like it's using what the default format is according to the user's locale:

```
       %c     The preferred date and time representation for the current
              locale.  (The specific format used in the current locale
              can be obtained by calling [nl_langinfo(3)](https://man7.org/linux/man-pages/man3/nl_langinfo.3.html) with D_T_FMT as
              an argument for the %c conversion specification, and with
              ERA_D_T_FMT for the %Ec conversion specification.)  (In
              the POSIX locale this is equivalent to %a %b %e %H:%M:%S
              %Y.)
```

Anyway, I'd make sure that the current locale on your end is set correctly. I'm hesitant to make any changes here as it would potentially mean forcing every user worldwide to use the same date/time format. 

BTW for US users on macOS, this is what it looks like:

![Screenshot 2023-08-19 at 11 49 10 AM](https://github.com/drowe67/freedv-gui/assets/449242/8e75ece8-0fdd-4f82-86d4-8bc39cd9870a)

**Comment by barjac** [comment]
[baz@localhost ~]$ cat /etc/locale.conf 
COUNTRY=GB
LANG=en_GB.UTF-8
LANGUAGE=en_GB.UTF-8:en_GB:en

[baz@localhost ~]$ date
Sun 20 Aug 22:32:51 BST 2023

The above is from my Mageia 9 Linux system. The other user who sees the same format as I do is using Win10.

Maybe the date/time format string could be a setting in freedv to allow users to select a more suitable format for their own locale and operating system.

I would probably use '+%d/%m/%y-%H:%M' which with the date command produces:
```
[baz@localhost ~]$ date '+%d/%m/%y %H:%M'
20/08/23 23:12
```

**Comment by tmiw** [comment]
So, I don't think it's actually picking up the `LANG` environment variable. For reference, here are the formats for various English speaking countries that show up for me:

```
mooneer@ubuntu:~/freedv-gui/build_linux$ LANG=en_GB.UTF-8 date +"%c"
Mon 21 Aug 2023 00:16:39 PDT
mooneer@ubuntu:~/freedv-gui/build_linux$ LANG=en_US.UTF-8 date +"%c"
Mon 21 Aug 2023 12:16:43 AM PDT
mooneer@ubuntu:~/freedv-gui/build_linux$ LANG=en_CA.UTF-8 date +"%c"
Mon 21 Aug 2023 12:16:47 AM
mooneer@ubuntu:~/freedv-gui/build_linux$ LANG=C date +"%c"
Mon Aug 21 00:16:56 2023
mooneer@ubuntu:~/freedv-gui/build_linux$
```

while in testing, even if overridden with `LANG`, I always seem to get the C locale date string in the FreeDV Reporter window.

Anyway, it looks like wxLocale needs to be initialized before all the date/time stuff works properly. See https://github.com/drowe67/freedv-gui/pull/509 for fix.

**Comment by Tyrbiter** [comment]
Just tried the locale fix, it does what it says on the tin!

As for the comment from @barjac it's quite a good suggestion, but I don't know if there is any easily reusable code that does this.

**Comment by barjac** [comment]
> As for the comment from @barjac it's quite a good suggestion, but I don't know if there is any easily reusable code that does this.
It would need to get the time elapsed since the date value passed to it and conditionally decide on the appropriate message to output and calculate the number of mins, hours, days or weeks etc. to display. Sadly my C++ is limited to Arduino programming or I would have a go. ;)

**Comment by tmiw** [comment]
Considering that FreeDV requests the current frequency/mode from Hamlib every five seconds or so (which implicitly triggers an update to FreeDV Reporter), the "Last Update" field might always show as "Just now" with the above logic. There's also the complication that we would probably need to iterate through all visible rows once a second to update to "X min ago" etc. as needed.

Anyway, I updated the date format in the PR to something that should still be locale-sensitive but shorter :)

**Comment by barjac** [comment]
Thanks Mooneer, that works for me!
![Screenshot_20230822_102923](https://github.com/drowe67/freedv-gui/assets/1324702/4b77fd2c-f994-479b-8198-71f4eb21fdc8)

**Comment by tmiw** [comment]
Cool, I merged the PR and will go ahead and close this for now.
