### ISSUE TITLE
Feature Request: PTT Input

### ISSUE THREAD

**Issue by drowe67** [drowe67/freedv-gui#51]
Sigi dg9bfc writes:

in freedv soft you have ptt out on a comport (to key external rig) ... so far so good

can you add also a PTT IN via CTS on a comport??

reason is ... i now use freedv on qo100 with sdr console ... and in normal ssb i key the sdr radio with usb/serial converter (ftdi chip) with a pullup resistor and pulling the cts pin to ground

**Comment by oh3gai** [comment]
First of all  thanks for great application.

Serial PTT in would be great improvment and / or wild idea to support for "zello" bt mic which would make IE. mobile operation simple. Audio in /out and ptt in same package.  

https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.com%2Fulk%2Fitm%2F164035444072

Good work !!
Br,Jarno / OH3GAI

**Comment by DG9BFC** [comment]
Hello David
any news about adding the PTT IN ?
a similar setup like we have for ptt out 
select comport and select pin to be used

**Comment by drowe67** [comment]
@DG9BFC this feature would involve significant effort to implement.  We would need to be arbitrate between the same serial port being used for PTT control.  Our experience has been anything around serial ports involves many support issues.

So some questions:
1. How any other people want this feature? Pls show this is not a one-off feature.  Wide spread email support on the digital voice list would be useful.
1. Is there any other way to do it with 3rd party software?  Is anyone else using a foot switch or external PTT control with FreeDV already?

**Comment by drowe67** [comment]
Here is one other request: https://github.com/drowe67/freedv-gui/issues/52

**Comment by DG9BFC** [comment]
There is no way for a foot pedal(YET!) You need to use the mouse... Should be a comport in on cts pinA usb to serial converter like ftdi or profilic and you can use any desktop mike with a ptt switch with pulling cts to ground So no more need of mouse switchI have no idea how many would use it.. But i guess a lot users would love to have a normal ptt button and do not need to use mouse to press ptt on screenA real ham radio mike can be wired that way to the PC.....similar as what i do with my sdr setup a normal user with a rig can wire gis handheld or desktop mike to pc... Ptt in on one comport... Ptt out on another port?? Or wire pc and rig in parallel?? So... I think a ptt in is a good ideaGreetz dg9bfc sigiAm 06.01.2021 23:23 schrieb drowe67 <notifications@github.com>:
@DG9BFC this feature would involve significant effort to implement.  We would need to be arbitrate between the same serial port being used for PTT control.  Our experience has been anything around serial ports involves many support issues.
So some questions:
How any other people want this feature? Pls show this is not a one-off feature.  Wide spread email support on the digital voice list would be useful.Is there any other way to do it with 3rd party software?  Is anyone else using a foot switch or external PTT control with FreeDV already?

**Comment by drowe67** [comment]
@DG9BFC pls answer my questions (1) and (2).  You may need to do some research with other users.

There is also the spacebar to toggle PTT.

**Comment by oh3gai** [comment]
Hi and thanks for good work!

I've been using serial COS / PTT connection for external desk mic and to link different roip app's together via virtual serial cable.  SVXlink, Zello, Echolink, Bluedv etc. they all support COS / PTT via serial so in that sence the serial connection is quite universal way to connect apps, but I also understand that it will make lot of support requests too.

I made dirty solution for freedv ptt with autoit. It presses freedv ptt button ui element when cos is received from other application. It's not very sophisticated solution, but in that way I was able to make some testing with freedv and I didn't need to talk with my self.. :)

You have great application!

br, Jarno

**Comment by drowe67** [comment]
@oh3gai - thanks for your comments!  Can you pls tell me what COS stands for?  New term to me....

So it sounds like we would need a few options:
1. Control via a serial byte of sequence of bytes received on a serial port.
1. Control via level on the serial hardware flow control pins.

In other applications is the COS/PTT input the same serial port as the PTT output?  Or are they different ports?  Thinking about how to handle the case where serial is used for PTT in and PTT out at the same time.

**Comment by DG9BFC** [comment]
@oh3gai ... can you send me some info how you made the "dirty" solution via autoit ??
while david may think about the ptt INPUT i would like to try out your workaround
dg9bfc(at)freenet.de

**Comment by oh3gai** [comment]
Hi!

I think the COS is abreviation of Carrier Operated Switch. So I was able to get feed back when squelch was open and radio was receiving. 

br, Jarno

**Comment by tmiw** [comment]
Quick question on this--it seems that the existing circuits for a foot pedal based PTT bridge RTS or another "output" serial pin with CTS or another input pin, not bridge the latter directly to ground. Examples:

https://www.n1fd.org/2020/05/21/remote-ptt-switch/
https://ece.uwaterloo.ca/~drayside/altinput/

I'm not even sure how a direct to ground implementation would work (would the CTS pin float to some random value when the switch isn't pressed?) but I could just not be 100% fully understanding how RS-232 works.

@drowe67, to reduce complexity I propose just supporting hardware pins for now (and requiring use of a separate port from the PTT output to the radio). Seems like it'd cover a fair bit of the use case for this feature.

BTW, the latest master supports enabling/disabling PTT by using Alt-P or the space bar. This was done (along with other changes) to better support visually impaired usage. It may not handle all the reasons to use a foot switch--especially since the application would still need to be in the foreground for those keys to work--but could still help.

**Comment by DG9BFC** [comment]
@tmiw mooner ... the direct to ground is made via a usb to serial converter (i used ftdi but others also should work)
the ftdi chip "inverts" the signal on cts ... means on input of that cts pin on the ftdi chip you connect a pullup resistor (it is then high and sends a low signal to the pc)
that pin can now be switched to ground (like we normally use ptt on ham gear) ... and sends a high signal to the pc (means switch to tx )
if freedv would allow the same it would be a bit easier to combine sdr soft and freedv soft or a conventional rig and freedv with a hard wired ptt (footpedal or whatever)
ok now i use freedv in fullduplex and only switch the sdr soft (the rig so to speak) ... so i can live without the ptt in 
when using freedv with sdr soft ... or with an external rig .. both could be used with a wired ptt
if windows does not allow using the same port you can either use a serial port emulator (vspe as an example) ... or just use two ports (one for tx in and one for ptt out to the rig)
i can push freedv AND sdr soft to the task bar (and do other things on the pc aka have other things in foreground) .. the ptt in still works fine (while i type this my sdr soft runs "on taskbar" and ptt to switch to tx still works fine)
be independant of the keyboard (say to type in logbook or just to look in qrz.com page while doing a qso)
so just for use freedv .. its not needed ... but would make things a lot easier :-)
REAL serial ports want to see plus and minus voltage but those usb to serial converters only need the voltage high or low measured against ground (no negative voltage) ... and its a lot easier for us hams to use a "switch to ground" ptt (and as a sidenote there are just a few pc left that have a real rs232 port)
you can configure any keyboard command (you mentioned alt-p) ... that is not the point
point is NO KEYBOARD needed when using wired ptt in and a "normal ham gear mike"
greetz sigi
ps i now use a wireless speaker-mike (not bluetooth but dect) and can walk around in the house while doing a qso cause it allows audio in both ways AND PTT ...

**Comment by drowe67** [comment]
> Quick question on this--it seems that the existing circuits for a foot pedal based PTT bridge RTS or another "output" serial pin with CTS or another input pin, not bridge the latter directly to ground. Examples:

Good question - we want to make sure this feature is useful with commonly used PTT input devices.  The SM1000 is pulled to ground for external PTT.  Perhaps get some more feedback on conventions for external PTT from some other Hams?

> @drowe67, to reduce complexity I propose just supporting hardware pins for now (and requiring use of a separate port from the PTT output to the radio). Seems like it'd cover a fair bit of the use case for this feature.

I agree - the end user interest for this feature is low, so if you want to implement it just take the simplest approach.

**Comment by DG9BFC** [comment]
I already explained how i solved the „switch to Ground“ thingy
Most pc now do not have a real rs232 (or just one that may be already in use)
A usb to Serial converter does the trick
Peel off the case .. solder in a pullup resistor to cts … connect your footpedal
Done
Greetz sigi dg9bfc

Gesendet von Mail für Windows 10

Von: drowe67
Gesendet: Sonntag, 30. Mai 2021 23:11
An: drowe67/freedv-gui
Cc: DG9BFC; Mention
Betreff: Re: [drowe67/freedv-gui] Feature Request: PTT Input (#51)

Quick question on this--it seems that the existing circuits for a foot pedal based PTT bridge RTS or another "output" serial pin with CTS or another input pin, not bridge the latter directly to ground. Examples:
Good question - we want to make sure this feature is useful with commonly used PTT input devices. The SM1000 is pulled to ground for external PTT. Perhaps get some more feedback on conventions for external PTT from some other Hams?
@drowe67, to reduce complexity I propose just supporting hardware pins for now (and requiring use of a separate port from the PTT output to the radio). Seems like it'd cover a fair bit of the use case for this feature.
I agree - the end user interest for this feature is low, so if you want to implement it just take the simplest approach.

**Comment by tmiw** [comment]
I have an initial implementation but I haven't tested it yet (I need to wire up something here first). However, I'm somewhat confident that it'll at least partially work, so I'm also open to generating Windows builds for testing if you guys prefer.

**Comment by DG9BFC** [comment]
PLEASE … a dropboxlink??

Gesendet von Mail für Windows 10

Von: Mooneer Salem
Gesendet: Montag, 31. Mai 2021 12:00
An: drowe67/freedv-gui
Cc: DG9BFC; Mention
Betreff: Re: [drowe67/freedv-gui] Feature Request: PTT Input (#51)

I have an initial implementation but I haven't tested it yet (I need to wire up something here first). However, I'm somewhat confident that it'll at least partially work, so I'm also open to generating Windows builds for testing if you guys prefer.

**Comment by tmiw** [comment]
I'll generate special builds with that PR; the ones I just emailed out don't have PTT input support.

**Comment by DG9BFC** [comment]
Yes .. downloaded … seems to work fine .. but no ptt Input found
If you have a testversion send it to me direct

Gesendet von Mail für Windows 10

Von: Mooneer Salem
Gesendet: Montag, 31. Mai 2021 12:54
An: drowe67/freedv-gui
Cc: DG9BFC; Mention
Betreff: Re: [drowe67/freedv-gui] Feature Request: PTT Input (#51)

I'll generate special builds with that PR; the ones I just emailed out don't have PTT input support.

**Comment by tmiw** [comment]
https://www.dropbox.com/sh/b8rxiu6ywliih1x/AAAQUdVu549Ty7WD39N2S9Iea?dl=0

**Comment by tmiw** [comment]
I was able to test the build this morning and ran into issues. The URL above has now been updated with a build that works. 👍
