### ISSUE TITLE
FreeDV (internal) Reporter duplicates reports.

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#513]
Using master at #8816ffb.
Today during a net on 60m, I switched to displaying 'all bands' and noticed a callsign appearing around 6 times but with frequency of 0.00 MHz apparently 'Receiving'. One was showing as 'transmitting'.
Switching to 'Other' a short while later showed 13 instances of the same callsign, so I grabbed a screenshot:

![image_2023-08-23_17-15-26](https://github.com/drowe67/freedv-gui/assets/1324702/579ba0b9-2f70-4969-ad0b-d2cf24b14eba)

**Comment by tmiw** [comment]
I see duplicates for that person on the web version, too, so I suspect they're just having a network issue. Assuming their network eventually gets stable, the duplicates should disappear on their own. Let me know if that doesn't happen.

**Comment by tmiw** [comment]
I haven't heard anything about this recently so I'm going to close for now. Feel free to reopen if the issue comes back.

**Comment by barjac** [comment]
It's not happened again so that's fine.

**Comment by barjac** [comment]
It's happening again in ms-sort-reporter:
![Screenshot_20230903_182437](https://github.com/drowe67/freedv-gui/assets/1324702/5c09a3f3-a239-4ae2-b307-ed78bda26889)

**Comment by tmiw** [comment]
I wasn't able to see it by the time I was able to get to a computer this morning but I did push a change on the server side that might help.
