### ISSUE TITLE
More options for the FreeDV (int) Reporter 

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#516]
Since the QST article about FreeDV has been published it has become clear that the reporter needs to have more fine grained setting options.
It's great to see more stations on the bands, but on 20m especially the reporter is becoming difficult to read in use.
Suggestions:
1 A filter to remove calls that have not been updated in the last N mins.
2 An option to only display (or highlight?) calls who have received me in the last N mins).
3 Show my own call line in a different colour.
4 An option to switch the reporter band filter automatically to the currently reported band (but only when that changes). i.e. The reporter band selector would still over-ride.

Just few ideas for discussion ;)

**Comment by tmiw** [comment]
I'm not sure about (1) and (2) as some clients (like ezDV) won't really update unless something (e.g. frequency, TX state, RX callsign) actually changes. 

On that note, how do you find that you handle it on the web version?

**Comment by barjac** [comment]
> I'm not sure about (1) and (2) as some clients (like ezDV) won't really update unless something (e.g. frequency, TX state, RX callsign) actually changes.
Isn't that the point though? If RX callsign actually changes then they should display so that would not be an issue. If none of those triggers have happened in the last e.g. 30 mins then remove them until something does happen. There are stations where the last update was 3 days ago, why clutter the screen with these if you (optionally) don't want to?
> 
> On that note, how do you find that you handle it on the web version?
I don't, I rarely look at the Web version now as it occupies more screen space or it's own window.  I used to like the green highlighting in the web version which kept refreshing and fading (seems broken now) which is missing in the internal version. Others have been commenting on this too on the air. They were sticking with the web version for this very reason but now are seeing the green highlight problem where it does not stay long enough and fade away slowly as before.

**Comment by tmiw** [comment]
> Isn't that the point though? If RX callsign actually changes then they should display so that would not be an issue. If none of those triggers have happened in the last e.g. 30 mins then remove them until something does happen. There are stations where the last update was 3 days ago, why clutter the screen with these if you (optionally) don't want to?

Maybe the internal one can sort by time (most recent first)? That way, at least active people will be easier to find.

> I don't, I rarely look at the Web version now as it occupies more screen space or it's own window. I used to like the green highlighting in the web version which kept refreshing and fading (seems broken now) which is missing in the internal version. Others have been commenting on this too on the air. They were sticking with the web version for this very reason but now are seeing the green highlight problem where it does not stay long enough and fade away slowly as before.

I pushed a change that I think might help with that. Let me know if it does?

**Comment by barjac** [comment]
> Maybe the internal one can sort by time (most recent first)? That way, at least active people will be easier to find.

That would help although if that was done, then I think the controls (Band spin wheel, Close etc.) would need to be at the top between the the column labels and the window header, or with a big list it would be difficult to access, while watching only the top of the list.
The snag that I can envisage is that with several QSOs active the top of the list would be jumping about too much as the stations pass TX to each other.


> I pushed a change that I think might help with that. Let me know if it does?

Yes that is looking much better - nice!

I had an idea that would be really cool but I guess a bit difficult to implement. Allow each user to pick his own display colour which could be used to highlight his line and stations hearing him. This would remove confusion between QSOs. It is done in some web based collaboration pads where users pick a colour as they check in. I was initially thinking about the Internal Reporter but the same in both would be great! /o\

**Comment by tmiw** [comment]
I was researching a bit more and I think we might be able to let users sort on any of the columns, much like the web version. I'll play around a bit in the code when I have a chance.

**Comment by tmiw** [comment]
I have a PR open for usability enhancements at https://github.com/drowe67/freedv-gui/pull/519. So far, it's just being able to sort the columns, but we could potentially add additional stuff there too.
