### ISSUE TITLE
Waterfall frequency scale - a bit inconsistent and cluttered

### ISSUE THREAD

**Issue by Tyrbiter** [drowe67/freedv-gui#517]
I am not a heavy waterfall user but recently I have been using it more than I have previously and have noticed that it needs a bit of tidying up, in my humble opinion :) The actual waterfall is much improved, it's the labelling that is not great.

The frequency annotation and scale markings appear to be overlaid at the top of the waterfall, which makes them more difficult to read than the same information on the spectrum display which is presented below the display. In particular the 500Hz label and multiples of it are difficult to place as the longer marks are unclear on the waterfall, but are perfectly legible on the spectrum display.

I think it would be better to be consistent with the spectrum tab if possible, I don't think there is a convention for where the frequency scale is displayed on a waterfall, however both my IC-7300 and TS-890 have the finer markings below their waterfalls.

Worth looking at?

**Comment by Tyrbiter** [comment]
![2023-09-01_00-04](https://github.com/drowe67/freedv-gui/assets/36776842/3483166c-4f07-4c58-80f6-c982a1ab7e09)

Here's a screenshot in case this is a Linux wxWindows quirk.

**Comment by tmiw** [comment]
Should be improved now. :) See #518.

<img width="931" alt="Screenshot 2023-08-31 at 6 03 54 PM" src="https://github.com/drowe67/freedv-gui/assets/449242/2e9741dd-4e3f-4048-9512-f75be22c6403">

<img width="575" alt="Screenshot 2023-08-31 at 6 04 01 PM" src="https://github.com/drowe67/freedv-gui/assets/449242/59aa704e-66bf-412c-94fd-d1d88a472507">
