### ISSUE TITLE
Feature request:External PTT input

### ISSUE THREAD

**Issue by oh3gai** [drowe67/freedv-gui#52]
First of all  thanks for great application.

This feature is probably the same what was allready asked,but.. 

External serial PTT in would be great improvment.

Wild idea to support ie. "zello" bluetooth mic which would make mobile operation simple. 

Audio in /out and ptt on same package. 

Thanks for the good work !!
Br,Jarno / OH3GAI

**Comment by drowe67** [comment]
Hi Jamo, glad that you like freedv-gui.  Is the request the same as https://github.com/drowe67/freedv-gui/issues/51?  If so, please add your notes there so we can keep them together.

I'm looking for volunteers to work on this one - basic C++ on Linux skills required.  I can help them.

Cheers,
David

**Comment by oh3gai** [comment]
Hi! Thanks for answer, I wasn't quite sure are we talking about same think about the #51 . So thats why I made new issue. I'm not familiar with Sdrconsole & Qo 100 stuff.
