### ISSUE TITLE
Allow running FreeDV Reporter (internal) when not reporting.

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#527]
Many people use a second machine to run freedv to monitor a web sdr whilst operating.

This causes a second entry in freedv reporter if they have 'reporting' enabled.

This is undesirable as the report is effectively fake (not from their own station) and clutters the reporter.

If they disable reporting to avoid the above then they cannot use the internal reporter on that machine as it stops working with 'reporting' unchecked.

Can the internal reporter be made to report activity when not itself reporting?

**Comment by barjac** [comment]
This was fixed but is now broken in 1.9.2

**Comment by tmiw** [comment]
Try #542?

**Comment by barjac** [comment]
Looks great, will build and test in aarch64 for monitoring, and run it on x86_64 later today.

**Comment by barjac** [comment]
Perfect! You worked wonders again :)
Here is RPi4b running Mageia9 and FreeDV with Firefox and a UK Web SDR while now not reporting itself. :)

![monitoring_SDR_RPi4_Mageia9](https://github.com/drowe67/freedv-gui/assets/1324702/9bedbf4e-683e-4b39-ab2d-4077bcaf7c1f)
