### ISSUE TITLE
Option to have the internal  Reporter band filter track the Reported Frequency.

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#530]
My thoughts are that with this option enabled that the reporter band filter would track the Reported Frequency no matter whether this is selected in FreeDV (when hamlib is used to control the rig), or whether it is reported to FreeDV from the rig when in 'read-only' mode.

Changing the band selector manually in the Reporter would still over-ride the tracking until either the modem is re-started and/or the Reported Frequency changes. Effectively this means that only 'changes' in Reported Frequency need to trigger an update of the band filter.

This could be a check box on the 'control bar' in the reporter. Its state should survive re-launches of FreeDV.

When the 'Track' check box is un-checked operation would be as now.

**Comment by tmiw** [comment]
Would it be okay if the "Show stations on" and this new option are on a line directly above the buttons? I'd like to avoid potentially making the window wider than necessary.

**Comment by barjac** [comment]
I would prefer it to not waste another line.
Could it be in the main program under the Report Frequency with something like:
Link [X]?
On wide laptop screens there is very little height to fit many Reporter lines as it is now.
At present the controls line is much shorter than the table width so I don't see how this is a problem, yet ;)

**Comment by Tyrbiter** [comment]
Maybe the band selector drop down could have an "Own band" entry? That wouldn't add any extra lines or space.

**Comment by barjac** [comment]
> Maybe the band selector drop down could have an "Own band" entry? That wouldn't add any extra lines or space.

Assuming that the tracked frequency when 'track is checked' would not affect the currently 'selected band' in the reporter then this suggestion would inhibit rapid un-checking of the check mark to quickly look at the reporter on the 'selected band' and then return to tracking the band in use by re-checking.
It would reduce usability.

**Comment by Tyrbiter** [comment]
So with 'own band' selected a selected 'filter' checkbox could appear allowing a quick look at the unfiltered list by unchecking it.

The logic would need to be deterministic to prevent confusion.

Maybe I am confused about exactly what @barjac has asked for, we all use the feature in a slightly different way and I may be misinterpreting the request.

**Comment by tmiw** [comment]
It sounds like @barjac prefers only using a checkbox and not having to select anything from the drop-down list at all (though the list may change on its own depending on the frequency selected in the main window).

How about:

Show stations on: [current band] [X] Filter tracks frequency 

(and then the existing buttons to the right)

?

**Comment by barjac** [comment]
> It sounds like @barjac prefers only using a checkbox and not having to select anything from the drop-down list at all (though the list may change on its own depending on the frequency selected in the main window).

Not quite:
If checkbox off then select from list exactly as now - no change.
On turning on checkbox leave list alone (maybe grey it out) and track current band, whether from rig (read only) or from pull down in main window. i.e. whatever band corresponds to the displayed frequency being reported.
On unchecking the checkbox un-grey the reporter band selector and return to the originally selected band in the reporter list.



> 
> How about:
> 
> Show stations on: [current band] [X] Filter tracks frequency
> 
> (and then the existing buttons to the right)
> 
> ?

Possibly yes, but maybe replace 'current band' with 'auto [X]' and when auto checked, grey out the selector?

**Comment by Tyrbiter** [comment]
I am going to let you guys decide how to fulfil this request, clearly you have a better idea of how it should work.

I don't have a strong enough view on it for my use cases.

**Comment by tmiw** [comment]
> Not quite: If checkbox off then select from list exactly as now - no change. On turning on checkbox leave list alone (maybe grey it out) and track current band, whether from rig (read only) or from pull down in main window. i.e. whatever band corresponds to the displayed frequency being reported. On unchecking the checkbox un-grey the reporter band selector and return to the originally selected band in the reporter list.

Graying it out sounds reasonable. It might still be a good idea to have the drop-down update on its own based on the frequency set in the main window as another indication that it is indeed tracking the band; I could see people getting confused if they have both the web version and the internal version open at the same time otherwise.

> Possibly yes, but maybe replace 'current band' with 'auto [X]' and when auto checked, grey out the selector?

[current band] is supposed to be the drop-down list and the [X] is for "Filter tracks frequency" (or "auto"). Sorry for the confusion!

**Comment by barjac** [comment]
> > Not quite: If checkbox off then select from list exactly as now - no change. On turning on checkbox leave list alone (maybe grey it out) and track current band, whether from rig (read only) or from pull down in main window. i.e. whatever band corresponds to the displayed frequency being reported. On unchecking the checkbox un-grey the reporter band selector and return to the originally selected band in the reporter list.
> 
> Graying it out sounds reasonable. It might still be a good idea to have the drop-down update on its own based on the frequency set in the main window as another indication that it is indeed tracking the band; I could see people getting confused if they have both the web version and the internal version open at the same time otherwise.

I don't like the idea of 'auto' changing the dropdown at all. Just grey out the dropdown but remember it's band for when auto is unchecked.
If I have the list set to ALL and check 'auto' while in qso on a band it would be nice to just un-check auto occasionally to see all bands or a specific band that I want to monitor.

I don't see how there would be confusion if the selector is greyed but still readable.

> 
> > Possibly yes, but maybe replace 'current band' with 'auto [X]' and when auto checked, grey out the selector?
> 
> [current band] is supposed to be the drop-down list and the [X] is for "Filter tracks frequency" (or "auto"). Sorry for the confusion!

Ah OK, as long as the 'auto' band does not overwrite the previously selected band (before auto was checked) so that on un-checking auto the previously selected returns. That would be OK, although I would still prefer to see what (greyed) band the selector has set while using auto. The reporter frequency shows what is being reported and filtered when auto is set so why show the same thing twice?

**Comment by tmiw** [comment]
See https://github.com/drowe67/freedv-gui/pull/534 for initial implementation.

**Comment by barjac** [comment]
> See #534 for initial implementation.

Perfect! Thanks again Mooneer :)
