### ISSUE TITLE
Allow Internal reporter to run when not reporting

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#538]
This was fixed but is now broken in 1.9.2

_Originally posted by @barjac in https://github.com/drowe67/freedv-gui/issues/527#issuecomment-1722254849_

**Comment by tmiw** [comment]
No need to open a new issue, the existing one can be reopened.

**Comment by barjac** [comment]
I could see no option to re-open it.

**Comment by tmiw** [comment]
> I could see no option to re-open it.

I thought anyone could to it. Maybe it's just something that project members can do? /shrug
