### ISSUE TITLE
Option to change internal reporter Transmitting and Receiving colours in settings.

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#541]
I have had a report today from an elderly user who struggles to read the coloured highlighted lines in the internal reporter.

It's nothing to do with colour blindness, just lack of contrast as I understand it.
If an option was available to maybe select paler colours (something like the web version) then it would help.

He finds black and white as foreground and background, or flipped, readable but not the heavily saturated coloured backgrounds.

A lot of this can be down to different operating systems and monitors, so some user control could be beneficial for many users myself included.

Any other thoughts on this?

**Comment by tmiw** [comment]
See https://github.com/drowe67/freedv-gui/pull/545 :)
