### ISSUE TITLE
File->On Top does not seem to do anything

### ISSUE THREAD

**Issue by Tyrbiter** [drowe67/freedv-gui#546]
As above, tried to get main window on top of reporter window. Selecting this menu entry does nothing and there is no indication it is active.

**Comment by barjac** [comment]
It does actually ;)
It toggles the FreeDV windows (main and reporter) so that other application windows cannot cover them.
It does not affect the relationship between the Main and Reporter (child?) windows which is what you were looking for.

**Comment by tmiw** [comment]
What @barjac said. The name of this menu item could be worded better, though. Or is there even a need for it anyway given that you can do it via your window manager? Suggestions would be good.

**Comment by Tyrbiter** [comment]
OK, well the answer is that using GNOME Wayland desktop in Fedora 38, On Top from the freedv-gui menu does not work, but the window manager setting does. Once selected in the WM, the reporter window still overlays the main window, this may be by design.

This could be as a result of Fedora being on the Wayland bleeding edge, there are other oddities but eventually these will be sorted out. The X Window System is an old and complex thing and replacing it with newer designs with equivalent functionality is non-trivial.

**Comment by tmiw** [comment]
Seeing this on Ubuntu 22.04 as well. Unfortunately I'm not sure why as it seems to happen regardless of whether I'm using wxWidgets 3.0 or 3.2 (not to mention that it seems to work on macOS and presumably Windows). I'm hesitant to include OS-specific code but since the window manager control for this seems to work, maybe we can hide the "On Top" option in FreeDV on Linux but keep it available for other platforms?

**Comment by barjac** [comment]
TBH it's not a feature that I recall seeing built into a project before, but then I don't go looking as I would always use the WM for that.

**Comment by Tyrbiter** [comment]
I wouldn't mind if @tmiw hides the menu entry in Linux, but I don't know if it will have universal effect.

Linux users have many and varied DEs and WMs, other systems don't so they tend to be a bit more deterministic.

My reason for trying this is that the reporter window overlays the main window all the time as arranged on my screen, being able to choose the Z-order is useful to me but perhaps @barjac prefers it to be fixed.

There may be ways of controlling this, I cannot simply move the reporter window to a different workspace as all the freedv-gui windows move together.

**Comment by tmiw** [comment]
Yeah, I'm hiding the option in Linux because the GTK project themselves say that it's not reliable (and even removed the ability to do so in GTK4).

More info at https://github.com/drowe67/freedv-gui/pull/549.
