### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by UgoPoddine** [drowe67/freedv-gui#552]
Hello Mooner,

this morning I have updated the freedv-gui on my two RasppberryPI installations, as usual, trying to install [a8f9588].
The first machine runs PI/OS with Linux 5.15 over arm32 : here no issue in updating FreeDV GUI.
The second is more up-to-date : Linux 6.1.21-v8+ #1642 aarch64 GNU/Linux : in this second case I got a blocking error claiming pulseaudio as mandatory  (see below).
On both machines Pulseaudio is not installed and portaudio is used to reach Alsa.

Can you help ?
As usual, thank-you very much to you and of course David for you appreciated effort

73, Ugo
IU1IPB

[...]

-- Using LPCNet from build directory...
-- Finding PulseAudio...
CMake Error at CMakeLists.txt:417 (find_package):
  By not providing "FindPulseAudio.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "PulseAudio", but CMake did not find one.

  Could not find a package configuration file provided by "PulseAudio" with
  any of the following names:

    PulseAudioConfig.cmake
    pulseaudio-config.cmake

  Add the installation prefix of "PulseAudio" to CMAKE_PREFIX_PATH or set
  "PulseAudio_DIR" to a directory containing one of the above files.  If
  "PulseAudio" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by UgoPoddine** [comment]
PS : till a couple of "commits" ago, I had no issues in installing FreeDV-GUi also on the ARM64 machine, than it's something that happened very recently

**Comment by tmiw** [comment]
Use of PortAudio on Linux has been deprecated. However, you can still use either of the following to enable it:

```
./build_linux.sh portaudio
```

or 

```
cmake -DUSE_PULSEAUDIO=0 [other arguments] ..
```

**Comment by UgoPoddine** [comment]
Unfortunately, on the small PIs, Pulseaudio seems to add useless latency.
In any case issue solved  : thank-you to have considered also our needs.
Regards
Ugo
