### ISSUE TITLE
Web reporter band filter ignores transmitting and decoding stations.

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#559]
During a net on 60m I looked at the web reporter with band filter set to 80m to see all the members of the net on 60m displayed!
Seems that it happens no matter which band filter is set.
 
![Screenshot_20231001_105331](https://github.com/drowe67/freedv-gui/assets/1324702/88f65eab-5c2f-4452-9c9e-c378d97685ad)

In the above quickly grabbed screenshot G4ABP was not reporting on the machine actually transmitting so is not shown.

I assume that this is not a feature :)

**Comment by Tyrbiter** [comment]
I've tried a few different filtering settings and I can't duplicate this, but I will confess that activity today has been fairly low.

It's worth noting that you probably ought to do a shift-reload on the page as this will force a reload of all of the page elements and empty any code caches.

**Comment by barjac** [comment]
>It's worth noting that you probably ought to do a shift-reload on the page as this will force a reload of all of the page elements and empty any code caches.

Is that relevant looking at the times of some of the updates?

The very top 20m entry is updated within 1 second of my entry (bottom in blue).

If that were the case then surely the program/script should do it. EBay manages to update auction timing to the second in web browsers, without users having to repeatedly hit CTRL/F5.

I will try to reproduce again.

**Comment by Tyrbiter** [comment]
Perhaps @tmiw can comment on the shift-reload aspect. I simply meant that if for some reason a browser tab has been open for a while (some of mine are months old but get reloaded each time I look at them and my browser version changes regularly) then it may be that it's running a cached version of any embedded code on the page.

I have tried to make this happen when I have seen activity during the last day by changing filtering settings and seeing if displayed stations remain there when they are not on the selected band. So far I have not seen it happen, but I'm one person and not a heavy user of filtering.

And yes, I can see your screen shot. It's clearly something your system did, although I don't know why. I use Firefox and always the latest version (118.0.1 currently). Could that be relevant? I'm not sure it would make much difference but there is so much code in a modern browser that almost anything can change. I think you have an ESR version, which by its nature won't get new bugs but could have some unfixed old bugs.

**Comment by tmiw** [comment]
It was definitely a bug as I was able to duplicate here by commenting out line 1432 of main.cpp and then playing back a previously recorded file (while the website's filter was on a band different than my own). This should now be fixed, though, but you may need to use Shift-F5 to clear cache and download the latest JavaScript.

Anyway, I'll close for now but let me know if it comes back and I'll reopen this issue.

**Comment by barjac** [comment]
OK thanks :)
