### ISSUE TITLE
Decimal point/comma problem with predefined frequencies

### ISSUE THREAD

**Issue by JohBod** [drowe67/freedv-gui#570]
FreeDV version: 1.9.2
OS: Win10, Swedish (which uses comma as decimal separator)

The predefined frequencies in the "Report Frequency" drop-down list are all red. This happens because they have decimal points instead of decimal commas. Selecting a red frequency from the list results in reporting the MHz digits correctly but all the decimals become zero e.g. 14.2360 becomes 14,0000 in the FreeDV reporter window and 14.0000 on https://qso.freedv.org/.

I was able to temporarily fix the problem by replacing '.' with ',' in all the entries in Tools/Options.../Rig Control/Predefined Frequencies. However, after stopping and restarting FreeDV, the list becomes totally messed up. It looks like all the commas have been replaced by newlines :) See attached screeshot.

73 Johan SM6LKM

![bild](https://github.com/drowe67/freedv-gui/assets/27567970/15ce876b-2514-4185-aad1-c7976f4cb818)

**Comment by Tyrbiter** [comment]
PR #561 resolves this, it will be included in the next release when that is ready.

**Comment by JohBod** [comment]
Where is the frequency list stored? I couldn't find it neither in C:\Users\jbodi\AppData\Roaming nor in the Windows registry.

By the way, the "FreeDV User Manual Oct 13 2023 3a5154d" points to HKEY_CURRENT_USER\SOFTWARE\CODEC2-Project\FreeDV\ which doesn't exist in my PC. Instead I found some FreeDV configuration here HKEY_CURRENT_USER\SOFTWARE\FreeDV\.

73

**Comment by Tyrbiter** [comment]
On my Linux system it's in the .freedv file in my home directory under the:

[Reporting]
...
FrequencyList=
...

key, I'm unfamiliar with the Windows arrangement.

@tmiw will be able to tell you, but the PR I referred to is intended to deal with locale issues where decimal separators and number delimiters are now recognised correctly.

**Comment by tmiw** [comment]
> Where is the frequency list stored? I couldn't find it neither in C:\Users\jbodi\AppData\Roaming nor in the Windows registry.

Yeah, HKEY_CURRENT_USER\SOFTWARE\freedv\Reporting\FrequencyList on Windows. The default for that is "3.6250,3.6430,3.6930,3.6970,5.4035,5.3665,7.1770,14.2360,14.2400,18.1180,21.3130,24.9330,28.3300,28.7200,10489.6400".

I'll update the documentation to reflect the actual Registry location.

**Comment by Tyrbiter** [comment]
The location for Linux is ~/.freedv, the manual says ~/.FreeDV so I suppose that should be edited too :-p

**Comment by tmiw** [comment]
> The location for Linux is ~/.freedv, the manual says ~/.FreeDV so I suppose that should be edited too :-p

Yep. https://github.com/drowe67/freedv-gui/pull/572

**Comment by tmiw** [comment]
I think this is resolved, so closing for now.
