### ISSUE TITLE
Add Play button in main window to replay the last recorded button

### ISSUE THREAD

**Issue by tmiw** [drowe67/freedv-gui#581]
This proposed feature is to make it easier to immediately replay files recorded using the existing Record button. Currently, people have to go to the Tools menu and locate the recorded file in order to play it back.

**Comment by barjac** [comment]
If this is really needed, then whether or not it is implemented, I think that reporting should be inhibited during playing of a recording.

**Comment by barjac** [comment]
Seems not!

![Screenshot_20231114_203718](https://github.com/drowe67/freedv-gui/assets/1324702/14ceb403-c5dc-4ecf-8939-938ee9697e4c)

**Comment by barjac** [comment]
Settings:

![Screenshot_20231114_204922](https://github.com/drowe67/freedv-gui/assets/1324702/22b30c5a-6990-40f2-ab71-5f6f8a568631)

**Comment by tmiw** [comment]
> Seems not!

Oh, you'll still show up on FreeDV Reporter, just that you won't be reporting that you heard yourself. Which it doesn't look like it did from the screenshot you posted?

**Comment by barjac** [comment]
That is the problem - if I am listening to a recording I don't want to be seen on the reporter as I am not listening on the air. Not a big issue and I don't want to hijack this issue. It just seemed wrong that it did not inhibit the reporting while playing a local file.:)

**Comment by tmiw** [comment]
> That is the problem - if I am listening to a recording I don't want to be seen on the reporter as I am not listening on the air. Not a big issue and I don't want to hijack this thread. It just seemed wrong that it did not inhibit the reporting while playing a local file. :)

Makes sense. Since it does seem to be pretty low priority we can consider it more fully at a later date for sure.

**Comment by tmiw** [comment]
I forget who originally wanted this but I'm going to close as it should go through the existing feature request process.
