### ISSUE TITLE
Option to allow Internal Reporter to filter on current frequency.

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#587]
Currently the reporter can filter on the band in which the current frequency is operating.

This works well but when a net is operating on a specific frequency in a band and other stations around the world are using the same band on different frequencies the display becomes cluttered.

This enhancement request is to optionally allow tighter control of the filter down to maybe the current frequency +/- 250Hz.

Maybe the 'Track current frequency' box could be replaced with 'Track band' and a new check box for 'Track frequency' added to track exact frequency?

**Comment by tmiw** [comment]
Out of curiosity, have you tried sorting on the current frequency? I wonder if that (along with the current band filter) would help organize things. If so, perhaps the solution would be to allowing sort by multiple columns at once?

**Comment by barjac** [comment]
> Out of curiosity, have you tried sorting on the current frequency?

No I use the Frequency tracker (badly named in hindsight as it tracks current band not frequency) and this is what I was doing on 80m on Sunday during the net. There was what appeared to be a small Japanese net on the band at the same time.
I sort by last transmitted so the list is in order, but when other stations transmit who are not in the net the list gets confusing.

> I wonder if that (along with the current band filter) would help organize things. If so, perhaps the solution would be to allowing sort by multiple columns at once?

Yes I have considered requesting multiple sorts which could be useful, however in this case I think that a tighter filter would be more appropriate to limit the stations in the reporter to only those on the net frequency.

**Comment by tmiw** [comment]
See https://github.com/drowe67/freedv-gui/pull/596 :)
