### ISSUE TITLE
Repeatedly asking Microphone Access Permission on MacOS

### ISSUE THREAD

**Issue by JohnN6** [drowe67/freedv-gui#597]
FreeDV (GUI 1.9.4) repeatedly ( usually 9 times ) asks for the same permission to access the microphone when running on an Apple M1 using MacOS Sonoma 14.0

After pressing OK nine times, no further requests are made.

John N G7LTQ

**Comment by tmiw** [comment]
As a workaround, try executing FreeDV from Terminal, i.e.

```
$ /Applications/FreeDV.app/Contents/MacOS/FreeDV
```

Anyway, I'm seeing this on my M1 as well and initially thought that this was a Sonoma bug, but unfortunately I'm not seeing this with any other apps that use the microphone (so far, I've tested with Audacity and Discord). I did do a test this morning where I codesigned the application with an entitlement that allows microphone usage and that seemed to fix the problem, but I need to do more testing to see if that's actually the fix. If that is indeed the fix, that basically means that codesigning is now mandatory and we'll have to adjust the builds accordingly.

**Comment by JohnN6** [comment]
Thanks for the reply.  Just to report back that running from Terminal requires just one permission with the message
"“Terminal.app” would like to access the microphone.”

This is not a big deal for me, I just thought it useful to report what seemed a bug.

I am surprised if it is a CodeSigning issue - I though CodeSigning and Notarisation has not changed for some time.

I know that the Sandbox system has changed with Sonoma; there was an Apple security update I saw which said :
	App Sandbox now associates your macOS app with its sandbox container using its code signature. The operating system asks the person using your app to grant permission if it tries to access a sandbox container associated with a different app. For more information, see https://developer.apple.com/documentation/security/app_sandbox/accessing_files_from_the_macos_app_sandbox.

Don’t worry too much about me as I am still having fun with FreeDV. 


John N.
G7LTQ/AG7VS

**Comment by tmiw** [comment]
> I know that the Sandbox system has changed with Sonoma

I read more about App Sandbox and it didn't sound like it would affect microphone permissions, but I wouldn't be surprised if it did. 

Regardless, it looks like "ad-hoc" signing resolves the issue as well, so we may be able to put off getting a developer account for a bit longer. Just need to change the CMake scripts to run the `codesign` tool (and include the needed entitlements).

**Comment by tmiw** [comment]
I updated the build process to ad-hoc sign the binary since that does seem to solve the problem. 1.9.5 should hopefully have a binary that works better, but in the meantime the Terminal workaround works.
