### ISSUE TITLE
Add new 'Msg' column to reporter.

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#602]
This is a request for a new 3 char wide column in the internal reporter to display up to any 3 ASCII characters.

A 3 character 'Msg' entry box in the reporter bottom bar could be used by any station to have the characters display on their reporter line.

Groups could decide on the content. Some may wish to use Q codes, other CW shorthand or even texting abbreviations or all of the above. 

This could make complex hard wired features as being discussed currently in PR#599 unnecessary.

e.g.:
In a net where someone has to leave urgently they could enter 'g2g' or 'QRT'.
Someone receiving via a web SDR could use 'WRX'.
One member of a group could ask what is my signal strength like? All the others could easily type in "S9+" etc. to give an instant report.
BRK could be very handy if used with care :)

The possibilities are endless and for just a 3 character width field it could be very useful.

I mentioned this idea in the UK net today and it was met with enthusiasm by all stations.

Not sure if this is possible to implement, but if it can then with a 5 second update cycle messages would be adequately fast.

**Comment by barjac** [comment]
More thoughts:
On modem start the Msg could default to a setting in the reporting config settings which itself normally defaults to blank.
This would allow for a persisting Msg e.g. 'WRX' to be set but overridden by any manual entry.

The entry box could have a context menu showing the most recently used to pick from.

Some form of Msg notification could be added. e.g. When a new Msg is received the line changes colour for a few seconds.

**Comment by tmiw** [comment]
This would be sent out only on the Internet, right? Why only three characters in that case?

**Comment by tmiw** [comment]
Hi @barjac! During the Project Leadership Team meeting yesterday, we decided on a new process for requesting feature enhancements. Can you provide the following if possible?

1. How many people want the feature? Please supply contacts details for at least 3 of them.
2. Is this a feature for FreeDV or Codec 2?
    a. If for FreeDV: How will it help enhance HF Digital Voice for Amateur radio?
    b. If for Codec2: How will it enhance open source speech coding?
3. Is this a feature for UHF or VHF? If so please talk to [M17](https://m17project.org/), rather than FreeDV.
4. Does the feature relate to [deprecated](https://github.com/drowe67/codec2#old-code-and-deprecated-features) code that will be deleted in the near future?
5. Is the feature a port to a [non C99 compatible](https://github.com/drowe67/codec2#ports-to-non-c99-compilers) compiler? We have standardized on C99.
6. Is the feature legal for Amateur Radio worldwide? Export Control regulations in many countries limit speech coding to a minimum of 700 bit/s and forbids encryption.
7. Your feature will take effort to implement. If the FreeDV developers work on your feature they won’t be doing other important work on the project. What help can you give in implementing/documenting/testing/supporting the feature?
8. It takes effort from the FreeDV developers to maintain and support features. What help can you give in maintaining/supporting/documenting the feature in the next 1-5 years?

**Comment by barjac** [comment]
> Hi @barjac! During the Project Leadership Team meeting yesterday, we decided on a new process for requesting feature enhancements. Can you provide the following if possible?

That seems like a good idea. I saw a comment recently which was pointing in this direction.
I think that alongside the core coding and decoding work on which this mode is built, in order to build a solid user base a really usable GUI is needed.
I appreciate that to the core codec developers, the GUI is fairly mundane and inconsequential. However without an expanding user base the mode will not gain in popularity and without the features requested by users they will drift away.
One single user may have a brilliant idea, which later becomes indispensable. 
Just food for thought ;)

> 
>     1. How many people want the feature? Please supply contacts details for at least 3 of them.

The regular members of the daily 60m net were all enthusiastic about this feature when I described it on the air as it will solve many issues that we regularly face.

G4MKT(me) G4ABP G6FLH GW8LJJ GW3OAJ M0SSN (and G8SEZ gave a '+1' up this page)  :)

I won't provide any contact details here without their permission but I'm sure the usual searches will find them.
Most don't have github accounts so commenting here is not something that they would be inclined to do.

> 
>     2. Is this a feature for FreeDV or Codec 2?

FreeDV-GUI Internal Reporter

>        a. If for FreeDV: How will it help enhance HF Digital Voice for Amateur radio?

By making the UK nets run much smoother, thus enhancing the perception of the mode in general.
The RSGB News on 80m attracts new and potential FreeDV users at home and in Europe who need initial test signals and encouragement. This feature will allow them to easily indicate their intention or not to join the post news net via the reporter, without calling in. I could go on, but many other uses for this enhancement have already been discussed and I'm sure more would follow once implemented.
Users on different continents would find their own uses to suit their needs. It would be freeform avoiding lots of potential future requests for specific hard coded features.

>        b. If for Codec2: How will it enhance open source speech coding?

n/a

> 
>     3. Is this a feature for UHF or VHF? If so please talk to [M17](https://m17project.org/), rather than FreeDV.

n/a

> 
>     4. Does the feature relate to [deprecated](https://github.com/drowe67/codec2#old-code-and-deprecated-features) code that will be deleted in the near future?

No

> 
>     5. Is the feature a port to a [non C99 compatible](https://github.com/drowe67/codec2#ports-to-non-c99-compilers) compiler? We have standardized on C99.

No 

>     6. Is the feature legal for Amateur Radio worldwide? Export Control regulations in many countries limit speech coding to a minimum of 700 bit/s and forbids encryption.

n/a
 
>     7. Your feature will take effort to implement. If the FreeDV developers work on your feature they won’t be doing other important work on the project. What help can you give in implementing/documenting/testing/supporting the feature?

Lots of testing almost daily in the UK 60m net, which will demonstrate to listeners and other users the way to use this feature to best effect.

>     8. It takes effort from the FreeDV developers to maintain and support features. What help can you give in maintaining/supporting/documenting the feature in the next 1-5 years?

I appreciate the work involved in software development having been involved to some degree for the last 35 years. Now I am a user and must thank all the team for your efforts :)

I maintain the freedv package amongst others for Mageia (Linux) and intend to keep testing and reporting bugs as needed.
Now that I use freedv myself I intend to backport the major development versions from time to time for users of the stable Mageia release to test.
We are not a rolling release so packages in the stable release are updated only for bug fixes and security issues. This can be a problem for projects like freedv-gui which has been developing rapidly.
Adding the latest development versions in our backports repository (subject to QA) will allow Mageia users to keep up with the latest developments without compromising stability.

**Comment by tmiw** [comment]
Thanks for that info! I'll forward it along to the rest of the leadership team for further discussion.

**Comment by barjac** [comment]
Further to the above there have been several recent instances during our daily UK nets where this would have been very useful. One point mentioned was that some visual (or audible ping) notification would be needed to make users aware that a new 'Msg' had been entered in the 'currently displayed' reports.
Thanks for considering this and for your previous excellent work on our other suggestions that are now enhancing FreeDV :)

**Comment by barjac** [comment]
Just curious, how often are these PLT decision making discussions?

**Comment by tmiw** [comment]
> Just curious, how often are these PLT decision making discussions?

Second Friday of every month, give or take a bit.

**Comment by tmiw** [comment]
This was approved by the PLT during our meeting yesterday. Changed tags accordingly and will work on this when time permits.

**Comment by barjac** [comment]
Thanks :)

**Comment by tmiw** [comment]
> Thanks :)

See https://github.com/drowe67/freedv-gui/pull/620 :)
