### ISSUE TITLE
libwxgtk3.0-gtk3-dev missing in BookWorm

### ISSUE THREAD

**Issue by UgoPoddine** [drowe67/freedv-gui#603]
Hello Mooner,

just trying to install FreeDV on ARM64 PiOS on Bookworm, but now libwxgtk3.0-gtk3-dev is no more available.
I suppose that I can not replace it simply with libwxgtk3.2-dev, is't it ?

Thank-you, also to David.
My best regards
Ugo

**Comment by tmiw** [comment]
3.2 should work without any modifications. In fact, we use 3.2 for the Windows and macOS builds. Let me know how that goes!

**Comment by tmiw** [comment]
Any luck on this?

**Comment by tmiw** [comment]
Closing for now. Let me know if this is still an issue and I can reopen.
