### ISSUE TITLE
1.9.5 'RX Only' can not be turned on and off without stopping the modem.

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#612]
When for example leaving a net and recording it, it is not possible to switch to 'RX Only' to indicate that you are no longer taking an active part without stopping the modem and the recording.

The recording is not really central to this, but it is impacted.

I thought that this was possible previously but I can't check just now.

I maybe did stop the modem in the past, however this time the recording would have been interrupted so I reluctantly left the system 'Receiving'.

Of course this would not matter if issue #602 was implemented as I would just put up 'REC' or a similar 'Msg' to indicate that I was only recording to the others in the group.

**Comment by tmiw** [comment]
Yeah, this was specifically disabled for the most recent release as it had some other possibly negative side effects (such as forcing a disconnect and then an immediate reconnect whenever you clicked OK in Tools->Options). I'd recommend creating a feature request for the ability to dynamically switch RX Only status for further review.

**Comment by barjac** [comment]
OK will do, however the need for this is really dependant on #602 which could serve the same purpose and many more.

**Comment by tmiw** [comment]
Going to close this since #602 was in fact implemented. Let me know if this needs to be reopened.
