### ISSUE TITLE
Reporter showing obsolete reports

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#616]
![Screenshot_20231206_095953](https://github.com/drowe67/freedv-gui/assets/1324702/6e6f61ee-e50e-4fa3-a28c-d74072c31c6d)

In the above screenshot just taken there are 7 entries.

However there are only 3 active stations at the top (sorted on last update).

The fourth down has not updated for over 7 hours and the remainder for days and even weeks.

These obsolete reports are cluttering the reporter for no good reason that I can think of.

Why are they still there if they are no longer reporting?

Can they be removed if they fail to report for maybe 15mins?

**Comment by Tyrbiter** [comment]
All of them are running older versions of freedv, it should improve if people used 1.9.5 or later. The reporting logic changed at this version.

**Comment by barjac** [comment]
Ah! OK
