### ISSUE TITLE
Feature request: Add CAT frequency control.

### ISSUE THREAD

**Issue by Supermagnum** [drowe67/freedv-gui#62]
It is not possible to control a radios frequency/VFO's via CAT control.

I think that  4 Steps up and down in Khz from these frequencies as required by the bandwidth of the selected mode with reasonable spacing should be a nice feature. 

The frequencies listed serves as "home frequency" it should be possible to "step" up or down from those.

I suggest these, they are directly from the IARU Region 1 bandplans :
3630 kHz - Digital Voice Centre of Activity
7070 kHz - Digital Voice Centre of Activity
10140 kHz - In the digimodes window.
14130 kHz - Digital Voice Centre of Activity
18150 kHz - Digital Voice Centre of Activity
21180 kHz - Digital Voice Centre of Activity
24960 kHz - Digital Voice Centre of Activity
28330 kHz - Digital Voice Centre of Activity
50.630 Digital Voice (DV) calling
70.3125 or
70.3250

It should also follow the proper USB or LSB rules.

**Comment by mdblack98** [comment]
Remember that 
10.136 FT8
7.074 FT8

**Comment by Supermagnum** [comment]
> Remember that
> 10.136 FT8
> 7.074 FT8

Those should of course not be available.

**Comment by drowe67** [comment]
Re this request:
1. Why not just tune manually?
1. What current problem does it solve?

**Comment by hobbes1069** [comment]
I agree, unlike digital modes such as FT8 (et. al.), DV is considered "phone". If you want cat controls and memories, that can easily be configured with software such as HRD and flrig.

**Comment by Supermagnum** [comment]
> I agree, unlike digital modes such as FT8 (et. al.), DV is considered "phone". If you want cat controls and memories, that can easily be configured with software such as HRD and flrig.

Flrig and FreeDV does not play along, at least not on Linux.
It causes a software collision .
I am not the only one who has the same issue.
Please look at:
https://www.reddit.com/r/linuxmint/comments/ixfs7d/hamlib_communication_collision_using_freedv_and/?utm_medium=android_app&utm_source=share

**Comment by drowe67** [comment]
I am uncomfortable about expanding the scope of FreeDV further - it's mission is digital voice and I would like to stay as close to just that as possible.   As @hobbes1069 suggests - if other applications exist for tuning then lets delegate that feature to them.  

Perhaps the solution here (and aim of this ticket) is work out how to make other apps and FreeDV work together when using Hamlib (if that's possible).  

@Supermagnum - can you please research that?  If you're not comfortable with the C coding perhaps you can work out the design issues and test/demonstrate two applications using Hamlib using existing tools.

**Comment by Supermagnum** [comment]
> I am uncomfortable about expanding the scope of FreeDV further - it's mission is digital voice and I would like to stay as close to just that as possible. As @hobbes1069 suggests - if other applications exist for tuning then lets delegate that feature to them.
> 
> Perhaps the solution here (and aim of this ticket) is work out how to make other apps and FreeDV work together when using Hamlib (if that's possible).
> 
That is a viable option.

> @Supermagnum - can you please research that? If you're not comfortable with the C coding perhaps you can work out the design issues and test/demonstrate two applications using Hamlib using existing tools.

I have zero programming skills, but I have the exact same error message on the newest Linux Mint. Perhaps it is hamlib that is the source of this problem as I don't know if it is able to handle simultaneous connections. 

The rig is a FT-991 ( original ) Works just fine with WJST-X, I have tried the exact same settings with FreeDV and Flrig.
That causes the mentioned communication collision. 

I have opened a issue here:
https://github.com/Hamlib/Hamlib/issues/489
Perhaps they can help.

FYI: I still think that adding international CAT frequency control in FreeDV is a cleaner solution than using a external program for that.

**Comment by hobbes1069** [comment]
Ahh. I have a solution there. You can change the hamlib rig to "FLRig FLRig" and hamlib will talk to Flrig instead. You'll get a lot more control of your radio with the only caveat that Flrig needs to be running before you start FreeDV.

**Comment by drowemyriota** [comment]
@Supermagnum does the response from https://github.com/Hamlib/Hamlib/issues/489 or @hobbes1069 resolve the issue for you?

If so can you please write some content for the FreeDV User Manual with instructions to assist others?

Not sure if we need to upgrade our Hamlib version?

**Comment by drowe67** [comment]
Closing this (1) it's outside the scope of FreeDV and (2) as third party solutions appear to be available, e.g. https://github.com/Hamlib/Hamlib/issues/489.  Happy to re-open if there is anything we need to add to FreeDV to facilitate 3rd party solutions (e.g. update Hamlib).
