### ISSUE TITLE
Callsign list opens downwards and often ends up off screen, making it unreadable.

### ISSUE THREAD

**Issue by Tyrbiter** [drowe67/freedv-gui#629]
In topFrame.cpp around the line 574->line 596 area, the callsign list generation code causes the list to always open downwards and it will disappear off the bottom of the window which can be at the lower edge of the usable screen.

It would be better if it behaved like the Report Freq. list which seems to limit its lower edge to the bottom of the freedv main window when it opens.

**Comment by tmiw** [comment]
It doesn't look like this behavior can be changed, unfortunately. I did find out that if you maximize the window, the callsign list will open upward. Maybe that's okay for now?

**Comment by Tyrbiter** [comment]
Yes, I think I will just move freedv to a new workspace. I compared the code and couldn't see much difference between the two drop downs. wxWidgets is good, but not perfect. I will look into making a feature request :)
