### ISSUE TITLE
Feature Request: expanded frequency offset range

### ISSUE THREAD

**Issue by mccla5214** [drowe67/freedv-gui#63]
Is it possible using the pilot one on the receive side to either have the software center on the pilot or using frequency control through CAT have the software shift the radio to center the pilot. Asking this for use on EME and satellite.

**Comment by DG9BFC** [comment]
what about a "tuning aid" ?? a red arrow pointing up or down depending what direction you have to tune by hand ... sure a cat control (via hamlib) is nice (and then we have also the qrg for psk reporter) ... but i think a manual tuning helper (with arrow point up down and a green box "locked" when centered) ... would be a nice add on for those users that have no cat and use a "normal rig" with audio in out and ptt ... not a modern rig with builtin usb soundcard and cat via usb
so ... another feature request ... show mistuneing with an arrow point up down :-)

**Comment by mccla5214** [comment]
I don't understand why it doesn't use a pilot tone in the carrier to lock
the receiving station on frequency so you don't have to fine tune it. Just
get close enough to get a lock and not worry about it.

**Comment by drowemyriota** [comment]
@mccla5214 all of the modems automatically determine the frequency offset of the received signals within a small range (e.g. +/- 60Hz for 700D).  The range varies across modes, it's a tough part of modem design.  To handle satellite Doppler freq offset ranges would be a significant amount of work.

There is no need to fine tune in any modes - the modem tracks small frequency offsets.
