### ISSUE TITLE
1.9.6 Callsign column of reporter truncated in Windows10

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#634]
I am reporting this on behalf of other users who use Win10 (I don't have any Win machines).

The following is what I have discovered from several users during on-air discussions.

In FreeDV 1.9.6 the leftmost reporter column, 'Callsign' acts as though the column width is set to be only a few characters wide such that only the call prefixes are visible.

The column can be dragged wider but reverts to narrow again when the table is refreshed for any reason, such as a filter change.

**Comment by tmiw** [comment]
Fixed as of https://github.com/drowe67/freedv-gui/pull/638.
