### ISSUE TITLE
1.9.6 Reporter table flicker when using 'Track' with 'freq'

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#635]
When using 'Track' with 'freq' set, the whole reporter table is refreshing on each 'Last update' update, maybe only the local user's update but not certain as some updates can display almost simultaneously.

The flicker effect happens about 150ms before the time changes in the user's 'Last update'. 

This is causing an annoying flicker, most noticeable when colour is showing, as it causes the colours to be extinguished for several seconds each time.

Tested also in master at #a8f58

/OT
A secondary effect of this relates to issue #634, as the refresh triggers the truncation of the callsign column in Win10.

**Comment by tmiw** [comment]
Should be fixed in https://github.com/drowe67/freedv-gui/pull/637 now.
