### ISSUE TITLE
Minor things in current git

### ISSUE THREAD

**Issue by Tyrbiter** [drowe67/freedv-gui#639]
Just a quick report of some very minor things.

In USER_MANUAL.html there is one instance of 'applicaton' when it should read 'application'.

In the filter dialog, for some reason the Default button moves slightly when selecting the Speaker Output equaliser tab for the first time. This is with neither equaliser enabled. Repeatable if window is closed and reopened, but not when switching tabs again.

**Comment by tmiw** [comment]
Documentation fixes are in https://github.com/drowe67/freedv-gui/pull/640.

As for the filter dialog, I'm not able to reproduce on Ubuntu 22.04 or openSUSE so far. Could it be something that only happens on certain screen sizes/resolutions?

**Comment by Tyrbiter** [comment]
The sequence is that the Default button moves a few pixels to the right as the Speaker Out Equalizer tab is selected, but only once, returning to the Mic In tab it stays put. For some bizarre reason the initial window paint has the button in the wrong place, but not on subsequent tab swaps. Only when the window is opened again.

This is using 1920x1080 screen resolution.

It's a really minor thing, I did a comparison of the code in the dlg_options.cpp sections that seemed relevant, couldn't see anything obvious. Probably a wxWidgets thing.

**Comment by tmiw** [comment]
#641 should resolve this. I had to add a similar workaround to what's done on the main window and I figured I'd also tweak some other stuff to make the dialog better handle being resized in general.

**Comment by barjac** [comment]
The Distance column label should read "km" not "KM" (kelvin mega?) when that option is selected. :)

**Comment by tmiw** [comment]
> #641

https://github.com/drowe67/freedv-gui/pull/642 :)
