### ISSUE TITLE
Minor enhancement to reporter message entry - discussion

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#645]
At present any one off 'throw away' comments that are sent are added to the 'Saved' list, filling it up with 'never again to be needed' items. Also 10 items is not currently enough, maybe 20 would be?

One possible simple solution:
Use CTRL/'Set' to add to the list and use just 'Set' to send without saving.

My initial idea for the list was that it would contain the 'most used' items in popularity order and now realize that the 'most recently used' was the wrong terminology.

Maybe:
If the last 200 or so messages were logged and sorted into most used order then the top 10+ could appear in the list. When the log reaches max size then delete everything that only appears once.
(there is a bug in that idea but it's food for thought :)

**Comment by tmiw** [comment]
Maybe I haven't been on the air much recently, but how quickly do messages fall off the list for you guys where it should be >10 items?

**Comment by barjac** [comment]
> Maybe I haven't been on the air much recently, but how quickly do messages fall off the list for you guys where it should be >10 items?

It's that any commonly used but not every day messages that I would like to stay in the list get pushed off after a few days.

I think the 10 items should maybe increase to 15 but if the list is too long then without some order to it visually searching gets slower, so it less convenient to use.

We need to be able to be selective about what is saved to the list, so I think if CTRL/Set were introduced to save then it would be enough.
I suppose that hitting 'CTRL/Set' if only 'Set' had been used would allow for a change of mind and save the current message anyway without further code change.

OR...

Another possibility would be a 'search while typing' feature where any matching previously used texts are listed for selection, each new character added narrowing the options.
The previous messages would be stored in a file which could be size limited to something reasonable like maybe 10k or so.

**Comment by Tyrbiter** [comment]
Maybe a temporary/permanent checkbox next to the set button? But obviously less wordy :)

**Comment by tmiw** [comment]
Maybe left-clicking Set doesn't actually save to the list, but if you right-click there's a "Save" option that pops up? (similar to the behavior on the main window)

**Comment by Tyrbiter** [comment]
Sounds like a plan to me.

**Comment by tmiw** [comment]
> Sounds like a plan to me.

https://github.com/drowe67/freedv-gui/pull/647

**Comment by barjac** [comment]
If I send a message to the server then select another to delete and use the 'Clear' context menu to delete it, the message in use on the server is also deleted :(

**Comment by tmiw** [comment]
> If I send a message to the server then select another to delete and use the 'Clear' context menu to delete it, the message in use is also removed from the server. :(
> 
> Also now that 'Send' (tooltip still says 'Set' BTW) is always needed, maybe the 'Send' context menu could have a 'Save only' option so messages may be saved without sending.

There should now be a Save Only right-click menu option in that PR.
