### ISSUE TITLE
Some stations are not updating reporter during transmit

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#657]
I have been seeing this for some time while I was using a dev version and others were using 1.9.6.

Now that all stations concerned are using 1.9.7 I am still seeing this.

The only common denominator that I can see so far is that the stations who only update during receive are running under Windows.

I only use Linux and my updates continue during transmit and receive. My internet connection is over 4G not land line BTW.

As a test to try to rule out RF issues with the network connection I got one station to drop to very low power yesterday and it made no difference. I will ask them to make a test with no output RF at all to be certain.

**Comment by tmiw** [comment]
Do you know what they're using for interface (i.e. Hamlib vs serial PTT)? 

Additionally, some radios also don't respond to CAT commands while in transmit (other than the command to stop transmitting). The FT-817 is one of those off the top of my head.

**Comment by barjac** [comment]
I have tried asking but with long overs and several in the net it's hard to get meaningful answers ;\ I will keep trying.

The stations concerned are showing red during TX so the update at the start of TX is sent.

I don't understand why the type of PTT control would affect subsequent updates being sent.

If the program cannot access the rig via hamlib (other than to stop TX) during TX then I assume it refuses to send an update, which does make sense as the data sent could not be current at that time. However if hamlib were not being used at all, then would updates continue during TX I wonder?

**Comment by tmiw** [comment]
> If the program cannot access the rig via hamlib (other than to stop TX) during TX then I assume it refuses to send an update, which does make sense as the data sent could not be current at that time. However if hamlib were not being used at all, then would updates continue during TX I wonder?

Based on the code that's there now, there's a timer that fires every 5 or so seconds that will retrieve the frequency/mode if it's configured to (i.e. hamlib or OmniRig are enabled). If it's able to successfully retrieve that info, then that's what triggers the reporting update. In short, if serial PTT is used (or no PTT at all), there won't be any updates during TX.

**Comment by barjac** [comment]
OK thanks that explains it.
I think this may be closed then as neither station is using Hamlib from what I can gather.
