### ISSUE TITLE
Example request: add 2400B sample?

### ISSUE THREAD

**Issue by jimt** [drowe67/freedv-gui#66]
Does it make sense to add a **2400B** sample to the `wav` directory for completeness?

**Comment by drowe67** [comment]
Sure - would you like to have a go at generating one with the command line tools?  See examples in [README_freedv](https://github.com/drowe67/codec2/blob/master/README_freedv.md). Let me know if you need any help.

**Comment by drowe67** [comment]
@jimt I found a 2400b demo file lying around and committed it here https://github.com/drowe67/freedv-gui/pull/64/commits/69973a301f8bdc677bcd791b0fe6503fa14344af

**Comment by jimt** [comment]
Sounds good.  Thanks!

I was toying with the idea of building the samples as part of the `build_*.sh` scripts since they download and rebuild a copy of codec2... but probably better to have the known good sample despite the additional filesize.
