### ISSUE TITLE
Click on PTT does not always work - seems to need a short click/hold.

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#660]
I have been seeing this for several versions, it's a minor issue but does catch me out sometimes. When I think I have dropped transmission, take a sip of tea and then look at the screen I find I am still transmitting!
Could it be be improved so a short click always works?

**Comment by tmiw** [comment]
Could this be some sort of desktop environment issue? I know I've never seen this on macOS and I haven't heard anything from Windows users, either.

**Comment by barjac** [comment]
I would imagine that 90% of Linux users will be using Plasma5 D.E. so I would be surprised if I were the only one seeing this.
Maybe its just that nobody else reported it?
Any ideas on debugging?
Where in the source is this click action detected?
I will try using the space bar instead of the mouse for a while for comparison, although I would expect that the space bar would produce a longer more 'catchable' event than a mouse click.

**Comment by tmiw** [comment]
> I would imagine that 90% of Linux users will be using Plasma5 D.E. so I would be surprised if I were the only one seeing this. Maybe its just that nobody else reported it? Any ideas on debugging? Where in the source is this click action detected? I will try using the space bar instead of the mouse for a while for comparison, although I would expect that the space bar would produce a longer more 'catchable' event than a mouse click.
> 
> This looks promising: https://www.reddit.com/r/kde/comments/10a69pl/mouse_not_registering_clicks_when_done_fast/?rdt=39737

I just tried double-clicking really fast a couple of times in Ubuntu 22.04 (running GNOME) and I seem to be able to consistently bring the app out of transmit. Granted, this is in a VM so it's possible open-vm-tools already adjusted the setting you linked to. Hopefully the adjustments in that link will help you?

**Comment by barjac** [comment]
I am struggling to reproduce this in tests which is partly why I did not report it it sooner. :(

One thing that I have discovered is that if the Reporter window is in focus then using the space bar as the PTT toggle fails and it toggles the last action in that window. e.g. 'Track' ON/OFF.

Maybe the space bar in the reporter should still operate as PTT unless the message text entry is active?

**Comment by Tyrbiter** [comment]
I see something occasionally, where the focused window (after changing workspaces) appears not to have the Stop button (or whichever button is used) active, so one must move the cursor outside the window and back on before the click reaches freedv's logic.

This is using GNOME 43.x Wayland on Fedora 39, but I think it's been around a while. It feels like a wxWidgets thing, I don't remember seeing it with non-wxWidgets applications on other workspaces.

**Comment by tmiw** [comment]
> Maybe the space bar in the reporter should still operate as PTT unless the message text entry is active?

Done: https://github.com/drowe67/freedv-gui/pull/666

> Where in the source is this click action detected? 

Just noticed this question. For PTT, you'll want `MainApp::FilterEvent()` inside ongui.cpp (for the space bar handling) and `MainFrame::OnTogBtnPTT()` (same file) for the mouse click handling.

**Comment by Tyrbiter** [comment]
> Done: #666

@tmiw is on fire today :)

**Comment by Tyrbiter** [comment]
> Any luck on being able to duplicate this again (hopefully more reliably)?

I have not seen anything here, when I did it seemed to be DE/wxWidgets/virtual desktop related and is occasional rather than repeatable.

**Comment by tmiw** [comment]
> > Any luck on being able to duplicate this again (hopefully more reliably)?
> 
> I have not seen anything here, when I did it seemed to be DE/wxWidgets/virtual desktop related and is occasional rather than repeatable.

I briefly searched wxWidgets' issues list and I haven't seen anyone reporting this there, so it's likely some sort of DE issue.

**Comment by barjac** [comment]
> Any luck on being able to duplicate this again (hopefully more reliably)?

No not recently, but all my receent testing has been done running under Cauldron (Mageia 10 dev).

Maybe the cause has been addressed in some updated system lib.

I will close this for now.
