### ISSUE TITLE
Add frequency column to callsign list

### ISSUE THREAD

**Issue by Tyrbiter** [drowe67/freedv-gui#662]
With freedv activity on more bands I think it would be useful for the callsign list to include frequency (or at least band) as it persists across frequency and band changes while the modem is left running.

**Comment by tmiw** [comment]
https://github.com/drowe67/freedv-gui/pull/663

**Comment by barjac** [comment]
> With freedv activity on more bands I think it would be useful for the callsign list to include frequency (or at least band) as it persists across frequency and band changes while the modem is left running.

Could you please expand on what you mean exactly? I don't understand the issue, sorry.

Are you saying that the frequency for a particular callsign may have changed but still reported as being on a previous frequency? If that is the case then surely there is an issue/bug that allows this? Why would another column be needed?

**Comment by tmiw** [comment]
> > With freedv activity on more bands I think it would be useful for the callsign list to include frequency (or at least band) as it persists across frequency and band changes while the modem is left running.
> 
> Could you please expand on what you mean exactly? I don't understand the issue, sorry.
> 
> Are you saying that the frequency for a particular callsign may have changed but still reported as being on a previous frequency? If that is the case then surely there is an issue/bug that allows this? Why would another column be needed?

My interpretation was that an additional column should be added in the drop-down list on the main window to show the frequency the user was on when they heard someone. For example:

![Screenshot 2024-01-20 at 3 23 25 PM](https://github.com/drowe67/freedv-gui/assets/449242/06886b37-86a5-4a63-8bf9-548a7aac32bc)

**Comment by Tyrbiter** [comment]
@tmiw has coded a patch that does what I was asking for, I suppose the only question is if a station changes band will the list overwrite the last entry if it has the same callsign as the top entry? I'm thinking that in some cases the history of what my station hears is quite useful, if a band change erases the previous frequency it's a bit less useful.

Is that clear now @barjac as this takes up no extra space I don't think it messes up smaller displays.

**Comment by tmiw** [comment]
> @tmiw has coded a patch that does what I was asking for, I suppose the only question is if a station changes band will the list overwrite the last entry if it has the same callsign as the top entry

If the user hears someone else and then the first person again, they should get a second entry in the list. But I'll add an additional check so that a duplicate can be added without having to hear someone else first.

**Comment by barjac** [comment]
Ah OK now I understand - not what I was thinking of at all :)

That 'Txt message' is only editable when reporting if off and can contain random text which is usually garbled if the message is long.

IIUC this text is sent via RF along with the voice data, so is unrelated to www reporting, so why the above limitation on editing?

For this use I would expect that it should be limited to callsign only?

**Comment by Tyrbiter** [comment]
That field gets reused for either the original 'unreliable' free-form text or the callsign from the reliable text algorithm that @tmiw devised. Expanding the field to a list is useful as it shows what has been heard in order and copes with band changes if made on the radio as well as when using the drop-down frequency list.

I wonder if the old unreliable method should have a note or tool tip to indicate that it's often a best guess when SNR is a bit low.

**Comment by tmiw** [comment]
> I wonder if the old unreliable method should have a note or tool tip to indicate that it's often a best guess when SNR is a bit low.

https://github.com/drowe67/freedv-gui/pull/665 updates the tooltip accordingly.

**Comment by barjac** [comment]
There is very minor issue when again clicking the down arrow to collapse the list.

It appears to 'select' the whole box turning it blue as well as closing the list. A click outside the box is needed to 'deselect' it.

**Comment by Tyrbiter** [comment]
> There is very minor issue when again clicking the down arrow to collapse the list.
> 
> It appears to 'select' the whole box turning it blue as well as closing the list. A click outside the box is needed to 'deselect' it.

This appears to be another wxWidgets thing, I see it too in freedv, not sure if other applications using wxWidgets are affected.

**Comment by tmiw** [comment]
> > There is very minor issue when again clicking the down arrow to collapse the list.
> > It appears to 'select' the whole box turning it blue as well as closing the list. A click outside the box is needed to 'deselect' it.
> 
> This appears to be another wxWidgets thing, I see it too in freedv, not sure if other applications using wxWidgets are affected.

It might be related to the control that's being used to show that list. Unfortunately I'm not sure there's a way to change that behavior.
