### ISSUE TITLE
Visual C++  Runtime Library

### ISSUE THREAD

**Issue by Roturbo** [drowe67/freedv-gui#667]
Hello,

i have a friend that ask me to report that he is getting error after pressing PTT,
with and without any type of PTT configured.

![WhatsApp Image 2024-01-22 at 21 59 14_3180483d](https://github.com/drowe67/freedv-gui/assets/91867260/a95bef63-7521-4008-b3d9-f790c49bbd96)

I have the same windows version and i don´t have this problem, i do have some big delay or fail
to turn off PTT on V 1.9.7 as already someone reported.

![Image 2024-](https://github.com/drowe67/freedv-gui/assets/91867260/a8c8eacb-a00f-48eb-b98f-b7681dab3eda)

This error was with version 1.9.4, but is the same error with 1.9.7 or 1.9.7.2.

It seams to be a C++ problem, do you have any idea to help solving this ?

He have try older DV version 1.9.1 and also have C++ different problems

![WhatsApp Image 2024-01-22 at 22 01 21_0380912f](https://github.com/drowe67/freedv-gui/assets/91867260/04849e0e-07c1-4b3e-b660-ffade6e36904)

Tanks in advance.

Regards

**Comment by tmiw** [comment]
Are you able to get screenshots of the Tools->Audio Config dialog (both Receive and Transmit tabs) and add them here?

**Comment by Roturbo** [comment]
Ok,, 

here it is.

![1](https://github.com/drowe67/freedv-gui/assets/91867260/ea966c97-278a-482b-84b0-f7238fa2af1e)

this one is ok.

![2 (2)](https://github.com/drowe67/freedv-gui/assets/91867260/5a8c4aae-7182-47fe-830d-310553e70e87)

He correct it and it is working, but the problem was also a microphone MARSGAMING  that only works at 96000,
my friend change to other micro and problem solved.

Many tanks for you replay and help.

Regards

**Comment by Roturbo** [comment]
Solved.

**Comment by tmiw** [comment]
Actually, the way FreeDV treats high sample rate devices isn't great, so I'm going to push a change to improve that. (I have the initial change, just need an actual device that shows up as >48000 in Windows to confirm.)

**Comment by Roturbo** [comment]
Hi,

if you need any test my friend have that Marsgaming mic and he can test it.

You may also code the soft to not save/apply if there is 0 on any sample rates.

Regards

**Comment by Roturbo** [comment]
Hello,

work "perfect" at least with that micro with 96000, no PTT error or any other C++ error.

He have a little low audio compared to other station, but that i think it is the settings 
that need to be adjusted,,, also he was about 1 mile from me with strong signal.


![22](https://github.com/drowe67/freedv-gui/assets/91867260/c849f302-8849-41e2-b269-1d7f4ea72c37)


Tanks for your work, i have one idea about the SNR, but i will open other topic about it later.

Regards

**Comment by tmiw** [comment]
No worries, thanks for your help in testing! I just merged that fix so hopefully fewer people have problems in the future. (I didn't realize so many people used sound devices capable of sample rates >48000. :)
