### ISSUE TITLE
wxWidgets 3.1.4

### ISSUE THREAD

**Issue by drowe67** [drowe67/freedv-gui#67]
https://github.com/drowe67/freedv-gui/pull/64#issuecomment-667903077

**Comment by tmiw** [comment]
Subscribing to this issue as we may need 3.1.4 to fix some macOS UI issues I noticed (namely the UI not properly updating for dark mode). I'll investigate a bit when I get a chance.

**Comment by drowe67** [comment]
@tmiw is this still an open issue on macOS?

**Comment by tmiw** [comment]
@drowe67, nope, I've been building with 3.1.4 for a while now and haven't seen any assertion failures recently. 👍

**Comment by drowe67** [comment]
That's great @tmiw good work :+1:
