### ISSUE TITLE
[BUG]: Stop button greyed out

### ISSUE THREAD

**Issue by Aleziss** [drowe67/freedv-gui#676]
Hello all,

I did install v1.9.7.2 and I noticed that when I start FreeDV, I can't stop it anymore as the stop button is greyed out...

Any ideas on this ?

![image](https://github.com/drowe67/freedv-gui/assets/57082992/c099b2d5-e817-4f5f-a035-9c51071a0c97)

Thank you for the awesome work on FreeDV ! Fun project !

**Comment by Aleziss** [comment]
Update, that situation happened when there is PTT Port configured to a specific COM port that is NOT currently present.

What seems to happend is that FreeDV tries to connect to that PTT Port which never respond, in my case because it was simply not connected to my PC !

When the port is active and properly connected, everything works perfectly. It is ONLY when the device is NOT active that FreeDV has its STOP button greyed out and in order to stop the app, I need to close it completely.

![image](https://github.com/drowe67/freedv-gui/assets/57082992/7141cad5-787c-4424-b094-12f508c91e7a)

**Comment by tmiw** [comment]
I'm still trying to duplicate this on the soon to be 1.9.8 but no luck so far. Can you try [this build](https://www.dropbox.com/scl/fi/7l3hy773h0tf6jy3m8xkc/FreeDV-1.9.8-devel-2024-01-23-74092f75-windows-x86_64.zip?rlkey=mqmjwko923f82790ncylp7yel&dl=0) (generated to help test the fix for another issue) and see if this works better for you?

**Comment by tmiw** [comment]
Closing due to lack of response. 1.9.8 should be out soon so if that ends up not fixing this issue, please feel free to update and I'll reopen this bug.

**Comment by Aleziss** [comment]
Hi Mooneer, sorry for the late reply... life... I will try your version as mine gets stuck if the com port is not active.

**Comment by Aleziss** [comment]
I did test with the dev version and it now reports that the port is not responding and I can now stop. The start button is not greyed out anymore.

**Comment by tmiw** [comment]
> I did test with the dev version and it now reports that the port is not responding and I can now stop. The start button is not greyed out anymore.

Good to hear. Thanks for testing!
