### ISSUE TITLE
Further GUI development - discussion

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#677]
Now that the GUI of both the main program and the reporter are compact and looking neat and clean thanks to great work by Mooneer I have been wondering how difficult it would be to combine the reporter into the main window.

Most users I know arrange the main window to occupy the top half of the screen and fit the reporter below it which involves some window dragging and sizing to achieve.

My ideal arrangement would have the reporter below the existing main window content by default, with an adjustable dividing line between them which could be dragged up and down to give either the main program or the reporter more height as required/desired.

If the reporter were turned off then the main window would get the whole screen.

Any thoughts anyone?

**Comment by tmiw** [comment]
That's actually a significant amount of work for I'm not sure how much gain. Additional feedback from others would be good (and submitting this via the existing feature request template would be good if this is something others want as well).

**Comment by Tyrbiter** [comment]
Currently the reporter windows stays on top of the main window when open, if it could be dropped down the Z-order I would find that more useful.

**Comment by tmiw** [comment]
> Currently the reporter window stays on top of the main window when open, if it could be dropped down the Z-order I would find that more useful.

Played around with this a little bit and haven't found a way to change this behavior yet. I also noticed that the Filter dialog is the same way. Not fully sure why.

BTW I haven't noticed this on any other platform except for Linux, either. /shrug

**Comment by tmiw** [comment]
How about https://github.com/drowe67/freedv-gui/pull/679? That should at least solve the Z ordering issue.

**Comment by tmiw** [comment]
Just merged #679, any other action needed here?

**Comment by barjac** [comment]
> Just merged #679, any other action needed here?

That was a side issue, it does not affect the main suggestion which needs discussion between users to decide on whether or not it needs escalating to a 'new feature request'.

I would suggest leaving this open to allow time for users to consider and become aware of this idea.

**Comment by Tyrbiter** [comment]
I would say that not having the reporter window forced on top allows for different ways of using the whole application. If we are suggesting a different top window configuration then that should be against the background of what freedv-1.9.8 will offer which already has additional flexibility over the current version.

**Comment by barjac** [comment]
> I would say that not having the reporter window forced on top allows for different ways of using the whole application. If we are suggesting a different top window configuration then that should be against the background of what freedv-1.9.8 will offer which already has additional flexibility over the current version.

Yes, I agree that the new configuration that allows the main GUI and the reporter to be minimized to separate task bar items does make a big difference and is much more flexible than the current one.

In light of this I am happy to shelve this idea.  :)
