### ISSUE TITLE
FreeDV 1.9.7.2 crashes with error when Audio output device is not 2-channel stereo

### ISSUE THREAD

**Issue by no1453** [drowe67/freedv-gui#678]
I kept getting a crash on 1.9.7.2 when I clicked "Start" until I reconfigured my audio output device to 2-channel (stereo) from 6-channel (5.1).  Then the program operates normally.   This is on Windows 11 Pro.

As a note, 1.9.6's behavior was simply no sound from the speakers, even though the "To Spkr/Hdphns" tab showed output, when my speakers were configured as 5.1.

**Comment by tmiw** [comment]
This should already be fixed in #668 (title refers to high sample rate devices but there are also changes for devices with more than 2 channels) and will be available in 1.9.8. Feel free to request that this bug be reopened if that ends up not being the case.
