### ISSUE TITLE
FreeDV Reporter does not sort by distance correctly

### ISSUE THREAD

**Issue by no1453** [drowe67/freedv-gui#680]
Windows 11 Pro.  In version 1.9.7.2, when you click on the column header for distance to sort by it, it will sort the numbers incorrectly, either when ascending, or descending.   Version 1.9.6 sorts correctly.    Version 1.9.8-devel (compiled from the current master branch) shows the same error in sorting by distance.

<img width="102" alt="distance" src="https://github.com/drowe67/freedv-gui/assets/3926817/b6337bc9-1e5d-4c52-952d-e708d199f3d8">

**Comment by tmiw** [comment]
Thanks for reporting this. Looks like it was a Windows specific issue as it seemed to be sorting okay on Linux and macOS. 

Anyway, https://github.com/drowe67/freedv-gui/pull/681 fixed this and should now be merged into master.

**Comment by no1453** [comment]
Glad I could help.
