### ISSUE TITLE
Option to display cardinal points rather than degrees in the reporter heading  column.

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#682]
Is there a possibility of extending the usability of the reporter heading column to display 16 approximate cardinal points as an alternative to degrees?

I have found a C++ routine that should handle the conversion:

```
int cardinalDirectionNumber( static_cast<int>( ( ( currentGustDirection / 360.0 ) * 16 ) + 0.5 )  % 16 );
const char* const cardinalDirectionTexts[] = { "N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "SW", "WNW", "NW", "NNW" };
string dirString = cardinalDirectionTexts[ cardinalDirectionNumber ];
```

Reference:
https://cumulus.hosiene.co.uk/viewtopic.php?p=9802&sid=bdb6d3c1f7f482e87ca10856dec6c1ff#p9802

**Comment by tmiw** [comment]
https://github.com/drowe67/freedv-gui/pull/685
