### ISSUE TITLE
freedv depends on libhamlib2 (>= 3.3-10build1) during package install on raspberry pi4 

### ISSUE THREAD

**Issue by giddygiddybangbang** [drowe67/freedv-gui#684]
Bookworm lite install on rpi4
Dpkg install shows the following after build:
unpacking freedv (1.9.8-devel-2024-01-27)
freedv depends on libhamlib2 (>= 3.3-10build1); however:
  Package libhamlib2 is not installed.

**Comment by tmiw** [comment]
Can you explain how you're getting and/or building the FreeDV package? It looks like the latest on Debian bookworm is https://packages.debian.org/bookworm/freedv, which is version 1.8.11.

**Comment by tmiw** [comment]
As mentioned in #683, `cpack` is no longer supported, so this will be closed.
