### ISSUE TITLE
Last version on pi/os 64 on Pi 3+ :very slow startup 

### ISSUE THREAD

**Issue by UgoPoddine** [drowe67/freedv-gui#687]
Hello Mooner,

I have installed the last freedv gui version on a fresh Pi/os 64 over pi3+
Differently from the same installation on the same hardware but on 32bit Pi/os image (still Bookworrm),  freedv gui starts well, but when I try to activate the modem (whatever, also the old 700c) the modem takes more than 1,5 minutes to start itself. Once started, It seems at first glance tò work well.
In the past similar issue happned on switcing off the modem, and you were able to solve.

Just for your knowledge.
Thank-you for your Activity, as usual.
IU1IPBi Ugo

**Comment by tmiw** [comment]
I'm guessing you're using PortAudio and not PulseAudio? https://github.com/drowe67/freedv-gui/pull/689 might help, or at least it does for me on macOS anyway.

**Comment by UgoPoddine** [comment]
Hello Mooner, you are right. In the past having Pulseaudio generate plenty of issues in these small machines, directly and on calfplugins. 
I will try your suggestion asao : thank-you so much, as usual

Ugo

**Comment by IU1IPB** [comment]
Hello Mooner,

I have installed the new version on the 64bit OS, but I can not see any difference. Modem startup still takes about 1m20 sec.
I wonder that this was for the first startup, but the same 1m20secs happened also to the further ones.

Thank-you
Ugo

**Comment by tmiw** [comment]
Try the latest from that PR again?

**Comment by UgoPoddine** [comment]
Hi Mooner,

I have installed at the moment the cd89a16c.
If I'm not wrong it's the last, but the problem seems to persist...

Tnx 
Ugo

Il giorno 17 feb 2024, 06:14, alle ore 06:14, Mooneer Salem ***@***.***> ha scritto:

**Comment by UgoPoddine** [comment]
Hello Mooner,

Sorry for the delay.
I have cloned d73e44e8 branch and the issue seems solved, at least regarding the startup time.
I will try on air this night.

You are the usual guru
Thank-you 
Ugo

Il giorno 17 feb 2024, 19:43, alle ore 19:43, Mooneer Salem ***@***.***> ha scritto:

**Comment by tmiw** [comment]
Thanks for the testing! I just merged the changes and they should be in the next release.
