### ISSUE TITLE
Release 1.9.8 FreeDV Reporter list does not populate

### ISSUE THREAD

**Issue by no1453** [drowe67/freedv-gui#690]
The window opens and seems to have all its widgets, but the list of participants does not appear.  On Windows 11 Pro.    Rest of program seems to operate normally.
![window](https://github.com/drowe67/freedv-gui/assets/3926817/90d0535f-6f7a-4dba-bbc8-b91a6c6d596c)

**Comment by tmiw** [comment]
I just installed 1.9.8 on my Windows VM and it looks like it's behaving as expected for me:

<img width="1189" alt="Screenshot 2024-02-11 at 10 28 29 AM" src="https://github.com/drowe67/freedv-gui/assets/449242/a0b92efd-3a40-48fd-8f5c-3d8160d8452a">

Some stuff you can try:

1. Make sure https://qso.freedv.org/ works in a web browser if you haven't done so already.
2. Disable IPv6 on your Windows machine. qso.freedv.org should work on both IPv6 and IPv4 but some ISPs don't handle the former very well (despite the fact that Windows and other OSes are supposed to fallback to v4).
3. Make sure the FreeDV Reporter hostname is actually configured to be "qso.freedv.org" (Tools->Options->Reporting). This is the default now but it was originally another hostname in the initial releases containing FreeDV Reporter.

**Comment by no1453** [comment]
My apologies, I just found the executable was somehow marked as "to block" in my firewall.   Everything works.
