### ISSUE TITLE
Callsign list - add a scroll bar

### ISSUE THREAD

**Issue by Tyrbiter** [drowe67/freedv-gui#691]
The callsign list is odd on my DE, it disappears off the bottom of the screen and I can't find a way of stopping this behaviour.

If there were a scroll bar then the list sub-window size could be more sensible and it would be possible to scroll down to earlier entries instead of being unable to see them at all.

**Comment by tmiw** [comment]
For me, scrollbars seem to appear when I actually click inside the list. For example, with GNOME on Linux (red circle):

![Screenshot 2024-02-13 at 9 12 52 AM](https://github.com/drowe67/freedv-gui/assets/449242/2821778e-b554-4423-aa05-09079eb7eaa6)

Windows and macOS for comparison:

<img width="512" alt="Screenshot 2024-02-13 at 9 02 11 AM" src="https://github.com/drowe67/freedv-gui/assets/449242/94e8a7c5-f83e-45e3-b9e4-a82105214ad9">

<img width="273" alt="Screenshot 2024-02-13 at 9 03 01 AM" src="https://github.com/drowe67/freedv-gui/assets/449242/fec989ce-ef80-474f-bc04-a6325e62ca8c">

Unfortunately, I'm not sure there's a way to influence this behavior on FreeDV's side.

**Comment by Tyrbiter** [comment]
I see what you mean, although I am particularly referring to a vertical scroll bar in my case, it's when the list fills to the point where the callsigns go off the bottom of the screen and I cannot scroll the list to see them and moving the window up doesn't show the bottom of the callsign list. Might be DE related, but I don't see why it would be, probably a feature of wxWidgets.

**Comment by tmiw** [comment]
Looks like when there are enough entries, there's also a vertical scroll bar that appears when I hover my mouse over the box:

![Screenshot 2024-02-15 at 11 18 38 AM](https://github.com/drowe67/freedv-gui/assets/449242/a27a5d42-d7d8-4582-89da-c3556172b34e)

I can scroll through the list using two-finger scrolling on my laptop's trackpad (or hover my mouse over the vertical line--which makes it thicker--and drag it up and down). Ubuntu 22.04 with GNOME as before. 

Unfortunately I don't think this is anything FreeDV itself can influence, especially since it does seem to be working as intended in other Linux environments and other OSes.

**Comment by Tyrbiter** [comment]
It's quite strange, what I see is shown below:

![Screenshot from 2024-02-16 10-27-35](https://github.com/drowe67/freedv-gui/assets/36776842/38e0c7bb-2a6c-4f12-8d85-58a30d1bd983)

I have to make the freedv window full screen in order to get the list to open upwards, otherwise it extends off the bottom of the screen and goes under the panel (the blurred area).

I quite understand the problem with coding this, I can't find any window manager settings that change this behaviour. Maybe something to think about for future versions.

**Comment by tmiw** [comment]
I tried some other tweaks but it doesn't look like wxWidgets wants to allow the popup to open upward. In the meantime, I provided a maximum size for the dropdown in https://github.com/drowe67/freedv-gui/pull/692. The exact maximum size is TBD but it might at least make your situation less likely to happen.

**Comment by Tyrbiter** [comment]
OK, I have it running with this change and will comment once I have some further testing completed.

**Comment by tmiw** [comment]
> OK, I have it running with this change and will comment once I have some further testing completed.
> 
> So far I find this an excellent improvement, as now I get a vertical scroll bar when the list overflows the window size. It's almost as if a default size is missing in wxWidgets on some platforms.

Cool, thanks! I'll go ahead and merge.
