### ISSUE TITLE
[Feature Request] Higher quality modes

### ISSUE THREAD

**Issue by Aleziss** [drowe67/freedv-gui#693]
### Contact Details

aleziss

### Feature for this project

Hello everyone,

I was wondering if it could be possible to run higher quality modes [since the FCC now permit 2.8kHz transmit bandwidth](https://docs.fcc.gov/public/attachments/DOC-398409A1.txt) in digital modes ?

I ask just for experimentation and see how wider, better quality or better compression would be like, if any of this is possible as test and exploration ?

With a warning message box that the operator must know if it is legal to run such wider modes.

Thank you for the awesome work on freedv !

### VHF/UHF

No

### Deprecated features

No

### Non-standard compiler

No

### Non-standard compiler

No

### Implementation assistance

Able to test such new features with other users.

### Support assistance

I can support by testing and reporting results of different modes in the upcoming years for sure.

**Comment by tmiw** [comment]
The former symbol rate restriction never affected FreeDV given that the FCC considers it "phone" and not "data".

That said, the existing 2020 mode (while less resilient) does have better quality than the other modes, not to mention that we are working on improvements to FreeDV overall in that regard. 👍

**Comment by Aleziss** [comment]
ohhh... awesome, can't wait to see and hear those future improvement.

I did ask because I think the codec is able to handle a lot higher quality.

Thanks for the reply !

You can close this suggestion.
