### ISSUE TITLE
Please ship FreeDV as flatpak package on FlatHub for Linux user

### ISSUE THREAD

**Issue by Nokia808** [drowe67/freedv-gui#697]
Hello dear. 

I would like to request from you to ship FreeDV program as flatpak package on FlatHub. This will make 2 things:
1) make FreeDV available to almost all Linux distros, because flatpak is a universal Linux package,
2) make FreeDV available in it's up to date latest version for Linux user & avoiding delay in the updating process of distro specific packages. For example, I'm on Fedora Linux 38, & freeDV available to me from official Fedora repositories as version 1.8.4 ......

Please see following links for more information about flatpak & FlatHub:

https://flatpak.org/

https://docs.flatpak.org/en/latest/

https://github.com/flatpak/flatpak

https://flathub.org/

https://github.com/flathub

https://github.com/flathub/flathub

Bellow link you can through it introduce flatpak package to FlatHub as a pull request:
https://github.com/flathub/flathub/pulls

Please do not ignore this issue. It is a great solution for Linux.

**Comment by tmiw** [comment]
Thanks for this feedback. Some work was started on this earlier, see https://github.com/drowe67/freedv-gui/pull/600. It's currently on hold for a few reasons:

1. The initial feedback was negative. While the sample size was pretty small, most people seemed to prefer compiling FreeDV themselves or using distro packages given the overhead Flatpak has.
2. Other higher priority development tasks are currently in progress.

That said, can you gauge how much demand there would be if a Flatpak or AppImage was available? (I'd rather not use Snap because it's Ubuntu specific.) Also, any reason for going with Flatpak specifically vs. AppImage, assuming that there aren't enough developer resources available to support both?

**Comment by Nokia808** [comment]
If you asked me which prefer flatpak or appimage I will select flatpak because it is much easier for packager to work with it in compare with appimage

I agree with you against Snap. But, flatpak completely different.

**Comment by Tyrbiter** [comment]
The reason for the slow release of freedv versions on Fedora is because of the many packages that depend on codec2, it is Fedora policy not to have .so version bumps during a release cycle of ~6 months.

**Comment by Nokia808** [comment]
@Tyrbiter 
It seem - if I'm not wrong in interpretation of your comment - that your plan to ship FreeDV as flatpak on Fedora flatpak official repositories !! If this is what you meant then there is a strategical miss-understanding between me & you ! I did not ask & will never ask to add FreeDV as flatpak on Fedora flatpak official repositories ! I asked for adding FreeDV as flatpak on FlatHub ! I asked for flatpak on FlatHub (which has no relation with Fedora) to escape away from Fedora extreme policies .... Moreover, most Flatpak users installing their flatpak packages from FlatHub not from Fedora flatpak ....

**Comment by Nokia808** [comment]
Keep it at your list with delayed priority. In the future when resources increased, do it at that time.

**Comment by tmiw** [comment]
Yeah, it won't hurt to keep this open for now. When priorities change, we can definitely revisit for sure.

**Comment by tmiw** [comment]
Current discussion about Flatpak on the linuxham reflector for those who are interested: https://groups.io/g/linuxham/topic/107122176

**Comment by tmiw** [comment]
Current discussion about Flatpak on the linuxham reflector for those who are interested: https://groups.io/g/linuxham/topic/107122176

**Comment by tmiw** [comment]
Closing as the project has decided not to do any further work on this at this time.
