### ISSUE TITLE
When tracking 'band', a change to 'frequ' is ignored until tracking is stopped and restarted. 

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#703]
I was on 28.720 two others were on 28.330 when I had band selected. Clicking freq made no difference. I had to click 'track' twice to see only 28.720.

![Screenshot_20240328_131146](https://github.com/drowe67/freedv-gui/assets/1324702/7070a8c2-6117-4224-96f1-b28c94b7f322)

**Comment by tmiw** [comment]
Thanks for finding this! Let me know how the fix in https://github.com/drowe67/freedv-gui/pull/704 goes. It seems that the user list *does* update in my testing, just not immediately (only when we receive an update for the users not matching the filter from the server, which typically happens within ~5 seconds with the more recent versions of FreeDV).

**Comment by barjac** [comment]
Yes, tested and seems just fine now - thanks! :)

**Comment by tmiw** [comment]
> Yes, tested and seems just fine now - thanks! :)

Sounds good. I just merged the appropriate PR. 👍
