### ISSUE TITLE
Compiling with clang-cl

### ISSUE THREAD

**Issue by gvanem** [drowe67/freedv-gui#71]
Just a FYI.

I know this project is rather gcc/MinGW centric. Some `#ifdef _MSC_VER` in the code seems to indicate MSVC is supported,
but trying that, it fails miserably. 

Trying with `clang-cl` instead, also fails on mundane things like of `__cpuid()`:
```c
In file included from dlg_audiooptions.cpp:22:
In file included from ./fdmdv2_main.h:68:
f:\ProgramFiler\LLVM-10-32bit\lib\clang\10.0.0\include\intrin.h(61,25): error: too few arguments provided to
      function-like macro invocation
void __cpuid(int[4], int);
                        ^
f:\ProgramFiler\LLVM-10-32bit\lib\clang\10.0.0\include\cpuid.h(223,9): note: macro '__cpuid' defined here
#define __cpuid(__leaf, __eax, __ebx, __ecx, __edx) \
        ^
In file included from dlg_audiooptions.cpp:22:
In file included from ./fdmdv2_main.h:68:
f:\ProgramFiler\LLVM-10-32bit\lib\clang\10.0.0\include\intrin.h(61,6): error: variable has incomplete type 'void'
void __cpuid(int[4], int);
     ^
f:\ProgramFiler\LLVM-10-32bit\lib\clang\10.0.0\include\intrin.h(519,35): error: too few arguments provided to
      function-like macro invocation
__cpuid(int __info[4], int __level) {
                                  ^
f:\ProgramFiler\LLVM-10-32bit\lib\clang\10.0.0\include\cpuid.h(223,9): note: macro '__cpuid' defined here
#define __cpuid(__leaf, __eax, __ebx, __ecx, __edx) \
        ^
In file included from dlg_audiooptions.cpp:22:
In file included from ./fdmdv2_main.h:68:
f:\ProgramFiler\LLVM-10-32bit\lib\clang\10.0.0\include\intrin.h(519,1): error: variable has incomplete type 'void'
__cpuid(int __info[4], int __level) {
^
f:\ProgramFiler\LLVM-10-32bit\lib\clang\10.0.0\include\intrin.h(520,3): error: expected expression
  __asm__ ("cpuid" : "=a"(__info[0]), "=b" (__info[1]), "=c"(__info[2]), "=d"(__info[3])
  ^
```

But patching it into:
```diff
--- a/src/fdmdv2_main.h 2020-09-04 12:44:39
+++ b/src/fdmdv2_main.h 2020-09-04 13:29:47
@@ -52,8 +52,10 @@

 #include <stdint.h>
 #include <speex/speex_preprocess.h>
-#if defined(__x86_64__) || defined(_M_X64) || defined(__i386) || defined(_M_IX86)
-#include <cpuid.h>
+#if defined(_MSC_VER)
+  #include <intrin.h> // used for AVX checking
+  #include <cpuid.h>
+#elif defined(__x86_64__) || defined(_M_X64) || defined(__i386) || defined(_M_IX86)
+  #include <cpuid.h>
 #endif
 #ifdef _WIN32
 #include <windows.h>
@@ -63,11 +65,6 @@
 #include <dlfcn.h>
 #endif

-#ifdef _MSC_VER
-// used for AVX checking
-#include <intrin.h>
-#endif
-
```

The `dlg_audiooptions.cpp` (and other) files compile fine.

**Comment by srsampson** [comment]
I was thinking about old versions of Visual C++ that understand _MSC_VER but don't understand
```
__cpuid()
```
Maybe they all do, and my question is bonkers...

**Comment by drowe67** [comment]
@gvanem Thanks for your suggestion.  We seem to have a lot of issues with that macro, which suggests it could be done better.  The other issue with supporting different compilers and platforms is someone has to maintain/test on the various platforms/compilers.  We get some coverage of this on Travis (and Docker for the Windows build).

What works best for me is having a maintainer for each platform - someone who will go to the trouble of building and basic testing on the platform they own.  @tmiw is a great example - he does excellent work on OSX.

Coincidentally, the issue of supporting other compiiers has also recently come up for [Codec 2](https://github.com/drowe67/codec2/pull/145)

**Comment by tmiw** [comment]
@drowe67, perhaps we can outsource that to the cpuid library? https://github.com/steinwurf/cpuid

As a bonus, it'll allow us to detect NEON on ARM if 2020 is ported to that architecture.

**Comment by drowe67** [comment]
Closing this one as the cpuid issue is covered over on LPCNet. If anyone want's to progress it in future pls feel free to post a PR.
