### ISSUE TITLE
Tooltip covers dB values for Squelch and TX Attenuation sliders

### ISSUE THREAD

**Issue by tmiw** [drowe67/freedv-gui#715]
## Steps to Reproduce

1. Click Start.
2. Drag TX Attenuation or Squelch sliders left or right.

## Expected Behavior

dB value should still be visible while dragging the sliders.

## Actual Behavior

Tooltips hide the slider values while dragging.

## SW Version Tested

FreeDV 1.9.9.1 (Git commit e1c1530bef9e35a6c346837a7de251c07776c146)

**Comment by Tyrbiter** [comment]
I think the obvious fix for this is to make the tooltip disappear as soon as the slider is clicked and dragged.

**Comment by tmiw** [comment]
> I think the obvious fix for this is to make the tooltip disappear as soon as the slider is clicked and dragged.

That's what it does for me on macOS but I don't think it does that on Windows. I think it'll be easier just to remove those tooltips rather than debug yet another Windows-specific issue. Will create a PR shortly.

**Comment by Tyrbiter** [comment]
Same problem on Linux, looks like the MacOS wxWidgets port has been better thought out.

**Comment by tmiw** [comment]
Interesting, I just merged that PR and this issue didn't auto-close. I'm guessing it's because I'm merging into bugfix-main instead of master? (I'm trying to keep the radae-related changes--once they come--separate from any bugfixes in case another release needs to be rolled out for any critical ones in the latter bucket.)

**Comment by Tyrbiter** [comment]
Seems odd that an arbitrary naming convention should be enforced for that. Anyway tooltips are gone as expected.
