### ISSUE TITLE
Reporter Msg column : Only add ellipsis (...) if the Msg column width will not fit the whole message. 

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#720]
In use I have been finding that many messages have the ellipsis even when I can easily widen my Msg column so it would fit the whole message.

At present widening the column does not expand the message and remove the ellipsis, the user has to still use the tooltip even when room has been made for the whole message.

Improved behaviour:
If a message has an ellipsis, allow widening of the column to adjust the number of characters allowed before an ellipsis is added.

**Comment by tmiw** [comment]
How does https://github.com/drowe67/freedv-gui/pull/721 work for you?
