### ISSUE TITLE
Sound card error

### ISSUE THREAD

**Issue by Psynewaves** [drowe67/freedv-gui#722]
Not sure what the cause is, but I am unable to use VB-Audio cable as the input for FreeDV.
The issue occurs on both 32 bit and 64 bit windows versions.
See attached pictures
![Audio](https://github.com/drowe67/freedv-gui/assets/118508891/4d79b594-9ce7-447a-aea3-bd8a3d052b34)
![Error](https://github.com/drowe67/freedv-gui/assets/118508891/04ca4704-af31-4b16-ba7c-d92441a56b33)

**Comment by tmiw** [comment]
This was fixed in 1.9.9.1. Can you try that version and confirm?

**Comment by tmiw** [comment]
Any updates?

**Comment by Psynewaves** [comment]
Hello,
Thank you for your reply. I am currently out west for rostered work. I will
be returning home on Wednesday and will certainly try the above
recommendation.
I shall provide an update as soon as possible after testing.

**Comment by Psynewaves** [comment]
I have tested this on 1.9.9.1 and the issue appears to be resolved. The error is no longer present and the modem is functional again :)
Thank you for  your time, help, assistance and patience with me.

**Comment by tmiw** [comment]
No worries! Feel free to open another issue if you find any other problems :)
