### ISSUE TITLE
CMakeLIsts.txt line 51 overrides configuration option -DFREEDV_VERSION_TAG=

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#726]
Can CMakeLists.txt line 51 please be made conditional on -DFREEDV_VERSION_TAG not already being set to a value during cmake configuration.

At present it get clobbered.
Thanks :)

**Comment by tmiw** [comment]
See https://github.com/drowe67/freedv-gui/pull/727 :)

**Comment by barjac** [comment]
Confirm resolved - thanks!
