### ISSUE TITLE
Voice keyer file/directory persistence.

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#728]
The voice keyer allows selection of a file to play but then forgets it and switches back to the one at the top of the directory.
This happens in the same session if the program is stopped and re-started.

It would be better if the directory in use and the file in use were remembered between re-boots, and program re-starts.

**Comment by tmiw** [comment]
I thought we *didn't* want the "alternate" voice keyer file to persist across restarts before. Am I remembering correctly or was this a scenario we didn't test originally?

That said, we should be saving the previously used path for Tools->Start Play/Record File, so I opened #729 for that.

**Comment by barjac** [comment]
> I thought we _didn't_ want the "alternate" voice keyer file to persist across restarts before. Am I remembering correctly or was this a scenario we didn't test originally?

I have no idea, but I don't see much point in one default VK file! That is like one default Msg for the reporter Msg column!

I have a "VK files" directory with a dozen different CQ and testing calls.
If I select one to use I expect it to be there until I change it and not have it change between re-starts, re-boots etc.
I was trying to fault find an issue the other day and was calling CQ on top band with the VK. Every time I re-started the program and used the VK to call it started a message intended for 10m, so I had to stop the TX, change the VK message back to "CQ_160m700D" and re-start. This happened several times.
Very frustrating!

I also think the 'current' VK filename should be visible on the main screen somewhere, to avoid transmitting the wrong message.
Maybe on the Voice Keyer button with no path or file extension shown?
Like:

Voice Keyer
CQ_160m700D

**Comment by tmiw** [comment]
I found the original PR that implemented that VK file selection (https://github.com/drowe67/freedv-gui/pull/493) and it looks like we were fine with how it's currently behaving back then:

> I could see a situation where someone forgets what they used previously and ends up transmitting the wrong WAV file out the next day. How about the following?
> 
> 1. The selected VK file is persistent but just for the current FreeDV run.
> 2. The default VK file is still set in Tools->Options->Audio and is what starts off as the "selected" one.
> 3. When doing (1), the folder the selected file is in persists across restarts (i.e. if you restart FreeDV and attempt to choose a VK file again, the window will start off in that folder instead of whatever random folder).

I'm guessing that's no longer the case? If so, to make sure I'm understanding the proposal:

1. Tools->Options->Audio should only configure the folder and *not* any specific file name for the voice keyer file.
2. Left-clicking on the Voice Keyer button for the first time FreeDV is ever run (or right-clicking at any time) should mandate selection of the specific voice keyer file at that point, with the file selection window defaulting to the folder specified in (1).
3. Left-clicking on the Voice Keyer button when there's a file already selected just uses that one, even if selected during a previous execution.
4. Whenever the exact file name changes in (2), store the full path to that file somewhere separate from where (1) is stored.

Let me know if I missed anything. I wonder if others who use the voice keyer should comment on this as well since this would be a significant change to how the feature woks.

(BTW the currently playing voice keyer filename does display on the bottom of the FreeDV window.)

**Comment by barjac** [comment]
> I found the original PR that implemented that VK file selection (#493) and it looks like we were fine with how it's currently behaving back then:
> 
> > I could see a situation where someone forgets what they used previously and ends up transmitting the wrong WAV file out the next day. How about the following?
> > 
> > 1. The selected VK file is persistent but just for the current FreeDV run.
> > 2. The default VK file is still set in Tools->Options->Audio and is what starts off as the "selected" one.
> > 3. When doing (1), the folder the selected file is in persists across restarts (i.e. if you restart FreeDV and attempt to choose a VK file again, the window will start off in that folder instead of whatever random folder).
> 
> I'm guessing that's no longer the case? If so, to make sure I'm understanding the proposal:
> 
>     1. Tools->Options->Audio should only configure the folder and _not_ any specific file name for the voice keyer file.

Yes.
The text entry field should only accept a path to the directory to be used, optionally using the choose button. Function is then similar to the 'Quick record' below it.

> 
>     2. Left-clicking on the Voice Keyer button for the first time FreeDV is ever run (or right-clicking at any time) should mandate selection of the specific voice keyer file at that point, with the file selection window defaulting to the folder specified in (1).

It should mandate the specifying of a directory for the VK files if one has not been set up in (1) but not the file as none may yet exist. If the directory exists the user will see that it is empty and cancel.

On selecting a file it would then be the 'current selection' which would persist for ever unless changed so I suppose it becomes your 'default'?.
I think the term 'default' is confusing, 'current selection' makes more sense to me. 


> 
>     3. Left-clicking on the Voice Keyer button when there's a file already selected just uses that one, even if selected during a previous execution.

...or session or boot - yes
> 
>     4. Whenever the exact file name changes in (2), store the full path to that file somewhere separate from where (1) is stored.

The full path would not be needed as the path to the current VK file directory would be stored in (1). 
Any newly selected file or new file would already be in, or be being stored in that directory.

I don't understand the reasoning behind "somewhere separate from where (1) is stored."

> 
> 
> Let me know if I missed anything. I wonder if others who use the voice keyer should comment on this as well since this would be a significant change to how the feature woks.

Certainly if you think.
> 
> (BTW the currently playing voice keyer filename does display on the bottom of the FreeDV window.)

Yes but there is no way of knowing what the 'current VK file' is without starting to play it, which is a bit late!
I think the button label would be the right place. Users will learn to keep file names short!

**Comment by tmiw** [comment]
> > ```
> > 2. Left-clicking on the Voice Keyer button for the first time FreeDV is ever run (or right-clicking at any time) should mandate selection of the specific voice keyer file at that point, with the file selection window defaulting to the folder specified in (1).
> > ```
> 
> It should mandate the specifying of a directory for the VK files if one has not been set up in (1) but not the file as none may yet exist. If the directory exists the user will see that it is empty and cancel.

Quick Record actually defaults to the user's Documents folder the first time FreeDV's started. That seems reasonable to do here as well, no? That way, only the file would need to be selected.

> > ```
> > 4. Whenever the exact file name changes in (2), store the full path to that file somewhere separate from where (1) is stored.
> > ```
> 
> The full path would not be needed as the path to the current VK file directory would be stored in (1). Any newly selected file or new file would already be in, or be being stored in that directory.
> 
> I don't understand the reasoning behind "somewhere separate from where (1) is stored."

What if the user wants to choose a file located outside of the configured VK directory? Only storing the file name would restrict use of the voice keyer to the files in the configured folder, correct?

> > Let me know if I missed anything. I wonder if others who use the voice keyer should comment on this as well since this would be a significant change to how the feature woks.
> 
> Certainly if you think.

Pinging @Tyrbiter in case he hasn't seen this thread yet.

> > (BTW the currently playing voice keyer filename does display on the bottom of the FreeDV window.)
> 
> Yes but there is no way of knowing what the 'current VK file' is without starting to play it, which is a bit late! I think the button label would be the right place. Users will learn to keep file names short!

Would putting the file name in the tooltip work?

**Comment by Tyrbiter** [comment]
> > > ```
> > > 2. Left-clicking on the Voice Keyer button for the first time FreeDV is ever run (or right-clicking at any time) should mandate selection of the specific voice keyer file at that point, with the file selection window defaulting to the folder specified in (1).
> > > ```
> > 
> > 
> > It should mandate the specifying of a directory for the VK files if one has not been set up in (1) but not the file as none may yet exist. If the directory exists the user will see that it is empty and cancel.
> 
> Quick Record actually defaults to the user's Documents folder the first time FreeDV's started. That seems reasonable to do here as well, no? That way, only the file would need to be selected.
> 

I'm not strongly decided on where this should be, ~/Documents is a reasonable default, I would hope that most people would realise that it is sensible to choose somewhere devoted to freedv, personally I use ~/freedv for recordings and ~/freedv/voice for vk files.

> > > ```
> > > 4. Whenever the exact file name changes in (2), store the full path to that file somewhere separate from where (1) is stored.
> > > ```
> > 
> > 
> > The full path would not be needed as the path to the current VK file directory would be stored in (1). Any newly selected file or new file would already be in, or be being stored in that directory.
> > I don't understand the reasoning behind "somewhere separate from where (1) is stored."
> 
> What if the user wants to choose a file located outside of the configured VK directory? Only storing the file name would restrict use of the voice keyer to the files in the configured folder, correct?
> 
> > > Let me know if I missed anything. I wonder if others who use the voice keyer should comment on this as well since this would be a significant change to how the feature woks.
> > 
> > 
> > Certainly if you think.
> 
> Pinging @Tyrbiter in case he hasn't seen this thread yet.
> 
> > > (BTW the currently playing voice keyer filename does display on the bottom of the FreeDV window.)
> > 
> > 
> > Yes but there is no way of knowing what the 'current VK file' is without starting to play it, which is a bit late! I think the button label would be the right place. Users will learn to keep file names short!
> 
> Would putting the file name in the tooltip work?

I wonder if the tooltip could be changed once a new user has understood what the various buttons do. Maybe have a new user setting which could be unticked to allow alternative tooltips or captions.

**Comment by tmiw** [comment]
> I'm not strongly decided on where this should be, ~/Documents is a reasonable default, I would hope that most people would realise that it is sensible to choose somewhere devoted to freedv, personally I use ~/freedv for recordings and ~/freedv/voice for vk files.

Do you think it's fairly common to want to play back voice keyer files from anywhere other than a single location? For instance, normally you'd play back a file from ~/freedv/voice but maybe you need to play one from ~/Downloads once or twice. I ask because based on what's been proposed so far, it sounds like the latter wouldn't be an option; you'd only be able to play back a file from that one pre-configured location.

> I wonder if the tooltip could be changed once a new user has understood what the various buttons do. Maybe have a new user setting which could be unticked to allow alternative tooltips or captions.

The tooltip should be able to be dynamically changed, but I'm of the mind that for basic day to day use, features should be self-explanatory.

**Comment by Tyrbiter** [comment]
> > I'm not strongly decided on where this should be, ~/Documents is a reasonable default, I would hope that most people would realise that it is sensible to choose somewhere devoted to freedv, personally I use ~/freedv for recordings and ~/freedv/voice for vk files.
> 
> Do you think it's fairly common to want to play back voice keyer files from anywhere other than a single location? For instance, normally you'd play back a file from ~/freedv/voice but maybe you need to play one from ~/Downloads once or twice. I ask because based on what's been proposed so far, it sounds like the latter wouldn't be an option; you'd only be able to play back a file from that one pre-configured location.
> 

Yes, which is probably not the best idea, so maybe there should be an Other... selection which allows freer choice.

> > I wonder if the tooltip could be changed once a new user has understood what the various buttons do. Maybe have a new user setting which could be unticked to allow alternative tooltips or captions.
> 
> The tooltip should be able to be dynamically changed, but I'm of the mind that for basic day to day use, features should be self-explanatory.

If possible yes. I like the idea of the filename in the button but that could look bad if the button was stretched ad infinitum.

**Comment by tmiw** [comment]
> > Do you think it's fairly common to want to play back voice keyer files from anywhere other than a single location? For instance, normally you'd play back a file from ~/freedv/voice but maybe you need to play one from ~/Downloads once or twice. I ask because based on what's been proposed so far, it sounds like the latter wouldn't be an option; you'd only be able to play back a file from that one pre-configured location.
> 
> Yes, which is probably not the best idea, so maybe there should be an Other... selection which allows freer choice.

I'm imagining using the normal file selection dialog here with the "initial" folder being the pre-configured one, which should allow users to select something else in another location. After selecting a file from another location, though, do we just not preserve the selected file? (i.e. transmit it until VK turns off, but don't use it next time the VK button's pushed)

**Comment by Tyrbiter** [comment]
> > > Do you think it's fairly common to want to play back voice keyer files from anywhere other than a single location? For instance, normally you'd play back a file from ~/freedv/voice but maybe you need to play one from ~/Downloads once or twice. I ask because based on what's been proposed so far, it sounds like the latter wouldn't be an option; you'd only be able to play back a file from that one pre-configured location.
> > 
> > 
> > Yes, which is probably not the best idea, so maybe there should be an Other... selection which allows freer choice.
> 
> I'm imagining using the normal file selection dialog here with the "initial" folder being the pre-configured one, which should allow users to select something else in another location. After selecting a file from another location, though, do we just not preserve the selected file? (i.e. transmit it until VK turns off, but don't use it next time the VK button's pushed)

That ought to be OK, I don't think we should make it any more complex than necessary. @barjac might like this, but a comment would be useful.

Displaying the filename in the button is OK if it's a short name, but how to deal with a longer name?

**Comment by barjac** [comment]
> > > > Do you think it's fairly common to want to play back voice keyer files from anywhere other than a single location?

No, but if they do then surely that is what the dialogue to set the path is for.

> > > For instance, normally you'd play back a file from ~/freedv/voice but maybe you need to play one from ~/Downloads once or twice. I ask because based on what's been proposed so far, it sounds like the latter wouldn't be an option; you'd only be able to play back a file from that one pre-configured location.

No you would not, you would simply change the directory path in the Tools->Audio dialogue temporarily - or have the sense to not put the files elsewhere in the first place or just move the files.
> > > 
> > > 
> > > Yes, which is probably not the best idea, so maybe there should be an Other... selection which allows freer choice.

The choice is totally free in my proposal, the user can change the 'current' VK directory at will.
> > 
> > 
> > I'm imagining using the normal file selection dialog here with the "initial" folder being the pre-configured one, which should allow users to select something else in another location. After selecting a file from another location,

I don't see any location as special. The dialogue would allow for the user to freely set ANY location as the current one.
I see this as keeping things simple whilst also allowing total flexibility. Some users may want to keep several VK sub-folders to avoid clutter in just one main one.

>> though, do we just not preserve the selected file? (i.e. transmit it until VK turns off, but don't use it next time the VK button's pushed)

We use whatever is the 'current VK file' in the 'current VK folder' for ever until we change it.
Keep it simple.

> 
> That ought to be OK, I don't think we should make it any more complex than necessary. @barjac might like this, but a comment would be useful.
> 
> Displaying the filename in the button is OK if it's a short name, but how to deal with a longer name?

You just truncate them on display. As I said before users will soon realize that short names are best :)

**Comment by Tyrbiter** [comment]
I think that's a fair summary, it would work for me as described.

**Comment by tmiw** [comment]
See https://github.com/drowe67/freedv-gui/pull/730, which should implement most of what @barjac mentioned. The one exception is the display of the VK filename; it's tooltip-only for now since I'm still not sure about having it in the button itself (regardless of how long the filename is). Example of what the tooltip looks like:

<img width="468" alt="Screenshot 2024-06-30 at 9 20 12 AM" src="https://github.com/drowe67/freedv-gui/assets/449242/f425995f-beab-4f67-97e1-cec5b3f6830b">

**Comment by Tyrbiter** [comment]
Seems adequate to me on first sight, but time will tell I expect.
