### ISSUE TITLE
Add relative volume settings in config for both transmit monitors

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#732]
When using the voice keyer or live transmit monitors to hear your own transmission, the volume is generally much higher than necessary.

If there were settings to attenuate these in maybe 1dB steps relative to the RX audio level then comfortable listening levels could be set for each. 

I suspect that the level needed for live TX will need to be considerably lower than that for the voice keyer so I think each does need its own setting.

**Comment by tmiw** [comment]
Thanks for this. Any thoughts on where the volume level should be settable from? (i.e. an additional slider or two in the existing Filter dialog or from some other location)

**Comment by barjac** [comment]
Maybe a new section called 'Monitor Levels' under  Tools->Options->Audio?

**Comment by tmiw** [comment]
> Maybe a new section called 'Monitor Levels' under Tools->Options->Audio?

Hmm, not sure about that one either; Tools->Options has traditionally been a location for settings that aren't supposed to change when a session is running (with the exception of the VK folder path now, of course). I see a few options:

1. Rename Tools->Filters to Tools->Audio Adjustment or similar and add the monitor volume controls there, or
2. Create a separate window just for configuring the monitor levels (accessible via the right-click menu for the VK and PTT buttons).

Maybe @Tyrbiter has some feedback as well?

**Comment by Tyrbiter** [comment]
Option 2 is preferable in my opinion.

**Comment by barjac** [comment]
I did not expect that once set as a value by a user that these would need to be adjusted on the fly. In the same way that in other software I use a relative setting for callsign ID which is to sent in the background at a lower level than the main signal is configured.

Don't forget that these would be 'relative' to any master system volume setting in use.

If the master volume is first set to a normal working level and suitable relative monitor levels are set in the configuration then I would expect that they would be left alone.

Temporary increase or decrease would be best done with the master volume control to avoid disturbing the configured relative monitor setting.

Of the two options above I would also prefer 2 as well, however manually edited values in the config file would be adequate for me.

**Comment by tmiw** [comment]
See https://github.com/drowe67/freedv-gui/pull/733. Let me know how that goes for you guys.
