### ISSUE TITLE
If a USB audio card is unplugged FreeDV wipes audio settings for that card.

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#734]
I have hit this many times and it is really frustrating and should not happen.

I use an external USB (CM108 based) audio dongle to handle audio to and from my transceiver.

I sometimes use that USB port with extension cable to connect other devices when not using FreeDV.

If I forget to re-connect it to the CM108 device afterwards and start FreeDV, then instead of just warning that the device is missing, FreeDV wipes it from the configuration as well!

Why, when it only needs to remind me to plug in the correct device and re-try?

**Comment by tmiw** [comment]
Part of what it's supposed to do is to switch the "analog" device(s) to the system's default if they no longer exist (i.e. if your USB headset's unplugged or something). Are you proposing that no configuration changes happen on any of the configured devices at all, or is it only the radio device(s) that shouldn't be touched?

**Comment by Tyrbiter** [comment]
FWIW I saw a similar problem in WSJTX the other day, I had a mains RCD trip out (due to a failing LED light) which caused the radios to lose power but not the PCs (on a UPS) and as a result I had to restart the PC connected to the radios because the USB connections didn't reinitialise and the USB cables are hard to reach.

I don't think this is anything to do with the WSJTX or freedv applications, it's at a lower level in the OS and USB subsystem.

What do you think @tmiw?

**Comment by barjac** [comment]
> Part of what it's supposed to do is to switch the "analog" device(s) to the system's default if they no longer exist (i.e. if your USB headset's unplugged or something).

That sounds possibly reasonable for fixed devices but not for removable ones that may be only temporarily missing. 

> Are you proposing that no configuration changes happen on any of the configured devices at all, or is it only the radio device(s) that shouldn't be touched?

I would say that no configuration changes should take place without first asking.

**Comment by tmiw** [comment]
> I don't think this is anything to do with the WSJTX or freedv applications, it's at a lower level in the OS and USB subsystem.

Likely, yes. @barjac's comments are definitely related to FreeDV, though, so we should determine how it should work there.

**Comment by tmiw** [comment]
> > Part of what it's supposed to do is to switch the "analog" device(s) to the system's default if they no longer exist (i.e. if your USB headset's unplugged or something).
> 
> That sounds possibly reasonable for fixed devices but not for removable ones that may be only temporarily missing.

Any ideas how to determine that? The most common way to trip this scenario would likely be removable devices going away, not someone deciding to upgrade to a new sound card/motherboard or something.

**Comment by barjac** [comment]
I would expect that if a configured audio device is missing then an error message should warn the user and allow the device to be replaced and the program re-started or re-initialized to correctly find the device listed in the config.

This is something that could be very off-putting to some new users who initially have some difficulty configuring the audio devices.
To have a good working configuration lost by simply having a USB plug removed could be the last straw for some. :(

**Comment by Tyrbiter** [comment]
> > I don't think this is anything to do with the WSJTX or freedv applications, it's at a lower level in the OS and USB subsystem.
> 
> Likely, yes. @barjac's comments are definitely related to FreeDV, though, so we should determine how it should work there.

The only reason it didn't happen to me in freedv is because the freedv modem wasn't running whereas WSJTX was decoding WSPR signals when the audio device disappeared from under it. I think it's essentially the same thing happening in both cases.

**Comment by barjac** [comment]
I suspect that the error to trip this already happens. It only needs to stop updating the config and simply say that the config seems wrong because ' device xyz is missing.

**Comment by barjac** [comment]
This is the message that appears when a first attempt to start the modem is made with the device removed.

"Your alsa_input.usb-0d8c_USB_PnP_Sound_Device-00.mono-fallback device cannot be found and may have been removed from your system. Please go to Tools->Audio Config... to confirm your audio setup."

You can't confirm the setup as it has been removed at this point and the selected audio device is "none".

Maybe this first dialogue should say "Check that your alsa_input.usb-0d8c_USB_PnP_Sound_Device-00.mono-fallback device is connected" and NOT change the config at this point?

Subsequent attempts to use the modem (ignoring the first message) produces:

![Screenshot_20240715_105556](https://github.com/user-attachments/assets/ebb7c056-99d0-4329-9fe8-6f83854b13e3)

**Comment by barjac** [comment]
Ah!!
I just discovered that if the first message is left on the screen while the device is re-inserted and then the dialogue closed with the X rather than OK, the modem can be re-started.

**Comment by Tyrbiter** [comment]
> Ah!! I just discovered that if the first message is left on the screen while the device is re-inserted and then the dialogue closed with the X rather than OK, the modem can be re-started.

A message like "Re-insert the missing device before clicking OK to continue normally" could be added.

**Comment by barjac** [comment]
> > Ah!! I just discovered that if the first message is left on the screen while the device is re-inserted and then the dialogue closed with the X rather than OK, the modem can be re-started.
> 
> A message like "Re-insert the missing device before clicking OK to continue normally" could be added. Or maybe add a Retry button for this purpose.

We doubled!! I was editing my above message during lunch and only saw your comment when I updated it. We are on the same page I think :)

**Comment by tmiw** [comment]
See https://github.com/drowe67/freedv-gui/pull/735. Does that message work for you guys?
