### ISSUE TITLE
[Feature Request] Display friendly name for audio devices when using PulseAudio/pipewire

### ISSUE THREAD

**Issue by tmiw** [drowe67/freedv-gui#739]
### Contact Details

tmiw

### Feature for this project

Currently, when FreeDV is compiled with PulseAudio support (the default), it displays the internal PulseAudio names for each audio device on the system (i.e. `alsa_output.xxx`). Other applications (such as pavucontrol) as well as FreeDV with PortAudio show a friendlier name (i.e. "Monitor of USB Audio Device"). FreeDV should show this friendly name when using PulseAudio too.

### VHF/UHF

No

### Deprecated features

No

### Non-standard compiler

No

### Non-standard compiler

No

### Implementation assistance

TBD -- need to determine whether there's demand for this feature first.

### Support assistance

TBD -- need to determine whether there's demand for this feature first.

**Comment by Tyrbiter** [comment]
I think this is a sensible change, however it would be useful to allow access to the ALSA name via something like a tooltip for cross-checking purposes. Some other tools will only display the ALSA names.

I don't know if the pipewire roadmap intends any of the device naming to change, it would be a good idea to try to find out.

**Comment by tmiw** [comment]
> I think this is a sensible change, however it would be useful to allow access to the ALSA name via something like a tooltip for cross-checking purposes. Some other tools will only display the ALSA names.
> 
> I don't know if the pipewire roadmap intends any of the device naming to change, it would be a good idea to try to find out.

Out of curiosity, what other tools only show the ALSA names? Has that caused usability problems for those?

**Comment by Tyrbiter** [comment]
I looked to see if I could find what I expected but it seems that even the older sound tools appear to use the friendlier pulseaudio names now. If I find anything else I will update this FR.

I reckon it would be useful to have tooltip access to the old ALSA names as I'm sure that some of the /dev tree has these names embedded in the output of some commands.

**Comment by tmiw** [comment]
Closing as no action has been taken on this since it was originally created.
