### ISSUE TITLE
FreeDV icon does not appear for Linux version

### ISSUE THREAD

**Issue by tmiw** [drowe67/freedv-gui#740]
For example, on GNOME:

![image](https://github.com/user-attachments/assets/b7084d5d-74f4-49cb-aa33-8d07af01f7ac)

whereas on macOS:

<img width="162" alt="image" src="https://github.com/user-attachments/assets/ed41af93-6eef-46dd-9281-6d3657bf6a7b">

(and similarly on Windows)

Anyway, the icon that's displayed should be the same regardless of platform. wxWidgets' `SetIcon()` might be usable for this, or perhaps a `.desktop` file needs to be created for FreeDV and installed in the correct location when running `make install`.

**Comment by Tyrbiter** [comment]
This is the output of rpm -ql for the Fedora freedv rpm:

/usr/bin/freedv
/usr/lib/.build-id
/usr/lib/.build-id/6b
/usr/lib/.build-id/6b/18bb958be26c1c4c8e763d1694e46a7b7fdf39
/usr/share/appdata/freedv.appdata.xml
/usr/share/applications/freedv.desktop
/usr/share/doc/freedv
/usr/share/doc/freedv/README.md
/usr/share/doc/freedv/USER_MANUAL.md
/usr/share/freedv-gui/wav
/usr/share/freedv-gui/wav/all_2020.wav
/usr/share/freedv-gui/wav/ve9qrp_1600.wav
/usr/share/freedv-gui/wav/ve9qrp_700c.wav
/usr/share/freedv-gui/wav/ve9qrp_700d.wav
/usr/share/freedv-gui/wav/ve9qrp_700e.wav
/usr/share/freedv-gui/wav/ve9qrp_800xa.wav
/usr/share/icons/hicolor/128x128/apps/freedv.png
/usr/share/icons/hicolor/256x256/apps/freedv.png
/usr/share/icons/hicolor/48x48/apps/freedv.png
/usr/share/icons/hicolor/64x64/apps/freedv.png
/usr/share/licenses/freedv
/usr/share/licenses/freedv/COPYING

As you can see there are various freedv.png files in different resolutions and also a .desktop file

This should be the same in the current distro version which is freedv-1.8.4 so the files needed are readily accessible.

**Comment by tmiw** [comment]
Sounds like it might be something the various package maintainers are already doing, then? If that's the case, do we need to take action on this at all?

**Comment by Tyrbiter** [comment]
> Sounds like it might be something the various package maintainers are already doing, then? If that's the case, do we need to take action on this at all?

I would say that as long as there is a suitable icon image file somewhere it's something a packager ought to do, @barjac is the Mageia packager so I would expect it to be in there somewhere but I have not checked what his packages contain.

**Comment by barjac** [comment]
Yes I do the same in Mageia, we have the various size icons and these are used for the .desktop file and also show on the taskbar along with the name and also in the main application menu.

![Screenshot_20240814_202120](https://github.com/user-attachments/assets/5ae0ff1f-220f-4a56-90ed-d04ab3a5cdf2)

> I would say that as long as there is a suitable icon image file somewhere it's something a packager ought to do

I agree this is something that packagers should do so it's not an issue.

**Comment by tmiw** [comment]
> I agree this is something that packagers should do so it's not an issue.

Fair enough, I'll go ahead and close for now.
