### ISSUE TITLE
Add text to the red line mouseover tooltip and remove 'Center RX' button

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#741]
Suggestions:
Change the red line mouseover tooltip to read:
"Double click to tune, middle click to re-center"
I suspect most users don't know about this feature.

Then, I really don't see any need for the 'Center RX' button as it duplicates the the above action.
This button is causing the main window to generate four left widget columns prematurely when reducing the window height compared to the situation before it was added.
When monitoring an SDR the space below the reporter was previously greater allowing more room for display of the SDR waterfall on a high aspect ratio screen like this laptop, whilst keeping only three widget columns each side of a good width 'scope widget.

This is just after the fourth left column is created when reducing height. 'Record' has been pushed into a new column by 'Center RX'. 
![Screenshot_20240826_101253](https://github.com/user-attachments/assets/508784c8-6f35-4256-bc6b-bd5d7020c7f3)

**Comment by barjac** [comment]
> On a more general note, is middle-click something that would be easy enough to find if that became the only way to re-center? I get that there'd be a tooltip but that'd also require someone to put their mouse over that area first.

Surely if they are adjusting the red line to re-tune RX then they already have the mouse over it, so the tooltip would appear anyway :)

Also it is inconvenient to have to move the mouse over to the 'Centre RX' button and back to the red line area to do this. Adjusting the tuning is a delicate operation and it is much more convenient to swap mouse buttons than move the mouse.

I really think that the button is superfluous clutter irrespective of any display issue.

**Comment by Tyrbiter** [comment]
Does anyone ever use the ReSync button these days? I don't think I would miss it.

**Comment by barjac** [comment]
> Does anyone ever use the ReSync button these days? I don't think I would miss it.

I have used it but not really sure whether it actually did anything that would not have been done automatically.
Are you saying that you would prefer to lose the Re-sync button rather than Re-center or would you be OK to lose both?

**Comment by Tyrbiter** [comment]
> > Does anyone ever use the ReSync button these days? I don't think I would miss it.
> 
> I have used it but not really sure whether it actually did anything that would not have been done automatically. Are you saying that you would prefer to lose the Re-sync button rather than Re-center or would you be OK to lose both?

If the ReSync button is of no use, removing it would make the Record button remain below it and keep the 3 column view.

I can see that the Center Rx button is somewhat out of place, but having it advertised only in a tooltip makes it more difficult to find.

**Comment by tmiw** [comment]
What if "Sync" was renamed to something else? Would that make the buttons fit better (assuming they were kept)?

**Comment by barjac** [comment]
> What if "Sync" was renamed to something else? Would that make the buttons fit better (assuming they were kept)?

Considering that all the buttons are the same height I don't see how that would change anything.

**Comment by barjac** [comment]
> I can see that the Center Rx button is somewhat out of place, but having it advertised only in a tooltip makes it more difficult to find.

The "double click to tune" is only advertised in the tooltip so how is this any different?

**Comment by Tyrbiter** [comment]
> > I can see that the Center Rx button is somewhat out of place, but having it advertised only in a tooltip makes it more difficult to find.
> 
> The "double click to tune" is only advertised in the tooltip so why should this be any different?

Well it's not really any different, I suppose it depends on how much you use these facilities. I find it useful to see what the modem thinks the centre frequency is but I rarely need to tune or re-centre because almost every signal I hear is bang on the nominal frequency. Reference oscillators are much more accurate over the long term than they used to be.

**Comment by tmiw** [comment]
I just realized--I'm not actually sure how to do middle-click on macOS without an external mouse. That might mean that the "Center RX". button still needs to stick around for that scenario. The addition to the tooltip isn't a huge deal, though, so I'll go ahead and at least do that.

**Comment by barjac** [comment]
> I just realized--I'm not actually sure how to do middle-click on macOS without an external mouse. That might mean that the "Center RX". button still needs to stick around for that scenario. 

Oops!

>The addition to the tooltip isn't a huge deal, though, so I'll go ahead and at least do that.
> 
> EDIT: #743

Thanks :)

**Comment by tmiw** [comment]
So yeah, do you know anyone who uses the ReSync button? If we're going to remove anything, that's the most likely candidate IMO (although it is still weird that this only seems to be a problem with KDE Plasma for some reason).

**Comment by tmiw** [comment]
Just pinging everyone. Any other work needed or can I just merge #743 as-is?

**Comment by Tyrbiter** [comment]
My only suggestion, aimed at @barjac and his screen estate requirements, is possibly moving the Resync button to a menu item if that's not too difficult. I don't use it, and have not heard anyone else say that they do.

Otherwise if this is seen as unnecessary I don't have any issues as it stands.

**Comment by tmiw** [comment]
Merged the change for the tooltips and am closing for now. Let me know if you'd like this reopened.
