### ISSUE TITLE
freedv_2_0_0 RADE howling on silence input

### ISSUE THREAD

**Issue by drowe67** [drowe67/freedv-gui#751]
Related to #750, RADE decoder howling noise/stuck when fed silence, see also https://github.com/drowe67/radae/pull/31

Success criteria:
1. No stability problems when RADE decoder fed silence.
2. No known way to induce howling.

**Comment by Roturbo** [comment]
Hi,,

i have a gate on input and sometimes i see the same on recordings, the silence make the soft output strange "voices",
but i don´t know if the problem is the silence on input before coding or on the decoder side..

**Comment by tmiw** [comment]
> Hi,,
> 
> i have a gate on input and sometimes i see the same on recordings, the silence make the soft output strange "voices", but i don´t know if the problem is the silence on input before coding or on the decoder side..

That sounds like maybe the "end of output" transmission faded out? That would explain why the audio didn't cut out immediately when the other side finished transmitting.

**Comment by drowe67** [comment]
@tmiw - with https://github.com/drowe67/radae/pull/31 can this one be closed?

**Comment by tmiw** [comment]
> @tmiw - with [drowe67/radae#31](https://github.com/drowe67/radae/pull/31) can this one be closed?

Yeah, I'll go ahead and close.
