### ISSUE TITLE
Signal resistance to interference is very good

### ISSUE THREAD

**Issue by Roturbo** [drowe67/freedv-gui#752]
I don´t know were to publish this, is just to communicate some testes i have made,,
so there is no bug or issue here.

I´m using a SDR, and to test the resistance i have put a notch with about 310Hz and move it back
and forward inside the signal, for my surprise the audio keep running normal.

![image](https://github.com/user-attachments/assets/18c72059-6e34-4be1-ba6b-777c7206231e)

![image](https://github.com/user-attachments/assets/0d098301-530a-4b96-bc52-e5efaeb6f575)

Than i go for more,, 631hz Notch.

![image](https://github.com/user-attachments/assets/f86b18a4-2ac8-4b32-932d-0f5945187954)
![image](https://github.com/user-attachments/assets/061dcb22-0d29-4d09-afc3-f54a60d3b31b)

I notice it start to degrade the signal a little bit but all words were clear, this means that on a freq
were there is present interference the software still can decode audio,, the test was made with 
a strong signal, i have to test with weak signal to see if it behaves the same.

In general, i´m impressed with the Rade and also my friends that before were using 700D, the quality
is so good that we don´t want to go back to other modes, i know it needs many corrections etc,
but for what is done Rade already prove is value.

Tank you for your good work, Rade is the way to go.

**Comment by tmiw** [comment]
Pinging @drowe67.

Anyway, good to hear that even notches don't seem to affect the signal too badly. I'd post reports like this in the RADE repo (https://github.com/drowe67/rade) since that seems more appropriate there.

**Comment by drowe67** [comment]
Thanks @Roturbo - interesting measure of robustness, but not sure if it would come up in the real world :thinking:   In the low level radae repo ctests we test the impact of interfering sine waves (like someone tuning up in the middle of the RADE signal), and it's also fairly robust.

**Comment by Roturbo** [comment]
Hello @drowe67 
maybe and is only a maybe, it is better missing signal like the notch is cutting than allow some other signal on that range.

With cases were we have a steady and permanent carrier or interference than add a notch may help better than one
strange signal that is also seen by the software and may disrupt the decoding,, if this is the case than in future 
a manual notch or AUTO-NOTCH  that detects this peak can minimize the problem.

The notch from digital radios like SDR is much more sharp and precise than analog radios, but this
can be done with FreeDV on audio level with same precision as an SDR.

By the way, i´m using Thetis that have a good NR2, from the 2 test that i have done there was no negative
impact on decoding, only the time to ReSync, will test it again with low signals to see if is the same.

Regards.

**Comment by Roturbo** [comment]
@tmiw 
> Pinging @drowe67.
> 
> Anyway, good to hear that even notches don't seem to affect the signal too badly. I'd post reports like this in the RADE repo (https://github.com/drowe67/rade) since that seems more appropriate there.

The link doesn´t exist yet

**Comment by tmiw** [comment]
> @tmiw
> 
> > Pinging @drowe67.
> > Anyway, good to hear that even notches don't seem to affect the signal too badly. I'd post reports like this in the RADE repo (https://github.com/drowe67/rade) since that seems more appropriate there.
> 
> The link doesn´t exist yet

Oops, I meant https://github.com/drowe67/radae/issues.

**Comment by Roturbo** [comment]
Hi @drowe67 

Just for your reference, software is working on a old MAC with windows 8 and on a Dual-Core 2.9Ghz.

Today we have made some test on 10m,, at 42 miles with less than 1w, almost no signal on the waterfall, 
but the audio still decoding normal, everyone were surprise and amazed with this new mode and the audio
quality that is very good and much more stable than the older modes.

I may be wrong, but Rade will take over any other HF Digital Voice on ham sphere.

**Comment by Roturbo** [comment]
@drowe67  @tmiw 

Hello,

just decode 3 or 4 RADE QSO and make some videos for reference 

https://youtu.be/Dw7l4Vc_dmo

https://youtu.be/U3Pvnfbt3_8

https://youtu.be/8QEoXksjNt0

You can use the links on other places if you want so other can see the quality and performance.

Regards

**Comment by tmiw** [comment]
Closing this as there is no issue here, just a user report. Thanks @Roturbo for that feedback, btw.
