### ISSUE TITLE
RADE sync indication missing

### ISSUE THREAD

**Issue by Tyrbiter** [drowe67/freedv-gui#753]
freedv-gui doesn't give any sync indication in RADE mode, at least for me here using the Linux version.

Is this something that is possible? Not sure if the RADE code allows for this yet.

**Comment by Tyrbiter** [comment]
I have just noticed that the orange line below the spectrum display is green when RADE is being decoded, however in the Sync box the word Modem is always in red whereas in other modes it is green when synced.

Looks like something simple could fix this.

**Comment by Roturbo** [comment]
hi @Tyrbiter 

I found this on the release page... and i think it is a long way for all to be working,
so we will find many bugs to solve, but all points that it is on the correct path.

-------------------------------------------

**As this is the first preview release, there are some limitations:**

As RADE currently doesn't return the signal's signal to noise ratio (SNR), 
it's not currently possible to receive it and the other FreeDV modes at the same time 
(as in, if you choose RADE and push Start, that's the only mode you can work; 
you'll need to stop, choose another mode and start again to work FreeDV with the existing modes).
    Squelch cannot currently be disabled with RADE. It's unknown at this time whether disabling squelch is possible.
    Due to compilation problems, 2020/2020B modes are disabled.
    There is currently no Windows ARM build; this will hopefully be included in a future preview build. 
You may be able to use the 64-bit Intel/AMD Windows build in the meantime.
    Minimum hardware requirements haven't been fully outlined, so your system currently 
may not be able to use RADE. Future planned optimizations may improve this.
    FreeDV Reporter does not currently report receiving RADE signals, 
but will report that you are using it and when you're transmitting.

https://github.com/drowe67/freedv-gui/releases

Regards

**Comment by tmiw** [comment]
See https://github.com/drowe67/freedv-gui/pull/754 and let me know/sign off if that's all good.

**Comment by Tyrbiter** [comment]
This is now working in the merged code.
