### ISSUE TITLE
AGC and Volume slider on RX and TX to main window

### ISSUE THREAD

**Issue by Roturbo** [drowe67/freedv-gui#755]
Hi,

just notice that some friends have high level audio compared to others, maybe an AGC to control
or limit the audio output will help to balance decoded signals,, this is more evident on Rade mode.

Also the volume gain mic/speaker placed in main window will help for easy control on input and output 
audio without have to go to Tools/Filter and have to close this to release/press PTT.

Regards, and tanks for your hard work.

.

**Comment by tmiw** [comment]
Adjustments in Tools->Filter actually take effect immediately, no need to push Stop and then Start again. There's also a TX monitor feature (right-click the PTT button in the main window) so you can immediately hear changes to the TX filters as you're transmitting.

I'll defer to @drowe67 on the AGC thing since it looks like there's an "auto EQ" option for the existing FreeDV modes.

**Comment by Roturbo** [comment]
yes i know that it takes effect immediately, but is always a 2 or more clicks to open a new window 
to do a simple function, control mic and speaker audio levels, the PTT is available if this window is open, 
that i didn´t test before, i see only now. 

![image](https://github.com/user-attachments/assets/178f192a-03b9-452a-84c0-9cb48d41399f)

The same slider takes 2 functions, it switch from RX to TX to control Speaker or Mic.

On the other modes we dind´t need to adjust this as it seems more controlled, but with Rade
some people appear with 2 or 3 times the audio volume compared to others. 

I also didn´t know about the right-click on PTT for audio monitor, if not as i suggest on that image, 
maybe someone can add it also to the right-click menu but not easy and practical as the double function.

**Comment by tmiw** [comment]
Can you repost this as a feature request for further discussion by the team? Direct link to the form [here](https://github.com/drowe67/freedv-gui/issues/new?assignees=&labels=feature+proposal&projects=&template=feature_request.yml&title=%5BFeature+Request%5D+). Once that's done, I'll close this duplicate issue.

**Comment by Roturbo** [comment]
@tmiw 

Hi, it is done, please check and close this one.

Tanks for your replay and support.

**Comment by tmiw** [comment]
Thanks, I'll take a look at the other one when I have a chance.
