### ISSUE TITLE
Adjustable delay from PTT-TX to audio output  (enhancement) 

### ISSUE THREAD

**Issue by Roturbo** [drowe67/freedv-gui#756]
Hi, this is a request from a friend.

Adjustable delay from PTT-TX to audio output to radio, the idea is to delay the RF a little to give time for relays to lock.

This is important for old rigs and PA´s, the relay have latching 15ms more or less depending on model, 
so if we delay the audio output from FreeDV there is also RF delay, so at the moment RF hit the relay it is already closed.

One more function is for people using also old rigs with USB SDR for Panadapter, the timing is so 
fast that the RF still have time to interfere and put spikes on the SDR before the relay is on or off
depending on the function.

Regards

**Comment by tmiw** [comment]
This is actually already in FreeDV:

<img width="985" alt="Screenshot 2024-10-20 at 8 23 57 PM" src="https://github.com/user-attachments/assets/65e829ff-deb8-44d4-932e-a384eea93879">

(Tools->Options->Rig Control, "TX/RX Delay (milliseconds)" field.)

Unless you mean something else?

**Comment by Roturbo** [comment]
Tanks @tmiw 

He didn´t see it, and i also didn´t see it or maybe we give it a different interpretation.

![image](https://github.com/user-attachments/assets/00778684-a8ff-4dab-9ade-8714b7e1e644)


Many tanks for your replay,, someone may close this.
