### ISSUE TITLE
AGC and Volume slider on RX and TX to main window [Feature Request] 

### ISSUE THREAD

**Issue by Roturbo** [drowe67/freedv-gui#760]
### Contact Details

Roturbo

### Feature for this project

Hi,

just notice that some friends have high level audio compared to others, maybe an AGC to control
or limit the audio output will help to balance decoded signals,, this is more evident on Rade mode.

Also the volume gain mic/speaker placed in main window will help for easy control on input and output
audio without have to go to Tools/Filter chose tab.

The new window that opens also may cover the signal from MIC on main window on small screens, 
and make it difficult to fine tune correct levels. 

![image](https://github.com/user-attachments/assets/ec2e6908-f0c8-4153-8a5f-fd58fc3a84e8)

The same slider takes 2 functions, it switch from RX to TX to control Speaker or Mic.

On the other modes we dind´t need to adjust this as it seems more controlled, but with Rade
some people appear with 2 or 3 times the audio volume compared to others.

Regards, and tanks for your hard work.

### VHF/UHF

None

### Deprecated features

None

### Non-standard compiler

None

### Non-standard compiler

None

### Implementation assistance

Sorry i can´t give much help as i don´t know coding, it is just one idea to improve the Gui usage.

### Support assistance

None, as this is a one time function implementation that will serve also for other modes,
so i think it will not need any future needs.

**Comment by tmiw** [comment]
Thanks for this! If you can find some other people who are interested, can you update the Contact Details field above accordingly?

**Comment by tmiw** [comment]
Haven't heard back so I'm going to close for now. Please update here once all required information has been provided and I will reopen.

**Comment by Roturbo** [comment]
Hello @tmiw 

The contact details i already have add my user, about other persons, i have 4 friends on a radio group
that agree with the volume control more accessible,  but what contact details you are asking ?

 Do you mean the contact of this persons that don´t participate on Github ??

Most programs have the output audio level control on main window, it is fast and practical 1 click, on FreeDV
to lower the audio we must lower the main volume of the PC or else take 4 steps/clicks till we reach the slider.

I thought that a suggested feature is something that someone present to improve the software and it is 
common sense that it is a logical thing to implement, and that it will benefit the usage
of the software in future by all the users, and not by some quantity of interested persons.


I have read some comments were people confirm the difference in audio level coming from other
modes to Rade, also cases were the receiver have to adjust this output levels in FreeDV because of
low audio output, on any case the AGC and volume control will benefit everyone and will make
the Gui more user friendly, if this is none sense than is not important how many people
wants a feature, because programming takes time and the developers have more important
features to focus.

So please you judge, if you think is relevant you may reopen, if not than for me is all ok,
i was just trying to help.

.

**Comment by tmiw** [comment]
> Hello @tmiw
> 
> The contact details i already have add my user, about other persons, i have 4 friends on a radio group that agree with the volume control more accessible, but what contact details you are asking ?
> 
> Do you mean the contact of this persons that don´t participate on Github ??

Yeah, we need the form completely filled out (including contact information even for those not on GH) to evaluate this.

**Comment by Roturbo** [comment]
Hi @tmiw 

i´m sorry but none of my friends wants to expose their contact details here, i have pointed this link
and they question me why the other feature requests, feature proposal etc don´t have contact details,
as you can imagine i was not able to explain because i also don´t know why.

Anyway, i respect your request but i´m not able to comply, maybe in future other people also ask
for this as they start to use FreeDV and feel the need to lower or increase the output volume.

Rade is really a very good DV mode, this weekend i look at the Reporter page and it was the first time
i see so many people testing this mode that i have to scroll down to see the end of the page, people
that already test the other modes gets convicted by Rade on first usage.

Local contacts that i have made on 10m in the range of 100 miles were done with less
than 15w, every long range and low power test we do is a surprise, so it will be only
a matter of short time for us to see the usage in much large scale.

So, many tanks for you and all the other developers involved, the ham community
deserves such a good DV mode without robotic voice, and they will be grateful.

Regards
