### ISSUE TITLE
2.0.0 - Recorded tones level is too high on replay into the decoder and there is a difference in output power between 700D and RADE.

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#763]
I have been using the 'Record' feature a lot during testing of RADE and find that the audio level is too high on playback of a recorded QSO especially for the local station.
There is also a difference between output audio level (i.e. power out) when switching over from 700D to RADE. The latter being much higher.

Maybe these level anomalies could be tidied up?

**Comment by tmiw** [comment]
Probably premature for that considering there's still things to implement on RADE. That said, the current code does set RADE about 4dB lower than what the TX Attenuation slider shows to ensure that people don't need to adjust it when switching back and forth.

**Comment by tmiw** [comment]
Closing this for now since no immediate action is required.
