### ISSUE TITLE
Build error Opensuse Tumbleweed - latest pre-release

### ISSUE THREAD

**Issue by rskunath** [drowe67/freedv-gui#768]
Building the latest source on Suse Tumbleweed and it errors out with: 

[CMakeFiles/build_sioclient.dir/build.make:86: build_sioclient-prefix/src/build_sioclient-stamp/build_sioclient-build] Error 2 

I do have all of the deps and devels installed. So not sure why it's not happy... any thoughts?

This was the tarball for the latest pre-release from the Freedv site. I did see some references to Freedv needing a newer version of sioclient than was used previously, but this is a new clean install and the sio client was pulled in via the build script. So, shouldn't that be current then for the prelease package?

TIA

**Comment by tmiw** [comment]
A few things:

1. Do you get this when you build from `master`?
2. Are you able to provide any build output from sioclient?

**Comment by rskunath** [comment]
I did a fresh rebuild from Master. A clean new clone. And I still have the same issue.

I don't see any output from the sioclient build except for the error in the main terminal. 

Maybe I need to examine the Linux install script and try building just the sioclient separately to see if I can get some additional info.

**Comment by rskunath** [comment]
I did see there is a distro version of sioclient. I did not have that installed because it wasn't listed as a dep. I installed that and saw the same error. There was no dev lib of that library though on TW.

It looked like from the output that there are many errors above the final fail on sioclient. It looked like it was still using the internal suppled static client for sioclient?

I attached the last part of the build output that has the errors, and I hope that will shed some light on what is going on.

TIA
[sioclient-errors.txt](https://github.com/user-attachments/files/17636386/sioclient-errors.txt)

**Comment by tmiw** [comment]
The errors look OpenSSL related. Do you have its libraries/development package installed?

**Comment by rskunath** [comment]
Yes, that was it Franco. Thanks for pointing me in the right direction.

libssl and libssl3 were missing the devel libs.I did install the sioclient from the distro too but I think the internal one is still used.

All builds fine now.

I didn't see that in the deps and I think that with the script running the build things scrolled away too fast for me to see what was being found and what wasn't.

Thanks to everyone who helped :)
