### ISSUE TITLE
[Software Issue]  "Radio device"

### ISSUE THREAD

**Issue by arblake** [drowe67/freedv-gui#782]
### Platform

Linux

### Platform Version

Uvuntu 24

### FreeDV Version

2.0.0-dev

### Steps to Reproduce

When I start easy setup, the box which is labeled "Radio device" is greyed and I cannot make a choice and thus the setup fails to complete. 

### Expected Behavior

A choice in the box

### Actual Behavior

cannot complete setup

**Comment by arblake** [comment]
I suspect the this message is the source of the problem. when i open the application i get this:
(freedv:116288): Gtk-CRITICAL **: 17:24:25.021: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

**Comment by tmiw** [comment]
Do you happen to have a screenshot that you can upload here? Also, if you click Cancel and go to Tools-Audio Options, what does that show your devices as?

**Comment by arblake** [comment]
Here is screen shot
![Screenshot from 2024-12-07 04-05-49](https://github.com/user-attachments/assets/761f0df0-6776-431d-9725-024b03e57bdb)

**Comment by tmiw** [comment]
What about if you click Advanced in Step 1? What does that dialog look like?

**Comment by arblake** [comment]
![Screenshot from 2024-12-08 11-58-36](https://github.com/user-attachments/assets/bcd82802-3b7e-49a6-9b1c-1fcea62da6d1)

**Comment by tmiw** [comment]
I suspect it's something with the naming of your radio device (presumably the C-Media one). Note how the input device ends in "mono-fallback" while the output one has "iec958-stereo" at the end. Easy Setup isn't designed for all scenarios, so it's perfectly okay to configure your audio by going into the Advanced audio config and manually selecting devices there. Hope that helps!

**Comment by arblake** [comment]
![Screenshot from 2024-12-08 11-58-36](https://github.com/user-attachments/assets/bcd82802-3b7e-49a6-9b1c-1fcea62da6d1)

**Comment by arblake** [comment]
resolved, Use Options from tools menu to configure.
