### ISSUE TITLE
[Feature request] PTT input (for use with foot petals, etc.)

### ISSUE THREAD

**Issue by tmiw** [drowe67/freedv-gui#80]
Per Siegfried Jackstien from the digitalvoice list, FreeDV should have a way to support PTT with foot switches, etc. (via CTS pin on serial port?)

**Comment by drowe67** [comment]
@tmiw I think this is a repeat of https://github.com/drowe67/freedv-gui/issues/51

**Comment by tmiw** [comment]
@drowe67, yep, agreed. Will close this one in favor of #51.
