### ISSUE TITLE
800xa mode does not work in 151 devel

### ISSUE THREAD

**Issue by DG9BFC** [drowe67/freedv-gui#81]
title says it all
in 141 devel the mode 800xa just works fine
in 151 devel it locks (signal to noise jumps up and it shows timing and delta frequency) ,, but no audio comes out of my speakers (tested in fullduplex over sat qo100)
all other modes do work fine
settings in both versions are the same
no idea why in 151 i have no audio out in that mode
win10 4 gig ram
greetz sigi dg9bfc

**Comment by DG9BFC** [comment]
tested now on a complezte different machine (core2duo and win7) ... before it was tested on win10 on an atom tablet (quadcore but no avx so no 2020 mode) ...
on the core2duo also no decode with 151
and guess what ... 141 receives just fine 
hmmm ... HEEEELLLPPP PLEASE 
greetz sigi dg9bfc

**Comment by drowe67** [comment]
@DG9BFC, we can't reproduce the problem.  Until we can reproduce it we can't fix it.

1. Does the [800XA test file](https://github.com/tmiw/freedv-gui/blob/pskreporter/wav/ve9qrp_800xa.wav) decode OK?
1. Pls post a screen shot of Help-About - this will let us check codec 2 version.
2. Please ask around with other users - can you find any other users who are experiencing this problem?
3. Pls record your off air 800XA signal and send us the file.  We will try to decode it.

@tmiw :point_up:

**Comment by tmiw** [comment]
@drowe67, @DG9BFC emailed me earlier to let me know that audio works on 1.5.1 if squelch is set to something negative. I was able to confirm on my end that that's the case and will create a PR on codec2 shortly.

**Comment by drowe67** [comment]
@DG9BFC @tmiw good work on tracking this one down :+1:

**Comment by DG9BFC** [comment]
Ok.. I found it.. Now its your turn to make the squelch in 800xa mode work similar to  the 141 devel versionGreetz sigi dg9bfcAm 04.01.2021 07:09 schrieb drowe67 <notifications@github.com>:

@DG9BFC @tmiw good work on tracking this one down 👍

**Comment by DG9BFC** [comment]
any precompiled version for me to try out?? ... greetz sigi dg9bfc
