### ISSUE TITLE
overscan on Scatter diagam

### ISSUE THREAD

**Issue by drowe67** [drowe67/freedv-gui#84]
I have been testing the latest Win 64 build (Version 1,5,1 devel FreeDV git hash 2578d57) via VAC loopback, checking the operation of  clipping and found that the unclipped 700D produced overscan on Scatter Screen (the points are outside the black screen and show up in the white border).The indicated SNR was 39dB.

All other modes were OK with 700E showing a SNR of 40dB and still displaying scatter screen correctly,

Peter VK5APR

**Comment by tmiw** [comment]
@drowe67, #146 seems like it fixes this issue too, agreed?
