### ISSUE TITLE
golay23.h required

### ISSUE THREAD

**Issue by ra1nb0w** [drowe67/freedv-gui#94]
the latest commit requires
```
:info:build /opt/local/var/macports/build/ports_science_freedv-gui/freedv-gui/work/freedv-gui-ee194ba1eb944c2de17b0c829e0b6ee53b109c8e/src/callsign_encoder.h:28:10: fatal error: 'golay23.h' file not found
:info:build #include "golay23.h"
:info:build          ^~~~~~~~~~~
```

**Comment by drowemyriota** [comment]
@tmiw is that something to do with the PSK reporter code?  How about adding the function headers for the few Golay functions you need inside the FreeDV source?  It's a tricky issue, sharing code between libcodec2 and freedv-gui without installing too many header files.

**Comment by tmiw** [comment]
@drowe67, yep. I created #95 to resolve the issue.

BTW, I'm probably going to play around more with the text field's encoding soon. Using full duplex and channel noise consistently results in zero decode (even at only 1dB noise) in my testing, which I'm not too thrilled about. In particular, I'm wondering if interleaving will help.

**Comment by ra1nb0w** [comment]
thank you!
