### ISSUE TITLE
PSK Reporter encoding/decoding improvements

### ISSUE THREAD

**Issue by tmiw** [drowe67/freedv-gui#97]
@drowe67, I'm creating this issue to brainstorm some thoughts I had for improving the PSK Reporter functionality. As of now, it uses Golay(23,12) for encoding, which falls hard on its face with channel noise other than 0dB (per local full duplex testing). I'm considering the following possibilities:

* Use normal Hadamard (not augmented) code with k=3, so a single character using the current PSK Reporter character set is encoded as two bytes of 7 bits each (the MSB is always 0 based on examples I've seen online, so we may be more tolerant of errors in certain cases).
* Interleave each coded character's bits. This would mean four bytes are needed to interleave two characters, eight for four, etc. In theory this should improve error correction, but I'm not sure by how much.
* Multi-pass decoding, possibly taking into account context-specific clues. (For instance, assuming 50% of the callsigns in existence are US callsigns, there's a 50% chance that the first 1-2 characters are K, N, W or AA-AL. Thus, perhaps we can weight possible candidates if we have more than a few bit errors.) This might take a lot more thinking and research to pull off, though.

Anyway, I haven't fully fleshed these out yet, so I'd be interested in suggestions or thoughts about the above.

**Comment by drowemyriota** [comment]
@tmiw a Golay code is a pretty good block code, so I'd be surprised if that is a weakness in the system.  Can you pls explain more about the failure at 0 dB SNR?  That's a pretty low SNR, so it it's good for SNRs >= 0dB you are doing well.

As I mentioned before - best break the PSK Reporter out as a function library and unit test it separately from freedv-gui, possibly at the codec2 level where API functions and tools exists to simulate the entire system.  You could then quickly simulate many messages and measure the packet error rate  on different channels, trapping any design and implementation issues. 

One possibility is some simple bug that's been missed as it's being tested in a integrated system.

**Comment by tmiw** [comment]
@drowe67, actually, I think I misunderstood how the Channel Noise option works. It looks like the dB setting for it basically causes FreeDV to produce enough noise to cause the SNR to drop to a maximum of whatever you select, *not* that it adds X dB of noise.

Anyway, at 5 dB for "Channel Noise" (which seems to produce a BER of ~0.02), the current Golay code seems to fall apart. It does get sync eventually, but I get random letters afterward. I wonder if it's possible that it'd have better results if it didn't just assume the first instance of the two sync characters is the correct one.

Speaking of which, I did manage to make some tweaks to make time to text sync time and possibly fix some display issues surrounding the PSK Reporter functionality. Perhaps we can start with those first? I'll test some more and create a PR tonight.

**Comment by drowemyriota** [comment]
> @drowe67, actually, I think I misunderstood how the Channel Noise option works. It looks like the dB setting for it basically causes FreeDV to produce enough noise to cause the SNR to drop to a maximum of whatever you select, _not_ that it adds X dB of noise.

The feature measures the signal power, then adds the appropriate amount of noise to achieve the specified SNR. This is approximate on real time signals - the non-real time simulation tools work better.  The SNR estimators for each mode aren't particularly well calibrated either.  I wouldn't be relying on these for super-accurate calibration and testing of any algorithm.

**Comment by tmiw** [comment]
@drowe67, good to know. I just created the PR for the display bug I noticed and a non-compatibility breaking tweak to improve sync time. 

I'm also working on the compatibility breaking stuff over at https://github.com/tmiw/freedv-gui/tree/psk_experimental. So far it looks like it's at least slightly improved over the current encoding but I'll need to test more (ideally with other people) to be sure.

**Comment by tmiw** [comment]
@drowe67, agree on closing this now that we have reliable_text/1.6.1?

**Comment by drowe67** [comment]
Ok yes - there is no doubt you have improved PSK reporter! :smile:

**Comment by tmiw** [comment]
Sounds good 👍
