### ISSUE TITLE
FreeDV 1.5.1 build program on Windows 10 Don't stand up

### ISSUE THREAD

**Issue by hiro2818** [drowe67/freedv-gui#99]
FreeDV1.5.1 source code
Using fedora cross-compilation
Create an executable program for Windows
Install on Windows 10
When I try to run it, I get an error and cannot run it
The error message is as follows.
It worked fine with FreeDV 1.5.0
Is there anything unusual?

Mismath bitween the program and libraly build versions detected
The Library Used 3.0 (wchar_t,compiler with C++ ABI 1013,wxcontainers.compatible with 2.8),
and your program Used 3.0 (wchar_t,compiler with C++ ABI 1014,wxcontainers.compatible with 2.8)

**Comment by hobbes1069** [comment]
Doesn't look like something specific to FreeDV... It looks like an ABI difference between what FreeDV was built with and what it's trying to run with. The only way I know of for this to happen is somehow different libraries are getting found by CPack that what it was built against.
